### ISSUE TITLE
手动识别蓝光电影出现报错

### ISSUE THREAD

**Issue by l552121229** [jxxghp/nas-tools#1111]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.0.5 d14fcf6d
>
> 环境: docker
>

## 你遇到什么问题了？

> 手动识别蓝光电影的时候报错

```
2022-09-13 22:03:28,928 INFO: 【RMT】开始处理：/data/data14T/download/other/Iron.Man.3.2013.2160p.BluRay.HEVC.DTS-HD.MA.7.1-BB/，转移方式：硬链接
2022-09-13 22:03:28,929 INFO: 【RMT】当前为蓝光原盘文件夹：/data/data14T/download/other/Iron.Man.3.2013.2160p.BluRay.HEVC.DTS-HD.MA.7.1-BB/
2022-09-13 22:03:28,946 ERROR: 【RMT】发生错误：'NoneType' object has no attribute 'get_movie_category' - Traceback (most recent call last):
  File "/nas-tools/app/media/media.py", line 785, in get_media_info_on_files
    meta_info.set_tmdb_info(tmdb_info)
  File "/nas-tools/app/media/meta/metabase.py", line 411, in set_tmdb_info
    self.category = self.category_handler.get_movie_category(info)
AttributeError: 'NoneType' object has no attribute 'get_movie_category'

2022-09-13 22:03:28,946 ERROR: 【RMT】检索媒体信息出错！
```

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是的

2022-09-13 22:03:28,928 INFO: 【RMT】开始处理：/data/data14T/download/other/Iron.Man.3.2013.2160p.BluRay.HEVC.DTS-HD.MA.7.1-BB/，转移方式：硬链接
2022-09-13 22:03:28,929 INFO: 【RMT】当前为蓝光原盘文件夹：/data/data14T/download/other/Iron.Man.3.2013.2160p.BluRay.HEVC.DTS-HD.MA.7.1-BB/
2022-09-13 22:03:28,946 ERROR: 【RMT】发生错误：'NoneType' object has no attribute 'get_movie_category' - Traceback (most recent call last):
  File "/nas-tools/app/media/media.py", line 785, in get_media_info_on_files
    meta_info.set_tmdb_info(tmdb_info)
  File "/nas-tools/app/media/meta/metabase.py", line 411, in set_tmdb_info
    self.category = self.category_handler.get_movie_category(info)
AttributeError: 'NoneType' object has no attribute 'get_movie_category'

2022-09-13 22:03:28,946 ERROR: 【RMT】检索媒体信息出错！

**Comment by jxxghp** [comment]
你是不是自己改了分类的配置文件，而且格式改错了？

**Comment by l552121229** [comment]
> 你不是自己改分类的配置文件，而且格式改错了？

我记得好像是没有改动过, 你这里也可以试试检索一下 id 为`1726`的这个电影

<img width="533" alt="Xnip2022-09-17_23-54-12" src="https://user-images.githubusercontent.com/35548398/190865554-e95b00b3-9838-4e99-86b1-c212c1b3bb1d.png">

```
2022-09-17 23:46:41,152	INFO: 【META】正在查询TMDB电影：1726 ...
2022-09-17 23:46:41,324	INFO: 【RMT】开始处理：/data/data14T/download/other/Iron.Man.2008.2160p.BluRay.HEVC.TrueHD.7.1.Atmos-BHD/，转移方式：硬链接
2022-09-17 23:46:41,325	INFO: 【RMT】当前为蓝光原盘文件夹：/data/data14T/download/other/Iron.Man.2008.2160p.BluRay.HEVC.TrueHD.7.1.Atmos-BHD/
2022-09-17 23:46:41,326	ERROR: 【RMT】发生错误：'NoneType' object has no attribute 'get_movie_category' - Traceback (most recent call last):
  File "/nas-tools/app/media/media.py", line 785, in get_media_info_on_files
    meta_info.set_tmdb_info(tmdb_info)
  File "/nas-tools/app/media/meta/metabase.py", line 411, in set_tmdb_info
    self.category = self.category_handler.get_movie_category(info)
AttributeError: 'NoneType' object has no attribute 'get_movie_category'

2022-09-17 23:46:41,327	ERROR: 【RMT】检索媒体信息出错！
```
