### ISSUE TITLE
签到bug[cannot connect to chrome at 127.0.0.1:54721 from chrome not reachable]

### ISSUE THREAD

**Issue by DDS-ALL** [jxxghp/nas-tools#1430]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.0
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

```
2022-10-06 20:06:16,474	ERROR: 【SITES】HDTime 签到出错：Message: unknown error: cannot connect to chrome at 127.0.0.1:37643
from chrome not reachable
 - Traceback (most recent call last):
  File "/nas-tools/app/sites/sites.py", line 221, in signin
    browser = ChromeHelper(ua=ua).get_browser()
  File "/nas-tools/app/utils/commons.py", line 21, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/helper/chrome_helper.py", line 20, in __init__
    self.init_config()
  File "/nas-tools/app/helper/chrome_helper.py", line 37, in init_config
    self._chrome = uc.Chrome(options=options, driver_executable_path=self._executable_path)
  File "/usr/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 401, in __init__
    super(Chrome, self).__init__(
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 589, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:37643
from chrome not reachable


2022-10-06 20:07:17,186	ERROR: 【SITES】PTMSG 签到出错：Message: unknown error: cannot connect to chrome at 127.0.0.1:54721
from chrome not reachable
 - Traceback (most recent call last):
  File "/nas-tools/app/sites/sites.py", line 221, in signin
    browser = ChromeHelper(ua=ua).get_browser()
  File "/nas-tools/app/utils/commons.py", line 21, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/helper/chrome_helper.py", line 20, in __init__
    self.init_config()
  File "/nas-tools/app/helper/chrome_helper.py", line 37, in init_config
    self._chrome = uc.Chrome(options=options, driver_executable_path=self._executable_path)
  File "/usr/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 401, in __init__
    super(Chrome, self).__init__(
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 589, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:54721
from chrome not reachable
```
```
root@nas-tools:/nas-tools $ ps -ef
PID   USER     TIME  COMMAND
    1 1000      0:01 {supervisord} /usr/bin/python3 /usr/bin/supervisord -n -c /nas-tools/supervisord.conf
   23 1000      0:04 python3 run.py
   25 1000      0:00 Xvfb -br -nolisten tcp -screen 0 1920x1080x24 -displayfd 4
   27 root      0:00 bash
   33 root      0:00 ps -ef
```
```
PUID=1000
PGID=1000
```

**Comment by DDS-ALL** [comment]
我这边再研究研究

估计还是权限问题

找到原因了向你反馈

**Comment by DDS-ALL** [comment]
```
root@nas-tools:/nas-tools $ ls -al /usr/lib/chromium/
total 216156
drwxr-xr-x    1 1000     1000          4096 Oct  6 18:44 .
drwxr-xr-x    1 root     root          4096 Oct  6 18:46 ..
drwxr-xr-x    1 1000     1000          4096 Oct  6 18:44 MEIPreload
-rwxr-xr-x    1 1000     1000     188173672 Sep 28 23:14 chrome
-rwxr-xr-x    1 1000     1000         14560 Sep 28 23:14 chrome-sandbox
-rw-r--r--    1 1000     1000        589879 Sep 28 23:14 chrome_100_percent.pak
-rw-r--r--    1 1000     1000        874312 Sep 28 23:14 chrome_200_percent.pak
-rwxr-xr-x    1 1000     1000        895920 Sep 28 23:14 chrome_crashpad_handler
-rwxr-xr-x    1 1000     1000      11754264 Oct  6 19:59 chromedriver
-rwxr-xr-x    1 1000     1000          1180 Sep 28 23:14 chromium-launcher.sh
-rw-r--r--    1 1000     1000       1438207 Sep 28 23:14 headless_lib_data.pak
-rw-r--r--    1 1000     1000       2605889 Sep 28 23:14 headless_lib_strings.pak
-rwxr-xr-x    1 1000     1000         59872 Sep 28 23:14 libEGL.so
-rwxr-xr-x    1 1000     1000       6151440 Sep 28 23:14 libGLESv2.so
-rwxr-xr-x    1 1000     1000        360096 Sep 28 23:14 libvulkan.so.1
drwxr-xr-x    1 1000     1000          4096 Oct  6 18:44 locales
-rw-r--r--    1 1000     1000       7141199 Sep 28 23:14 resources.pak
-rw-r--r--    1 1000     1000        407280 Sep 28 23:14 snapshot_blob.bin
-rw-r--r--    1 1000     1000        730520 Sep 28 23:14 v8_context_snapshot.bin
-rwxr-xr-x    1 1000     1000         37394 Sep 28 23:14 xdg-mime
-rwxr-xr-x    1 1000     1000         33273 Sep 28 23:14 xdg-settings
```
这边chrome文件夹权限也没有问题

**Comment by DDS-ALL** [comment]
我这边还有一个线索，就是更新镜像前我提前更新了源码，并且测试是正常的，可以正常签到，而更新镜像后，就不能正常使用了

**Comment by DDS-ALL** [comment]
我怀疑是不是镜像的问题

**Comment by DDS-ALL** [comment]
退回v2.1.3版本，再升级到v2.2.0，再次签到，就正常了

**Comment by DDS-ALL** [comment]
接下来我也解决不了了，只能给这些线索了

**Comment by DDS-ALL** [comment]
```
PID   USER     TIME  COMMAND
    1 1000      0:01 {supervisord} /usr/bin/python3 /usr/bin/supervisord -n -c /nas-tools/supervisord.conf
   25 1000      0:12 python3 run.py
   27 1000      0:00 Xvfb -br -nolisten tcp -screen 0 1920x1080x24 -displayfd 4
   87 1000      0:03 [chromedriver]
  115 1000      0:03 [chromedriver]
  130 1000      0:00 [python3]
  131 1000      0:00 /usr/lib/chromium/chrome --disable-gpu --no-sandbox --ignore-certificate-errors --disable-dev-shm-usage --remote-debugging-host=127.0.0.1 --remote-debugging-p
  132 1000      0:00 /usr/lib/chromium/chromedriver --port=46593
  140 root      0:00 bash
  153 root      0:00 ps -ef
```

**Comment by DDS-ALL** [comment]
我在supervisor这边找到了新线索
```
2022-10-06 21:17:42,189 INFO reaped unknown pid 90 (terminated by SIGPIPE)
```

**Comment by DDS-ALL** [comment]
我这边还是没有找到原因，root用户就可以正常运行，说明也不是版本的原因

**Comment by DDS-ALL** [comment]
权限我又检查了一遍，都是正常的，还是找不到原因

**Comment by DDS-ALL** [comment]
并且我通过查看进程，发现Chrome是启动了，是python程序连接不到Chrome

**Comment by DDS-ALL** [comment]
![](https://github.com/DDS-Derek/img/raw/main/2022/10/06/88FAD3BF-C48D-40D3-8398-D2126B50AC73.jpeg)

**Comment by DDS-ALL** [comment]
我这边又有新的发现了，不是权限问题，我在我的Windows docker上测试，
```
PUID=1000
PGID=1000
```
```
root@nastools:/nas-tools $ ps -ef
PID   USER     TIME  COMMAND
    1 1000      0:00 {supervisord} /usr/bin/python3 /usr/bin/supervisord -n -c /nas-tools/supervisord.conf
   28 root      0:00 /bin/sh
   35 1000      0:08 python3 run.py
   37 1000      0:00 Xvfb -br -nolisten tcp -screen 0 1920x1080x24 -displayfd 4
   99 1000      0:00 [python3]
  100 1000      0:04 /usr/lib/chromium/chrome --extra-plugin-dir=/usr/lib/nsbrowser/plugins --disable-gpu --no-sandbox
  103 1000      0:00 /usr/lib/chromium/chromedriver --port=55645
  111 1000      0:00 /usr/lib/chromium/chrome --type=zygote --no-zygote-sandbox --no-sandbox --log-level=0 --enable-cra
  112 1000      0:00 /usr/lib/chromium/chrome --type=zygote --no-sandbox --log-level=0 --enable-crashpad --crashpad-han
  134 1000      0:01 /usr/lib/chromium/chrome --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-
  135 1000      0:00 /usr/lib/chromium/chrome --type=utility --utility-sub-type=storage.mojom.StorageService --lang=en-
  258 1000      0:01 /usr/lib/chromium/chrome --type=gpu-process --no-sandbox --disable-dev-shm-usage --log-level=0 --e
  267 1000      0:04 /usr/lib/chromium/chrome --type=renderer --enable-crashpad --crashpad-handler-pid=0 --enable-crash
  280 1000      0:00 /usr/lib/chromium/chrome --type=renderer --enable-crashpad --crashpad-handler-pid=0 --enable-crash

```
程序可以正常运行，这也验证了我前面的猜想：python程序连接不到Chrome

> 并且我通过查看进程，发现Chrome是启动了，是python程序连接不到Chrome

**Comment by Stonestonestone** [comment]
> 我这边还是没有找到原因，root用户就可以正常运行，说明也不是版本的原因

同上，同时在logs中报 `INFO reaped unknown pid 85 (terminated by SIGPIPE)`;经测试PUID及PGID改为0才行就没问题；

**Comment by DDS-ALL** [comment]
我这边又尝试了`106.0.5249.103-r0` `99.0.4844.84-r0` 版本的chromium-chromedriver，问题依旧，目前就 `102.0.5005.173` 版本可以，但是alpine软件库这个版本已经没有，所以暂时没有任何合适的解决办法

**Comment by DDS-ALL** [comment]
目前最好的解决方法是，拉取 `2.1.3` 版本的镜像，自动升级到 `2.2.0` ,再进入容器内部，输入
```
curl https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o /usr/bin/mc && \
chmod +x /usr/bin/mc
```
就可以正常使用了

**Comment by Stonestonestone** [comment]
> 目前最好的解决方法是，拉取 `2.1.3` 版本的镜像，自动升级到 `2.2.0` ,再进入容器内部，输入
> 
> ```
> curl https://dl.min.io/client/mc/release/linux-amd64/mc --create-dirs -o /usr/bin/mc && \
> chmod +x /usr/bin/mc
> ```
> 
> 重启 就可以正常使用了

我直接PUIDGID=0了，反正umask设置了0000，免得后续再出类似的问题，每次exec一下也挺烦的

**Comment by DDS-ALL** [comment]
今天我又研究了一下，问题依旧，基本在我能力范围内的方法都折腾过了，看看有没有其他大佬能解决吧

**Comment by DDS-ALL** [comment]
目前我想出来的解决办法就是**外置Chrome**，外置Chrome以后就不会受到版本的影响，因为可以拉固定的Chrome镜像，一般专业的Chrome镜像也不会出现兼容性问题，所以我觉得外置Chrome是目前不错的办法

这个问题昨天我也请教了ChineseSubFinder的作者allanpk716大佬了，这是大佬的回复
```
我看了 issue 也没搞清楚为啥出问题···

不清楚为啥，看搜索的资料都没法确认问题，只能对比发现有问题，没得明确的解决方案
```
allanpk716大佬也没有解决办法

**Comment by DDS-ALL** [comment]
我这边还有一个想法，chromium-chromedriver问题都是在非root环境下才会出现的，那能不能把控制Chrome和主程序分开，控制Chrome用root用户，而主程序用设置的PUID和PGID

**Comment by DDS-ALL** [comment]
因为版本更新和日志更新的原因

现在报错为
```
2022-10-16 22:18:56,480	INFO: 【Sites】开始站点仿真签到：PTMSG
Message: unknown error: cannot connect to chrome at 127.0.0.1:53075
from chrome not reachable

2022-10-16 22:19:57,278	ERROR: 【Sites】PTMSG 无法打开网站
Message: unknown error: cannot connect to chrome at 127.0.0.1:51599
from chrome not reachable
```
当然，主问题肯定还是跟以前一样，还是没有找到解决办法

**Comment by DDS-ALL** [comment]
我这边又发现了一个新扩展

https://pypi.org/project/chromedriver-autoinstaller/

通过这个扩展下载的chromedrive有可能就不会出现上诉问题，作者有时间可以尝试一下

**Comment by DDS-ALL** [comment]
我最终判断是chrome的兼容性问题，因为在其他linux主机上都是可以非root用户正常签到的，而我测试的j1900就不行。所以解决这个问题唯一的方法，也是可以永久解决的方法就是把调用chrome部分分离，用root用户来调用chrome

**Comment by DDS-ALL** [comment]
我把此issued关了，以后有新发现再开吧

**Comment by DDS-ALL** [comment]
我这边有新发现，有可能可以解决这个问题

从下面两张图片可以看出chrome启动的端口是60907，而nastools连接chrome的端口是47593

我不确定这样是否正常，希望作者可以回复一下


![](https://github.com/DDS-Derek/img/raw/main/2022/11/18/CBEDBBF8-A624-407A-B17F-3D657DBA91EB.jpeg)

![](https://github.com/DDS-Derek/img/raw/main/2022/11/18/76E082D2-B37A-46D4-8B87-15F7DAF67F76.jpeg)

**Comment by Stonestonestone** [comment]
> 我这边有新发现，有可能可以解决这个问题
> 
> 从下面两张图片可以看出chrome启动的端口是60907，而nastools连接chrome的端口是47593
> 
> 我不确定这样是否正常，希望作者可以回复一下
> 
> ![](https://github.com/DDS-Derek/img/raw/main/2022/11/18/CBEDBBF8-A624-407A-B17F-3D657DBA91EB.jpeg)
> 
> ![](https://github.com/DDS-Derek/img/raw/main/2022/11/18/76E082D2-B37A-46D4-8B87-15F7DAF67F76.jpeg)

我尝试了一下，这个端口不是固定的；
![图片](https://user-images.githubusercontent.com/26944865/206939780-05d75f33-e1a1-4583-8cc6-3ee8737bee58.png)
![图片](https://user-images.githubusercontent.com/26944865/206939955-7ad0b344-b438-452e-a81c-75a606b4211c.png)

**Comment by Stonestonestone** [comment]
![图片](https://user-images.githubusercontent.com/26944865/206940295-6eff1ebd-589d-4ab3-a95c-942a72a0de0c.png)
root运行的时候日志完全不同（我不清楚图片中是否存在隐私，如果发现有涉及隐私的部分麻烦提醒我修改一下，谢谢）

**Comment by DDS-ALL** [comment]
> > 我这边有新发现，有可能可以解决这个问题
> > 从下面两张图片可以看出chrome启动的端口是60907，而nastools连接chrome的端口是47593
> > 我不确定这样是否正常，希望作者可以回复一下
> > ![](https://github.com/DDS-Derek/img/raw/main/2022/11/18/CBEDBBF8-A624-407A-B17F-3D657DBA91EB.jpeg)
> > ![](https://github.com/DDS-Derek/img/raw/main/2022/11/18/76E082D2-B37A-46D4-8B87-15F7DAF67F76.jpeg)
> 
> 我尝试了一下，这个端口不是固定的； ![图片](https://user-images.githubusercontent.com/26944865/206939780-05d75f33-e1a1-4583-8cc6-3ee8737bee58.png) ![图片](https://user-images.githubusercontent.com/26944865/206939955-7ad0b344-b438-452e-a81c-75a606b4211c.png) 不清楚这个运行的逻辑，浏览器拟真的时候端口是如何绑定的，但确实未对应上；我再试试root运行看看

这个问题目前还是没有解决思路，我现在的解决方案是以root用户运行，然后配合我自己写的脚步给文件设置合适的权限

**Comment by Stonestonestone** [comment]
以root权限运行，设置umask为0000能解决硬链等文件的权限问题。后续如果确认没有问题我再考虑设置PUIDPGID

**Comment by jxxghp** [comment]
#2381
