### ISSUE TITLE
BDMV格式转移失败

### ISSUE THREAD

**Issue by Nothend** [jxxghp/nas-tools#1502]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.0 c256bc59
>
> 环境: docker or windows or Synology
>Synology 中的 docker

## 你遇到什么问题了？

> BDMV格式转移失败

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 寻求解决方案

### 1.我的蓝光电影已经用tmm刮削好了，如下图
  
![image](https://user-images.githubusercontent.com/73117056/194820222-780406dd-77c7-49f5-9164-303bd1147435.png)

  目录中含有bdmv目录。

### 3.使用手动识别，选择电影的主目录，比如这里的“**哈利·波特与魔法石 (2001)**”，界面提示“转移成功”，但是日志中却提示错误，如下：
   `15:55:30 INFO - 【META】正在查询TMDB电影：671 ...

15:55:30 INFO - 【RMT】开始处理：/PT1/movie/哈利·波特与魔法石 (2001)/，转移方式：硬链接

15:55:30 INFO - 【RMT】当前为蓝光原盘文件夹：/PT1/movie/哈利·波特与魔法石 (2001)/

15:55:30 ERROR - 【RMT】文件转移时发生错误：expected str, bytes or os.PathLike object, not NoneType - Traceback (most recent call last): File "/nas-tools/app/filetransfer.py", line 614, in transfer_media dir_exist_flag, ret_dir_path, file_exist_flag, ret_file_path = self.__is_media_exists(dist_path, media) File "/nas-tools/app/filetransfer.py", line 845, in __is_media_exists dir_name, file_name = self.get_moive_dest_path(media) File "/nas-tools/app/filetransfer.py", line 1128, in get_moive_dest_path format_dict = self.get_format_dict(media_info) File "/nas-tools/app/filetransfer.py", line 1108, in get_format_dict "original_name": StringUtils.clear_file_name(os.path.splitext(media.org_string)[0]), File "/usr/lib/python3.10/posixpath.py", line 118, in splitext p = os.fspath(p) TypeError: expected str, bytes or os.PathLike object, not NoneType
15:55:30 INFO - 【RMT】/PT1/movie/哈利·波特与魔法石 (2001)/ 处理完成，总数：1，失败：0`

### 4.如果选择“**哈利·波特与魔法石 (2001)/BDMV**”这个目录，则可以转移成功，日志正常，但是emby却无法识别，出现几十个0000X文件名的内容。
   `15:57:44 INFO - 【META】正在查询TMDB电影：671 ...
15:57:44 INFO - 【RMT】开始处理：/PT1/movie/哈利·波特与魔法石 (2001)/BDMV/，转移方式：硬链接

15:57:44 INFO - 【RMT】当前为蓝光原盘文件夹：/PT1/movie/哈利·波特与魔法石 (2001)/BDMV/

15:57:44 INFO - 【RMT】正在硬链接目录：/PT1/movie/哈利·波特与魔法石 (2001)/BDMV 到 /PT1/links/emby_movie/外语电影/哈利·波特与魔法石 (2001)

15:57:44 INFO - 【RMT】文件 /PT1/movie/哈利·波特与魔法石 (2001)/BDMV 硬链接完成

15:57:44 INFO - 【META】正在查询TMDB电影：671 ...

15:57:44 INFO - 【MSG】发送wechat消息：title=哈利·波特与魔法石 (2001) 转移完成, text=评分：7.9，类型：电影，类别：外语电影，大小：4.0K，来自：手动整理

15:57:45 INFO - 【NFO】正在生成电影NFO文件：哈利·波特与魔法石 (2001)

15:57:45 INFO - 【NFO】正在保存 poster 图片：/PT1/links/emby_movie/外语电影/哈利·波特与魔法石 (2001)

15:57:49 INFO - 【NFO】正在保存 fanart 图片：/PT1/links/emby_movie/外语电影/哈利·波特与魔法石 (2001)

15:57:56 INFO - 【NFO】正在保存 background 图片：/PT1/links/emby_movie/外语电影/哈利·波特与魔法石 (2001)

15:57:58 INFO - 【NFO】正在保存 logo 图片：/PT1/links/emby_movie/外语电影/哈利·波特与魔法石 (2001)

15:58:02 INFO - 【NFO】正在保存 disc 图片：/PT1/links/emby_movie/外语电影/哈利·波特与魔法石 (2001)

15:58:05 INFO - 【NFO】正在保存 banner 图片：/PT1/links/emby_movie/外语电影/哈利·波特与魔法石 (2001)

15:58:09 INFO - 【NFO】正在保存 thumb 图片：/PT1/links/emby_movie/外语电影/哈利·波特与魔法石 (2001)

15:58:11 INFO - 【EMBY】开始刷新Emby媒体库...

15:58:11 INFO - 【RMT】/PT1/movie/哈利·波特与魔法石 (2001)/BDMV/ 处理完成，总数：1，失败：0

15:58:11 INFO - 【SUBTITLE】通知ChineseSubFinder下载字幕: /PT1/links/emby_movie/外语电影/哈利·波特与魔法石 (2001)/哈利·波特与魔法石 (2001).mp4

15:58:12 INFO - 【SUBTITLE】ChineseSubFinder任务添加成功：
1255c3a4472b33c534723a9ad4fad13afc056838bc2dc49df2b6985389fbcfea`

 
![image](https://user-images.githubusercontent.com/73117056/194821329-e16caad3-d9c7-416d-8640-3ff59a9b8aa0.png)

**Comment by Nothend** [comment]
1.又试了一下，直接把源文件“**哈利·波特与魔法石 (2001)**”拷贝到hlinks里面，emby是识别的，看来确实是转移的问题。
2.我又用nastool自己的识别试了下，过程是这样的，先把“**哈利·波特与魔法石 (2001)**”移动到其他跟nastool无关的目录，然后再移动回nastool监控的目录，nastool自动识别，日志提示以下错误：
   `16:18:20 INFO - 【SYNC】开始转移监控目录文件...

16:18:20 INFO - 【RMT】开始处理：/PT1/movie/哈利·波特与魔法石 (2001)/BDMV/BACKUP，转移方式：硬链接

16:18:22 INFO - 【META】index bdmv 以年份 在TMDB中未找到电影信息!

16:18:22 INFO - 【META】index bdmv 以年份 在TMDB中未找到电影信息!

16:18:22 INFO - 【META】正在从TheDbMovie网站查询：index bdmv ...

16:18:26 INFO - 【META】index bdmv TMDB网站未查询到媒体信息！

16:18:26 WARN - 【RMT】index.bdmv 无法识别媒体信息！

16:18:26 ERROR - 【RMT】index.bdmv 无法识别媒体信息！

16:18:26 INFO - 【RMT】/PT1/movie/哈利·波特与魔法石 (2001)/BDMV/BACKUP 处理完成，总数：1，失败：1

16:18:26 INFO - 【MSG】发送wechat消息：title=/PT1/movie/哈利·波特与魔法石 (2001)/BDMV/BACKUP 有 1 个文件转移失败，请登录NASTool查看, text=
16:18:27 WARN - 【SYNC】/PT1/movie/哈利·波特与魔法石 (2001)/BDMV/BACKUP转移失败：无法识别媒体信息`

**Comment by YoshiPark** [comment]
蓝光电影好像有m2ts格式文件也无法识别

**Comment by jxxghp** [comment]
原盘是要指定BDMV目录的上级目录，且不能一个种子的目录的下有多个原盘文件夹。

**Comment by YoshiPark** [comment]
> 原盘是要指定BDMV目录的上级目录，且不能一个种子的目录的下有多个原盘文件夹。

22:35:58 ERROR - 【Sync】/media3/video/movie 处理失败：无法识别媒体信息
22:35:58 INFO - 【RMT】开始处理：/media3/video/movie/[成龙]1979.龙拳.德版.DIY原盘国粤双语中字.Blu.Ray，转移方式：硬链接
22:35:58 WARN - 【RMT】00001.m2ts 无法识别媒体信息！
22:35:58 ERROR - 【RMT】00001.m2ts 无法识别媒体信息！
22:35:58 WARN - 【RMT】00283.m2ts 无法识别媒体信息！
22:35:59 ERROR - 【RMT】00283.m2ts 无法识别媒体信息！
22:35:59 WARN - 【RMT】00285.m2ts 无法识别媒体信息！
22:35:59 ERROR - 【RMT】00285.m2ts 无法识别媒体信息！
22:35:59 WARN - 【RMT】00282.m2ts 无法识别媒体信息！
22:35:59 ERROR - 【RMT】00282.m2ts 无法识别媒体信息！
22:35:59 WARN - 【RMT】00202.m2ts 无法识别媒体信息！
22:36:00 ERROR - 【RMT】00202.m2ts 无法识别媒体信息！
22:36:00 WARN - 【RMT】00201.m2ts 无法识别媒体信息！
22:36:01 ERROR - 【RMT】00201.m2ts 无法识别媒体信息！
22:36:01 WARN - 【RMT】00287.m2ts 无法识别媒体信息！
22:36:01 ERROR - 【RMT】00287.m2ts 无法识别媒体信息！
22:36:01 WARN - 【RMT】00011.m2ts 无法识别媒体信息！
22:36:01 ERROR - 【RMT】00011.m2ts 无法识别媒体信息！
22:36:01 WARN - 【RMT】00208.m2ts 无法识别媒体信息！
22:36:02 ERROR - 【RMT】00208.m2ts 无法识别媒体信息！
22:36:02 WARN - 【RMT】00288.m2ts 无法识别媒体信息！
22:36:02 ERROR - 【RMT】00288.m2ts 无法识别媒体信息！
22:36:02 WARN - 【RMT】00204.m2ts 无法识别媒体信息！
22:36:02 ERROR - 【RMT】00204.m2ts 无法识别媒体信息！
22:36:02 WARN - 【RMT】00103.m2ts 无法识别媒体信息！
22:36:03 ERROR - 【RMT】00103.m2ts 无法识别媒体信息！
22:36:03 WARN - 【RMT】00286.m2ts 无法识别媒体信息！
22:36:03 ERROR - 【RMT】00286.m2ts 无法识别媒体信息！
22:36:03 WARN - 【RMT】00281.m2ts 无法识别媒体信息！
22:36:03 ERROR - 【RMT】00281.m2ts 无法识别媒体信息！
22:36:03 WARN - 【RMT】00284.m2ts 无法识别媒体信息！
22:36:04 ERROR - 【RMT】00284.m2ts 无法识别媒体信息！
22:36:04 WARN - 【RMT】00203.m2ts 无法识别媒体信息！
22:36:04 ERROR - 【RMT】00203.m2ts 无法识别媒体信息！
22:36:04 WARN - 【RMT】00302.m2ts 无法识别媒体信息！
22:36:04 ERROR - 【RMT】00302.m2ts 无法识别媒体信息！
22:36:04 WARN - 【RMT】00207.m2ts 无法识别媒体信息！
22:36:05 ERROR - 【RMT】00207.m2ts 无法识别媒体信息！
22:36:05 WARN - 【RMT】00205.m2ts 无法识别媒体信息！
22:36:05 ERROR - 【RMT】00205.m2ts 无法识别媒体信息！
22:36:05 WARN - 【RMT】00206.m2ts 无法识别媒体信息！
22:36:05 ERROR - 【RMT】00206.m2ts 无法识别媒体信息！
22:36:05 WARN - 【RMT】00101.m2ts 无法识别媒体信息！
22:36:06 ERROR - 【RMT】00101.m2ts 无法识别媒体信息！
22:36:06 INFO - 【RMT】/media3/video/movie/[成龙]1979.龙拳.德版.DIY原盘国粤双语中字.Blu.Ray 处理完成，总数：21，失败：21

这种事没有办法识别是吗？

**Comment by jxxghp** [comment]
/media3/video/movie/[成龙]1979.龙拳.德版.DIY原盘国粤双语中字.Blu.Ray

这个目录下的文件结构截图看看

**Comment by YoshiPark** [comment]
> /media3/video/movie/[成龙]1979.龙拳.德版.DIY原盘国粤双语中字.Blu.Ray
> 
> 这个目录下的文件结构截图看看

![微信图片_20221012230515](https://user-images.githubusercontent.com/20967749/195379523-cedff128-80e4-4719-86b9-21c62d29d65a.png)
![微信图片_20221012230744](https://user-images.githubusercontent.com/20967749/195379924-05138450-e32a-4ecc-9c9e-bc4f3fbcc025.png)
![微信图片_20221012230749](https://user-images.githubusercontent.com/20967749/195379948-1ccdd535-0df2-448d-8421-e9771eb78bab.png)

**Comment by Nothend** [comment]
> 原盘是要指定BDMV目录的上级目录，且不能一个种子的目录的下有多个原盘文件夹。

多谢大佬百忙之中回复，我选择的就是BDMV 的上级目录，同时其他目录也试了，不知道怎么回事，有的BDMV 可以识别并硬链接正确，有的就不行，目录结构跟上面的朋友一样的

**Comment by jxxghp** [comment]
你这个就是多层文件夹呀，原盘合集不支持

**Comment by Nothend** [comment]
> 你这个就是多层文件夹呀，原盘合集不支持

好的，谢谢大佬，那我把合集里面的，单独拷出来行吗？

**Comment by goofysun** [comment]
问题类似，原盘文件夹转移成功，但是会多出来一个 index(2018)，几乎每个BDMV的原盘都会多出来

正在转移文件：index.bdmv
=> /video/links/电影/外语电影/Index (2018)/Index (2018).bdmv

**Comment by cearychua** [comment]
一样的问题.一百多个PT上下载的蓝光原盘电影,大部分都是错误.崩溃了

**Comment by 120318** [comment]
当前对于嵌套蓝光原盘目录支持不够好，比如媒体库是 `/movie`：
1. `/movie/Spider Man/BDMV/index.bdmv`可以可以成功转移，这是最简单的情况。
2. `/movie/Spider Collection/Spider Man/BDMV/index.bdmv` 会去尝试识别`Spider Collection`，如果识别成功，可以成功转移，但是刮削信息是不准的，因为无法认为`Spider Collection`是哪部电影。这是合集。
3. `/movie/Action/Spider Man/BDMV/index.bdmv` 会去尝试识别`Action`，这就很难识别成功了，因为`Action`识别不出来啥，这只是一个分类目录。
4. `/movie/Spider Collection/Breaking Bad/S01D01/BDMV/index.bdmv`，可以成功转移。这是剧集。

2和3的情况就导致
现在需要一些能力去区分到底是：1. 合集，2. 单纯的分类（目录无限嵌套），3. 剧集的多个part（电视剧原盘（S01D01,S02D02...）

**Comment by Nothend** [comment]
> 当前对于嵌套蓝光原盘目录支持不够好，比如媒体库是 `/movie`：
> 
> 1. `/movie/Spider Man/BDMV/index.bdmv`可以可以成功转移，这是最简单的情况。
> 2. `/movie/Spider Collection/Spider Man/BDMV/index.bdmv` 会去尝试识别`Spider Collection`，如果识别成功，可以成功转移，但是刮削信息是不准的，因为无法认为`Spider Collection`是哪部电影。这是合集。
> 3. `/movie/Action/Spider Man/BDMV/index.bdmv` 会去尝试识别`Action`，这就很难识别成功了，因为`Action`识别不出来啥，这只是一个分类目录。
> 4. `/movie/Spider Collection/Breaking Bad/S01D01/BDMV/index.bdmv`，可以成功转移。这是剧集。
> 
> 2和3的情况就导致 现在需要一些能力去区分到底是：1. 合集，2. 单纯的分类（目录无限嵌套），3. 剧集的多个part（电视剧原盘（S01D01,S02D02...）

目前就是这样，我现在把蓝光原盘的，单独放一个文件夹，然后让emby去识别，没问题的
