### ISSUE TITLE
运行一段时间后WEB页面无法打开

### ISSUE THREAD

**Issue by chris5641** [jxxghp/nas-tools#1560]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.2.1
>
> 环境: docker 
>

## 你遇到什么问题了？

> 群晖docker版，每次运行NASTool一段时间后，web页面就无法访问了，但是后台识别、转移、推送都还是正常的

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

```
2022-10-12 13:22:27,913	INFO: 已启用https，请使用 https://IP:3000 访问管理页面
2022-10-12 13:22:27,913	INFO: TMDB匹配模式：正常模式
2022-10-12 13:22:27,913	INFO: 媒体管理软件设置为：jellyfin
2022-10-12 13:22:27,914	INFO: 下载软件设置为：qbittorrent
2022-10-12 13:22:27,914	INFO: 下载文件转移模式为：硬链接
2022-10-12 13:22:27,914	INFO: 索引器设置为：builtin
2022-10-12 13:22:27,914	INFO: 保种时间未配置，自动删种功能已关闭
2022-10-12 13:22:27,914	INFO: 下载软件监控未开启，下载器监控功能已关闭
2022-10-12 13:22:34,659	INFO: 【RUN】站点自动签到服务启动
2022-10-12 13:22:35,614	INFO: 【RUN】RSS订阅服务启动
2022-10-12 13:22:35,669	INFO: 【RUN】订阅定时搜索服务启动
2022-10-12 13:22:35,672	INFO: 【SYNC】读取到监控目录：/video/Movies，目的目录：/video/Link/Movies，转移方式：硬链接
2022-10-12 13:22:35,672	INFO: 【SYNC】读取到监控目录：/video/TVs，目的目录：/video/Link/TVs，转移方式：硬链接
2022-10-12 13:22:35,672	INFO: 【SYNC】读取到监控目录：/video/Anime，目的目录：/video/Link/Anime，转移方式：硬链接
2022-10-12 13:22:36,004	INFO: 【RUN】/video/Movies 的监控服务启动
2022-10-12 13:22:36,416	INFO: 【RUN】/video/TVs 的监控服务启动
2022-10-12 13:22:36,546	INFO: 【RUN】/video/Anime 的监控服务启动
[Errno 2] No such file or directory: 'Xvfb'
配置文件地址：/config/config.yaml
NASTool 当前版本号：v2.2.1
正在加载配置...
日志输出类型为：file
日志将写入文件：/config/logs
开始启动进程...
Pending jobs:
    Sites.signin (trigger: cron[hour='8', minute='1'], pending)
    Rss.rssdownload (trigger: interval[0:30:00], pending)
    Rss.rsssearch_all (trigger: interval[1 day, 0:00:00], pending)
    Config.init_config (trigger: interval[0:10:00], pending)
    MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
    Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
    Rss.rsssearch (trigger: interval[0:05:00], pending)
    Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2022-10-12 13:23:35 CST)
    Rss.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
    MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
    get_login_wallpaper (trigger: interval[1:00:00], next run at: 2022-10-12 13:22:35 CST)
 * Serving Flask app 'web.main'
 * Debug mode: off
Job "Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2022-10-12 19:23:35 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/nas-tools/app/sites/sites.py", line 339, in refresh_pt_date_now
    self.refresh_all_pt_data(True)
  File "/nas-tools/app/sites/sites.py", line 138, in refresh_all_pt_data
    with ThreadPool(min(len(refresh_sites), self._MAX_CONCURRENCY)) as p:
  File "/usr/lib/python3.10/multiprocessing/dummy/__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 927, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
Job "Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2022-10-13 01:23:35 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/nas-tools/app/sites/sites.py", line 339, in refresh_pt_date_now
    self.refresh_all_pt_data(True)
  File "/nas-tools/app/sites/sites.py", line 138, in refresh_all_pt_data
    with ThreadPool(min(len(refresh_sites), self._MAX_CONCURRENCY)) as p:
  File "/usr/lib/python3.10/multiprocessing/dummy/__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 927, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
Job "Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2022-10-13 07:23:35 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/nas-tools/app/sites/sites.py", line 339, in refresh_pt_date_now
    self.refresh_all_pt_data(True)
  File "/nas-tools/app/sites/sites.py", line 138, in refresh_all_pt_data
    with ThreadPool(min(len(refresh_sites), self._MAX_CONCURRENCY)) as p:
  File "/usr/lib/python3.10/multiprocessing/dummy/__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 927, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
Job "Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2022-10-13 13:23:35 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/nas-tools/app/sites/sites.py", line 339, in refresh_pt_date_now
    self.refresh_all_pt_data(True)
  File "/nas-tools/app/sites/sites.py", line 138, in refresh_all_pt_data
    with ThreadPool(min(len(refresh_sites), self._MAX_CONCURRENCY)) as p:
  File "/usr/lib/python3.10/multiprocessing/dummy/__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 927, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
2022-10-13 08:01:00,052	INFO: 【SITES】开始站点模拟登录：猫
2022-10-13 08:01:03,441	WARNING: 【SITES】猫 模拟登录失败，请检查cookie
2022-10-13 08:01:03,442	INFO: 【MSG】发送wechat消息：title=站点签到, text=【猫】模拟登录失败，请检查cookie！
2022-10-13 11:16:35,707	INFO: 【SYNC】开始转移监控目录文件...
2022-10-13 11:16:35,762	INFO: 【RMT】开始处理：/video/Movies/The.Lobster.2015.1080p.BluRay.x264.DTS-WiKi，转移方式：硬链接
2022-10-13 11:16:37,169	INFO: 【META】The Lobster 识别到 电影：TMDBID=254320, 名称=龙虾, 上映日期=2015-10-15
2022-10-13 11:16:37,187	INFO: 【RMT】正在转移文件：The.Lobster.2015.1080p.BluRay.x264.DTS-WiKi.mkv 到 /video/Link/Movies/欧美电影/龙虾 (2015)/龙虾 (2015) - 1080p.mkv
2022-10-13 11:16:37,701	INFO: 【RMT】文件 The.Lobster.2015.1080p.BluRay.x264.DTS-WiKi.mkv 硬链接完成
2022-10-13 11:16:38,101	INFO: 【META】正在查询TMDB电影：254320 ...
2022-10-13 11:16:40,627	INFO: 【MSG】发送wechat消息：title=龙虾 (2015) 转移完成, text=评分：7.0，类型：电影，类别：欧美电影，质量：BluRay 1080p，大小：14.35G，来自：目录同步
2022-10-13 11:16:41,404	INFO: 【SUBTITLE】通知ChineseSubFinder下载字幕: /video/Link/Movies/欧美电影/龙虾 (2015)/龙虾 (2015) - 1080p.mkv
2022-10-13 11:16:41,405	INFO: 【RMT】/video/Movies/The.Lobster.2015.1080p.BluRay.x264.DTS-WiKi 处理完成，总数：1，失败：0
2022-10-13 11:16:41,410	INFO: 【SYNC】开始转移监控目录文件...
2022-10-13 11:16:41,410	INFO: 【RMT】开始处理：/video/Movies/The.Lobster.2015.1080p.BluRay.x264.DTS-WiKi/Sample，转移方式：硬链接
2022-10-13 11:16:41,412	WARNING: 【RMT】/video/Movies/The.Lobster.2015.1080p.BluRay.x264.DTS-WiKi/Sample/The.Lobster.2015.1080p.BluRay.x264.DTS-WiKi.Sample.mkv 可能是预告片，跳过...
2022-10-13 11:16:41,412	INFO: 【RMT】/video/Movies/The.Lobster.2015.1080p.BluRay.x264.DTS-WiKi/Sample 处理完成，总数：0，失败：0
2022-10-13 11:16:42,038	INFO: 【SUBTITLE】ChineseSubFinder任务添加成功：838373ac34c5e29fad4ad20e948b40502ed78e6537a681b45f5deebec63784f5

```

**Comment by link2fun** [comment]
```
[Errno 2] No such file or directory: 'Xvfb'
```
你是哪个目录没映射对么

**Comment by jxxghp** [comment]
没有拉全量镜像，但是又打开了浏览器仿真开关吧。

**Comment by chris5641** [comment]
> 没有拉全量镜像，但是又打开了浏览器仿真开关吧。

重新拉取了镜像，也么踹打开仿真开关，结果还是会一段时间后无法访问WEB页面

```
2022-10-13 16:12:34,666	INFO: WEB管理页面用户：wc5641
2022-10-13 16:12:34,880	INFO: 已启用https，请使用 https://IP:3000 访问管理页面
2022-10-13 16:12:34,880	INFO: TMDB匹配模式：正常模式
2022-10-13 16:12:34,880	INFO: 媒体管理软件设置为：jellyfin
2022-10-13 16:12:34,881	INFO: 下载软件设置为：qbittorrent
2022-10-13 16:12:34,881	INFO: 下载文件转移模式为：硬链接
2022-10-13 16:12:34,881	INFO: 索引器设置为：builtin
2022-10-13 16:12:34,881	INFO: 保种时间未配置，自动删种功能已关闭
2022-10-13 16:12:34,882	INFO: 下载软件监控未开启，下载器监控功能已关闭
2022-10-13 16:12:35,570	INFO: 【RUN】站点自动签到服务启动
2022-10-13 16:12:35,694	INFO: 【RUN】RSS订阅服务启动
2022-10-13 16:12:35,702	INFO: 【RUN】订阅定时搜索服务启动
2022-10-13 16:12:35,704	INFO: 【Sync】读取到监控目录：/video/Movies，目的目录：/video/Link/Movies，转移方式：硬链接
2022-10-13 16:12:35,705	INFO: 【Sync】读取到监控目录：/video/TVs，目的目录：/video/Link/TVs，转移方式：硬链接
2022-10-13 16:12:35,731	INFO: 【Sync】读取到监控目录：/video/Anime，目的目录：/video/Link/Anime，转移方式：硬链接
2022-10-13 16:12:35,859	INFO: 【RUN】/video/Movies 的监控服务启动
2022-10-13 16:12:36,005	INFO: 【RUN】/video/TVs 的监控服务启动
2022-10-13 16:12:36,062	INFO: 【RUN】/video/Anime 的监控服务启动
配置文件地址：/config/config.yaml
NASTool 当前版本号：v2.2.1
正在加载配置...
日志输出类型为：file
日志将写入文件：/config/logs
开始启动进程...
Pending jobs:
    Sites.signin (trigger: cron[hour='8', minute='1'], pending)
    Rss.rssdownload (trigger: interval[0:30:00], pending)
    Rss.rsssearch_all (trigger: interval[1 day, 0:00:00], pending)
    Config.init_config (trigger: interval[0:10:00], pending)
    MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
    Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
    Rss.rsssearch (trigger: interval[0:05:00], pending)
    Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2022-10-13 16:13:35 CST)
    Rss.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
    MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
    get_login_wallpaper (trigger: interval[1:00:00], next run at: 2022-10-13 16:12:35 CST)
 * Serving Flask app 'web.main'
 * Debug mode: off
Job "Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2022-10-13 22:13:35 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/nas-tools/app/sites/sites.py", line 339, in refresh_pt_date_now
    self.refresh_all_pt_data(True)
  File "/nas-tools/app/sites/sites.py", line 138, in refresh_all_pt_data
    with ThreadPool(min(len(refresh_sites), self._MAX_CONCURRENCY)) as p:
  File "/usr/lib/python3.10/multiprocessing/dummy/__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 927, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
[2022-10-13 16:27:38,391] ERROR in app: Exception on /statistics [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/nas-tools/web/main.py", line 781, in statistics
    SiteData = Sites().get_pt_date()
  File "/nas-tools/app/sites/sites.py", line 345, in get_pt_date
    self.refresh_all_pt_data()
  File "/nas-tools/app/sites/sites.py", line 138, in refresh_all_pt_data
    with ThreadPool(min(len(refresh_sites), self._MAX_CONCURRENCY)) as p:
  File "/usr/lib/python3.10/multiprocessing/dummy/__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 927, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
[2022-10-13 16:27:40,409] ERROR in app: Exception on /statistics [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/nas-tools/web/main.py", line 781, in statistics
    SiteData = Sites().get_pt_date()
  File "/nas-tools/app/sites/sites.py", line 345, in get_pt_date
    self.refresh_all_pt_data()
  File "/nas-tools/app/sites/sites.py", line 138, in refresh_all_pt_data
    with ThreadPool(min(len(refresh_sites), self._MAX_CONCURRENCY)) as p:
  File "/usr/lib/python3.10/multiprocessing/dummy/__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 927, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
Job "Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2022-10-14 04:13:35 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/nas-tools/app/sites/sites.py", line 339, in refresh_pt_date_now
    self.refresh_all_pt_data(True)
  File "/nas-tools/app/sites/sites.py", line 138, in refresh_all_pt_data
    with ThreadPool(min(len(refresh_sites), self._MAX_CONCURRENCY)) as p:
  File "/usr/lib/python3.10/multiprocessing/dummy/__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 927, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
Job "Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2022-10-14 10:13:35 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/nas-tools/app/sites/sites.py", line 339, in refresh_pt_date_now
    self.refresh_all_pt_data(True)
  File "/nas-tools/app/sites/sites.py", line 138, in refresh_all_pt_data
    with ThreadPool(min(len(refresh_sites), self._MAX_CONCURRENCY)) as p:
  File "/usr/lib/python3.10/multiprocessing/dummy/__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 927, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
2022-10-14 08:01:00,244	INFO: 【Sites】开始站点模拟登录：猫
2022-10-14 08:01:04,378	WARNING: 【Sites】猫 模拟登录失败，请检查cookie
2022-10-14 08:01:04,378	INFO: 【Message】发送wechat消息：title=站点签到, text=【猫】模拟登录失败，请检查cookie！
Job "Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2022-10-14 16:13:35 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/nas-tools/app/sites/sites.py", line 339, in refresh_pt_date_now
    self.refresh_all_pt_data(True)
  File "/nas-tools/app/sites/sites.py", line 138, in refresh_all_pt_data
    with ThreadPool(min(len(refresh_sites), self._MAX_CONCURRENCY)) as p:
  File "/usr/lib/python3.10/multiprocessing/dummy/__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 927, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
Job "Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2022-10-14 22:13:35 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/nas-tools/app/sites/sites.py", line 339, in refresh_pt_date_now
    self.refresh_all_pt_data(True)
  File "/nas-tools/app/sites/sites.py", line 138, in refresh_all_pt_data
    with ThreadPool(min(len(refresh_sites), self._MAX_CONCURRENCY)) as p:
  File "/usr/lib/python3.10/multiprocessing/dummy/__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 927, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
Job "Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2022-10-15 04:13:35 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/nas-tools/app/sites/sites.py", line 339, in refresh_pt_date_now
    self.refresh_all_pt_data(True)
  File "/nas-tools/app/sites/sites.py", line 138, in refresh_all_pt_data
    with ThreadPool(min(len(refresh_sites), self._MAX_CONCURRENCY)) as p:
  File "/usr/lib/python3.10/multiprocessing/dummy/__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 927, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
Job "Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2022-10-15 10:13:35 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/nas-tools/app/sites/sites.py", line 339, in refresh_pt_date_now
    self.refresh_all_pt_data(True)
  File "/nas-tools/app/sites/sites.py", line 138, in refresh_all_pt_data
    with ThreadPool(min(len(refresh_sites), self._MAX_CONCURRENCY)) as p:
  File "/usr/lib/python3.10/multiprocessing/dummy/__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 927, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
2022-10-15 08:01:00,157	INFO: 【Sites】开始站点模拟登录：猫
2022-10-15 08:01:03,427	WARNING: 【Sites】猫 模拟登录失败，请检查cookie
2022-10-15 08:01:03,428	INFO: 【Message】发送wechat消息：title=站点签到, text=【猫】模拟登录失败，请检查cookie！
Job "Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2022-10-15 16:13:35 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/nas-tools/app/sites/sites.py", line 339, in refresh_pt_date_now
    self.refresh_all_pt_data(True)
  File "/nas-tools/app/sites/sites.py", line 138, in refresh_all_pt_data
    with ThreadPool(min(len(refresh_sites), self._MAX_CONCURRENCY)) as p:
  File "/usr/lib/python3.10/multiprocessing/dummy/__init__.py", line 124, in Pool
    return ThreadPool(processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 927, in __init__
    Pool.__init__(self, processes, initializer, initargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

```
