### ISSUE TITLE
重启NAS Tools后系统自动pull request #1557 出错导致无法启动，请问环境是否有问题，是否只能重装，有无其他补救措施

### ISSUE THREAD

**Issue by YangZeCN** [jxxghp/nas-tools#1579]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 最新版本？ 无法访问NASTool获取版本信息
>
> 环境: 威联通 Dockers

## 你遇到什么问题了？

> 重启NAS Tools后系统自动pull request #1557 出错导致无法启动，是否有补救办法，不行的话是不是只能重装Dockers？

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 暂时没有找到相关问题

## 你期望的结果

> 是否有补救办法，不行的话是不是只能重装Dockers？

## 给出程序界面截图、后台运行日志或配置文件
> 威联通Container Station 控制台日志如下：
-------------------------------------------
Removing supervisord.log
HEAD is now at 50bec658 Merge pull request #1557 from jxxghp/dev
Already up to date.
更新成功...
检测到requirements.txt有变化，重新安装依赖...
Requirement already satisfied: pip in /usr/lib/python3.10/site-packages (22.2.2)
Requirement already satisfied: setuptools in /usr/lib/python3.10/site-packages (65.4.1)
Requirement already satisfied: wheel in /usr/lib/python3.10/site-packages (0.37.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Requirement already satisfied: APScheduler==3.9.1 in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (3.9.1)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/asttokens/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f07752024a0>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/asttokens/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/asttokens/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/asttokens/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/asttokens/
Collecting asttokens==2.0.8
  Using cached asttokens-2.0.8-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: async-generator==1.10 in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (1.10)
Requirement already satisfied: attrs==22.1.0 in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (22.1.0)
Collecting backcall==0.2.0
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting backports.shutil-get-terminal-size==1.0.0
  Using cached backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl (6.5 kB)
Requirement already satisfied: beautifulsoup4==4.11.1 in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (4.11.1)
Requirement already satisfied: bencode.py==4.0.0 in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (4.0.0)
Requirement already satisfied: better-exceptions==0.3.3 in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (0.3.3)
Collecting bs4==0.0.1
  Using cached bs4-0.0.1.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cacheout==0.14.1 in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (0.14.1)
Requirement already satisfied: certifi==2022.6.15 in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (2022.6.15)
Requirement already satisfied: cffi==1.15.1 in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (1.15.1)
Requirement already satisfied: charset-normalizer==2.1.1 in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 14)) (2.1.1)
Requirement already satisfied: click==8.1.3 in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 15)) (8.1.3)
Requirement already satisfied: colorama==0.4.4 in /usr/lib/python3.10/site-packages (from -r requirements.txt (line 16)) (0.4.4)
Collecting colored==1.3.93
  Using cached colored-1.3.93.tar.gz (24 kB)
  Preparing metadata (setup.py) ... done
Collecting cryptography==38.0.1
  Downloading cryptography-38.0.1-cp36-abi3-musllinux_1_1_x86_64.whl (4.2 MB)
     ━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.1/4.2 MB 95.2 kB/s eta 0:00:44
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 435, in _error_catcher
    yield
  File "/usr/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 516, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
  File "/usr/lib/python3.10/http/client.py", line 465, in read
    s = self.fp.read(amt)
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/usr/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
  File "/usr/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/usr/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 438, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 483, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/usr/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 165, in unpack_url
    file = get_http_url(
  File "/usr/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 106, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/usr/lib/python3.10/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "/usr/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/usr/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 573, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 509, in read
    with self._error_catcher():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 440, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
无法安装依赖，请更新镜像...
以PUID=0，PGID=0的身份启动程序...
注意：日志将停止打印，请通过文件或WEB页面查看日志
2022-10-13 22:42:26,361 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-10-13 22:42:26,370 INFO RPC interface 'supervisor' initialized
2022-10-13 22:42:26,370 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2022-10-13 22:42:26,370 INFO supervisord started with pid 1
2022-10-13 22:42:27,373 INFO spawned: 'nas-tools' with pid 34
2022-10-13 22:42:27,434 INFO exited: nas-tools (exit status 1; not expected)
2022-10-13 22:42:28,437 INFO spawned: 'nas-tools' with pid 35
2022-10-13 22:42:28,500 INFO exited: nas-tools (exit status 1; not expected)
2022-10-13 22:42:30,504 INFO spawned: 'nas-tools' with pid 36
2022-10-13 22:42:30,565 INFO exited: nas-tools (exit status 1; not expected)
2022-10-13 22:42:33,570 INFO spawned: 'nas-tools' with pid 37
2022-10-13 22:42:33,632 INFO exited: nas-tools (exit status 1; not expected)
2022-10-13 22:42:34,634 INFO gave up: nas-tools entered FATAL state, too many start retries too quickly
^C2022-10-13 22:44:02,723 WARN received SIGINT indicating exit request

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
> logs/supervisor下日志：

Traceback (most recent call last):
  File "/nas-tools/run.py", line 6, in <module>
    from pyvirtualdisplay import Display
ModuleNotFoundError: No module named 'pyvirtualdisplay'
Traceback (most recent call last):
  File "/nas-tools/run.py", line 6, in <module>
    from pyvirtualdisplay import Display
ModuleNotFoundError: No module named 'pyvirtualdisplay'
Traceback (most recent call last):
  File "/nas-tools/run.py", line 6, in <module>
    from pyvirtualdisplay import Display
ModuleNotFoundError: No module named 'pyvirtualdisplay'
Traceback (most recent call last):
  File "/nas-tools/run.py", line 6, in <module>
    from pyvirtualdisplay import Display
ModuleNotFoundError: No module named 'pyvirtualdisplay'

**Comment by jxxghp** [comment]
你这是网络有问题装不上依赖，手动拉最新镜像
