### ISSUE TITLE
订阅了几个动漫以后打不开电视剧订阅菜单了

### ISSUE THREAD

**Issue by vleboy** [jxxghp/nas-tools#1700]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本:docker  v2.2.2 
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> 订阅 《死神 千年血战篇》以后，过了一会儿，无法打开菜单【订阅管理】- 【电视剧订阅】

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 能打开菜单【订阅管理】- 【电视剧订阅】

## 给出程序界面截图、后台运行日志或配置文件
![image](https://user-images.githubusercontent.com/8954958/196492826-36977b47-50cb-4a56-b9e8-34fcf72e61c4.png)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
2022-10-19 00:44:01,798	INFO: WEB管理页面用户：admin
2022-10-19 00:44:01,798	INFO: 未启用https，请使用 http://IP:3000 访问管理页面
2022-10-19 00:44:01,798	INFO: TMDB匹配模式：正常模式
2022-10-19 00:44:01,799	INFO: 媒体管理软件设置为：emby
2022-10-19 00:44:01,799	WARNING: 微信配置不完整，将无法接收到通知消息！
2022-10-19 00:44:01,799	WARNING: 微信Token、EncodingAESKey未配置，微信控制功能将无法使用
2022-10-19 00:44:01,799	INFO: 下载软件设置为：qbittorrent
2022-10-19 00:44:01,799	INFO: 下载文件转移模式为：硬链接
2022-10-19 00:44:01,800	INFO: 索引器设置为：jackett
2022-10-19 00:44:01,800	INFO: 微信等移动端渠道搜索已开启自动择优下载
2022-10-19 00:44:01,800	INFO: 保种时间未配置，自动删种功能已关闭
2022-10-19 00:44:01,800	INFO: 下载软件监控未开启，下载器监控功能已关闭
2022-10-19 00:44:01,984	INFO: 站点自动签到服务启动
2022-10-19 00:44:02,011	INFO: RSS订阅服务启动
2022-10-19 00:44:02,015	INFO: 订阅定时搜索服务启动
2022-10-19 00:44:02,021	INFO: 豆瓣同步服务启动
2022-10-19 00:44:02,021	INFO: 媒体库同步服务启动
2022-10-19 00:44:02,023	INFO: 【Sync】读取到监控目录：/Video/Download/Movies，目的目录：/Video/Media/Movies，转移方式：硬链接
2022-10-19 00:44:02,023	INFO: 【Sync】读取到监控目录：/Video/Download/Series，目的目录：/Video/Media/Series，转移方式：硬链接
2022-10-19 00:44:02,023	INFO: 【Sync】读取到监控目录：/Video/Download/Anime，目的目录：/Video/Media/Anime，转移方式：硬链接
2022-10-19 00:44:02,042	INFO: /Video/Download/Movies 的监控服务启动
2022-10-19 00:44:02,043	INFO: /Video/Download/Series 的监控服务启动
2022-10-19 00:44:02,065	INFO: /Video/Download/Anime 的监控服务启动
配置文件地址：/config/config.yaml
NASTool 当前版本号：v2.2.2
正在加载配置...
日志输出类型为：file
日志将写入文件：/config/logs
开始启动进程...
Pending jobs:
    Sites.signin (trigger: cron[hour='8', minute='1'], pending)
    Rss.rssdownload (trigger: interval[0:30:00], pending)
    Rss.rsssearch_all (trigger: interval[1 day, 0:00:00], pending)
    DoubanSync.sync (trigger: interval[2 days, 12:00:00], pending)
    MediaServer.sync_mediaserver (trigger: interval[12:00:00], pending)
    Config.init_config (trigger: interval[0:10:00], pending)
    MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
    Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
    Rss.rsssearch (trigger: interval[0:05:00], pending)
    Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2022-10-19 00:45:02 CST)
    Rss.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
    MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
    get_login_wallpaper (trigger: interval[1:00:00], next run at: 2022-10-19 00:44:02 CST)
 * Serving Flask app 'web.main'
 * Debug mode: off
[2022-10-19 00:46:09,834] ERROR in app: Exception on /tv_rss [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/nas-tools/web/main.py", line 593, in tv_rss
    return render_template("rss/tv_rss.html",
  File "/usr/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/usr/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/nas-tools/web/templates/rss/tv_rss.html", line 78, in top-level template code
    正在订阅 {% if Item[6] > 0 %}({{ Item[6] - Item[7] }}/{{ Item[6] }}){% endif %}
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by jxxghp** [comment]
dev已修复
