### ISSUE TITLE
数据库报错反馈贴

### ISSUE THREAD

**Issue by Mruser0** [jxxghp/nas-tools#1817]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.3.0 5e5b7e5c
>
> 环境:   Synology  docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

删除所有配置文件，重拉镜像，重建容器，配置好站点和其它设置后，启动了4个站点的刷流任务，运行正常，自动删种正常，但是数据统计不更新今日上传量和下载量，总上传量和其它数据正常更新，同时自动rss刷流任务偶尔会报处理rss发生错误：this session is in prepared state错误，同时查看log文件，发现报的有异常

ERROR in app: Exception on /search [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/nas-tools/web/main.py", line 222, in search
    pris = User().get_user(username).get("pris")
  File "/nas-tools/web/backend/user.py", line 52, in get
    for user in self.dbhelper.get_users():
  File "/nas-tools/app/helper/db_helper.py", line 888, in get_users
    return self._db.query(CONFIGUSERS).all()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2772, in all
    return self._iter().all()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2907, in _iter
    result = self.session.execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1713, in execute
    conn = self._connection_for_bind(bind)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1552, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 721, in _connection_for_bind
    self._assert_active()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 594, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
已浏览查看

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
其它功能正常，希望恢复正常数据统计

## 给出程序界面截图、后台运行日志或配置文件
[nas-tools-stdout---supervisor-qhpxao4u.log](https://github.com/jxxghp/nas-tools/files/9889616/nas-tools-stdout---supervisor-qhpxao4u.log)

> 如UI BUG请提供截图及配置文件截图
![M{T3 1F(L_ O0R9P V_1R 4](https://user-images.githubusercontent.com/107661622/198672966-ba883ad1-3db7-406a-a395-021f7295e0bc.png)
![8ZXADKO~QFS%9FBU2 A7SWC](https://user-images.githubusercontent.com/107661622/198673299-28aeeb30-e561-432d-b6d7-d52a4a521f42.png)
这个刷流数据重启后就会一直停留在这个数据不更新，已下载种子和已删除种子数一直在后台刷新，但这里不会变。
> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志

**Comment by Mruser0** [comment]
![Screenshot_20221028-185553](https://user-images.githubusercontent.com/107661622/198675276-6cf66838-1608-4749-8689-de2a1c7c5445.jpg)
这个是刷流RSS种子时偶尔会报的错误

**Comment by lightolly** [comment]
今日上传量需要昨天的数据，等一天后就正常显示了

**Comment by jxxghp** [comment]
2.5.0-beta版本做了较大调整，目前未再发现数据库问题
