### ISSUE TITLE
更新2.3.0后出现：文件转移失败，错误码 1。2.2.3的时候正常

### ISSUE THREAD

**Issue by AisukaYuki** [jxxghp/nas-tools#1833]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.3.1
> 环境: windows python git源码运行

## 你遇到什么问题了？

>  文件转移失败，错误码 1

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

>文件权限没问题。同样的配置，2.2.3没问题，更新2.3.0后出现问题

## 你期望的结果

> 

## 给出程序界面截图、后台运行日志或配置文件

> 其它问题提供后台日志，如为Docker请提供 logs/supervisor 目录下的日志
[run.txt](https://github.com/jxxghp/nas-tools/files/9895071/run.txt)
[config.txt](https://github.com/jxxghp/nas-tools/files/9895004/config.txt)
![image](https://user-images.githubusercontent.com/17586327/198861096-1b952fc9-ec19-4429-b750-e2df80d9b911.png)

**Comment by zero617** [comment]
v2.3.1 windows下连移动也不行了 错误码1

**Comment by Crazy-FuQing** [comment]
同问 nastool_win_v2.3.1 win10   源和目的是同一个文件夹中的两个文件夹 也会报错误1
![image](https://user-images.githubusercontent.com/46838021/198861583-3557b5cc-6b37-442e-be46-c6321eff7dcc.png)

**Comment by AisukaYuki** [comment]
> v2.3.1 windows下连移动也不行了 错误码1

> 同问 nastool_win_v2.3.1 win10 源和目的是同一个文件夹中的两个文件夹 也会报错误1 ![image](https://user-images.githubusercontent.com/46838021/198861583-3557b5cc-6b37-442e-be46-c6321eff7dcc.png)

#1825
dev分支应该已经修复了，等待merge commits

**Comment by AisukaYuki** [comment]
`2022-10-30 13:24:42,883	INFO: 【Rmt】开始处理：/下载/动漫/[NC-Raws] 间谍过家家 - 17 (B-Global 3840x2160 HEVC AAC MKV) [752A9D08].mkv，转移方式：硬链接
2022-10-30 13:24:42,899	INFO: 【Rmt】正在转移文件：[NC-Raws] 间谍过家家 - 17 (B-Global 3840x2160 HEVC AAC MKV) [752A9D08].mkv 到 /bangumi/动漫\间谍过家家 (2022)\Season 1\间谍过家家 - S01E17 - 第17集.mkv
2022-10-30 13:24:42,929	ERROR: 【Rmt】文件转移时发生错误：[WinError 2] 系统找不到指定的文件。 - Traceback (most recent call last):
  File "D:\Program Files\nastools\app\filetransfer.py", line 747, in transfer_media
    ret = self.__transfer_file(file_item=file_item,
  File "D:\Program Files\nastools\app\filetransfer.py", line 432, in __transfer_file
    retcode = self.__transfer_command(file_item=file_item,
  File "D:\Program Files\nastools\app\filetransfer.py", line 169, in __transfer_command
    retcode = subprocess.run(['powershell', 'cmd /C mklink /H',
  File "C:\Program Files\python\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\python\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\python\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

2022-10-30 13:24:42,931	INFO: 【Rmt】/下载/动漫/[NC-Raws] 间谍过家家 - 17 (B-Global 3840x2160 HEVC AAC MKV) [752A9D08].mkv 处理完成，总数：1，失败：0
`

**Comment by Crazy-FuQing** [comment]
非常感谢大佬 问题在2.3.2版本中已经解决了 
![image](https://user-images.githubusercontent.com/46838021/198872502-7d06cda7-8e5e-4212-8853-26851fb5c0d5.png)
