### ISSUE TITLE
当例如LTSB系统自带powershell不存在时 ，报错的解决方法（实验性

### ISSUE THREAD

**Issue by AisukaYuki** [jxxghp/nas-tools#1841]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.3.2
>
> 环境: docker or windows or Synology
>windows python pull最新源码运行
**补充一下，系统因为是win10老版本ltsb的，没有powershell**

## 你遇到什么问题了？

> 由于系统没有powershellsubprocess.py 报错

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 

## 你期望的结果

>解决方法，用户自己安装外部安装PowerShell7，可重命名pwsh.exe为powershell，配置系统环境参数。但是由于外部调用时，pwsh会报错，需要在调用时增加-command参数

 例如：
retcode = subprocess.run(['powershell', '**-command** ', 'cmd /C mklink /H',
                                              f'"{target_file}"',
                                              f'"{file_item}"'], startupinfo=st).returncode

最好是在代码中做一下判断，如果系统powershell不存在，就调用外部C:\Program Files\powershell\7\pwsh.exe
当然也可以不做判断，只加 -command 参数即可，用户自己配置powershell 外部环境。 -command  对于正常用户来说没有影响

## 给出程序界面截图、后台运行日志或配置文件

pwsh调用失败时报错
> 022-10-30 14:34:49,738 INFO: 【Rmt】开始处理：/下载/动漫/[NC-Raws] 间谍过家家 - 17 (B-Global 3840x2160 HEVC AAC MKV) [752A9D08].mkv，转移方式：硬链接
2022-10-30 14:34:49,751 INFO: 【Rmt】正在转移文件：[NC-Raws] 间谍过家家 - 17 (B-Global 3840x2160 HEVC AAC MKV) [752A9D08].mkv 到 /bangumi/动漫\间谍过家家 (2022)\Season 1\间谍过家家 - S01E17 - 第17集.mkv
2022-10-30 14:34:49,785 ERROR: 【Rmt】文件转移时发生错误：[WinError 2] 系统找不到指定的文件。 - Traceback (most recent call last):
  File "D:\Program Files\nastools\app\filetransfer.py", line 747, in transfer_media
    ret = self.__transfer_file(file_item=file_item,
  File "D:\Program Files\nastools\app\filetransfer.py", line 432, in __transfer_file
    retcode = self.__transfer_command(file_item=file_item,
  File "D:\Program Files\nastools\app\filetransfer.py", line 169, in __transfer_command
    retcode = subprocess.run(['powershell', 'cmd /C mklink /H',
  File "C:\Program Files\python\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\python\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\python\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
2022-10-30 14:34:49,787 INFO: 【Rmt】/下载/动漫/[NC-Raws] 间谍过家家 - 17 (B-Global 3840x2160 HEVC AAC MKV) [752A9D08].mkv 处理完成，总数：1，失败：0

**Comment by Shurelol** [comment]
建议下载powershell安装

**Comment by AisukaYuki** [comment]
> 建议下载powershell安装

系统精简，不能安装最新的pwsh，我外部调用了C:\Program Files\powershell\7\pwsh.exe，但是外部调用需要增加 -command 作为 cmd的连接。我更新了一下上面的描述。增加-command 参数对于系统本来就用powershell 也没有影响。如果不好合并代码的话。我就自己fork一份了

**Comment by Shurelol** [comment]
建议下载powershell5.1安装

**Comment by Shurelol** [comment]
可以了么

**Comment by AisukaYuki** [comment]
> 可以了么

The argument 'cmd' is not recognized as the name of a script file. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

不行。-command 不加会报错。。。
![image](https://user-images.githubusercontent.com/17586327/198875197-d8fbf575-3be6-4882-b8fc-c70b040e59f1.png)
只能加上-command 才能正常用。

不用麻烦了，我自己fork一份，我自己用就好了
