### ISSUE TITLE
windows版本的出现搜索报错

### ISSUE THREAD

**Issue by Antonchenxr** [jxxghp/nas-tools#1868]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 2.3.2
>
> 环境: windows
>

## 你遇到什么问题了？

> 搜索资源的时候，bt资源全部呈现，但是pt资源无内容，站点统计里可以看到数据，站点资源和搜索均无效

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 在群晖版本里没有发现这个问题

## 你期望的结果

> 希望知道是否是bug还是其他原因引起

## 给出程序界面截图、后台运行日志或配置文件

> 21:39:31 INFO - 下载文件转移服务启动
21:39:31 INFO - RSS订阅服务启动
21:39:31 INFO - 订阅定时搜索服务启动
21:39:31 INFO - 媒体库同步服务启动
21:39:58 INFO - 【Douban】正在通过网页抓取豆瓣详情：https://movie.douban.com/subject/3025375/
21:40:00 INFO - 【Meta】正在查询TMDB电影：284052 ...
21:40:01 INFO - 【Web】从TMDB中匹配到电影：奇异博士 (2016)
21:40:01 INFO - 【Web】开始检索 奇异博士 ...
21:40:01 INFO - 【Indexer】开始并行检索 Doctor Strange，线程数：3 ...
21:40:01 INFO - 【Indexer】开始检索Indexer：M-TEAM ...
21:40:01 INFO - 【Indexer】开始检索Indexer：Audiences ...
21:40:01 INFO - 【Indexer】开始检索Indexer：HD Dolby ...
21:40:02 WARN - 【Spider】错误：XPathExpr.join() got an unexpected keyword argument 'closing_combiner' - Traceback (most recent call last): File "app\indexer\client\spider.py", line 477, in parse File "pyquery\pyquery.py", line 261, in __call__ File "pyquery\pyquery.py", line 247, in _copy File "pyquery\pyquery.py", line 232, in __init__ File "pyquery\pyquery.py", line 243, in _css_to_xpath File "cssselect\xpath.py", line 222, in css_to_xpath File "cssselect\xpath.py", line 223, in <genexpr> File "cssselect\xpath.py", line 256, in selector_to_xpath File "cssselect\xpath.py", line 294, in xpath File "cssselect\xpath.py", line 303, in xpath_combinedselector File "cssselect\xpath.py", line 294, in xpath File "cssselect\xpath.py", line 325, in xpath_relation File "cssselect\xpath.py", line 439, in xpath_relation_descendant_combinator TypeError: XPathExpr.join() got an unexpected keyword argument 'closing_combiner'
21:40:02 WARN - 【Indexer】HD Dolby 未检索到数据
> 
[logs.txt](https://github.com/jxxghp/nas-tools/files/9914896/logs.txt)

**Comment by XINGYUZHMM** [comment]
同样情况，内置索引器出现。

**Comment by jxxghp** [comment]
是这个站吗？ hddolby.com   我有，无法重现

```
2022-11-03 16:50:35,424	INFO: 【Douban】正在通过网页抓取豆瓣详情：https://movie.douban.com/subject/3025375/
2022-11-03 16:50:38,755	INFO: 【Meta】正在查询TMDB电影：284052 ...
2022-11-03 16:50:39,874	INFO: 【Web】从TMDB中匹配到电影：奇异博士 (2016)
2022-11-03 16:50:39,875	INFO: 【Web】开始检索 奇异博士 ...
2022-11-03 16:50:40,034	INFO: 【Indexer】开始并行检索 Doctor Strange，线程数：1 ...
2022-11-03 16:50:40,035	INFO: 【Indexer】开始检索Indexer：杜比 ...
2022-11-03 16:50:43,060	WARNING: 【Indexer】杜比 返回数据：31
2022-11-03 16:50:43,949	INFO: 【Meta】正在查询TMDB电影：453395 ...
2022-11-03 16:50:44,691	INFO: 【Meta】Doctor Strange in the Multiverse of Madness 识别到 电影：TMDBID=453395, 名称=奇异博士2：疯狂多元宇宙, 上映日期=2022-05-04
2022-11-03 16:50:44,692	INFO: 【Indexer】Doctor Strange in the Multiverse of Madness 2022 V2 UHD BluRay 2160p TureHD Atmos 7.1 HDR x265 10bit-Hares 识别为 电影 奇异博士2：疯狂多元宇宙 (2022) 不匹配
2022-11-03 16:50:44,700	INFO: 【Indexer】Doctor Strange 2016 UHD BluRay REMUX 2160p HEVC Atmos TrueHD7.1 2Audio-CHD 大小：47.83G 促销：50% 不符合默认过滤规则
2022-11-03 16:50:45,303	INFO: 【Meta】正在查询TMDB电影：284052 ...
2022-11-03 16:50:45,312	INFO: 【Meta】Doctor Strange 识别到 电影：TMDBID=284052, 名称=奇异博士, 上映日期=2016-10-25
2022-11-03 16:50:47,007	INFO: 【Indexer】Doctor Strange 2016 BluRay 1080p x265 10bit 2Audio MNHD-FRDS 国配中字奇异博士/斯特兰奇博士/史特兰奇博士/奇怪博士 特效国配中英 国英双语 10bit HEVC 识别为 奇异博士 (2016)  匹配成功
2022-11-03 16:50:47,013	INFO: 【Indexer】Doctor Strange in the Multiverse of Madness 2022 BluRay 1080p x265 10bit DDP7.1 MNHD-FRDS 识别为 电影 奇异博士2：疯狂多元宇宙 (2022) 不匹配
2022-11-03 16:50:47,017	INFO: 【Indexer】Doctor Strange in the Multiverse of Madness 2022 2160p 60FPS SVFI 2 3 Blu-ray x265 10bit HDR TrueHD 7.1-toothless 大小：31.81G 促销：50% 不符合默认过滤规则
2022-11-03 16:50:47,023	INFO: 【Indexer】Doctor Strange in the Multiverse of Madness 2022 2160p UHD BluRay x265 10bit HDR mUHD-FRDS 识别为 电影 奇异博士2：疯狂多元宇宙 (2022) 不匹配
2022-11-03 16:50:47,027	INFO: 【Indexer】Doctor Strange in the Multiverse of Madness 2022 2160p EUR UHD Blu-ray HEVC 10bit HDR Atmos TrueHD 7.1-Iceyumao@Dream 大小：17.12G 促销：普通 不符合默认过滤规则
2022-11-03 16:50:47,031	INFO: 【Indexer】Doctor Strange in the Multiverse of Madness 2022 2160p EUR UHD Blu-ray Remux HEVC Atmos TrueHD 7.1-Iceyumao@Dream 大小：51.46G 促销：普通 不符合默认过滤规则
2022-11-03 16:50:47,036	INFO: 【Indexer】Doctor Strange in the Multiverse of Madness 2022 1080p BluRay x264 DTS-WiKi 识别为 电影 奇异博士2：疯狂多元宇宙 (2022) 不匹配
2022-11-03 16:50:47,042	INFO: 【Indexer】Doctor Strange in the Multiverse of Madness 2022 1080p BluRay x265 10bit DTS-WiKi 识别为 电影 奇异博士2：疯狂多元宇宙 (2022) 不匹配
2022-11-03 16:50:47,046	INFO: 【Indexer】Doctor Strange in the Multiverse of Madness 2022 2160p UHD Blu-ray HDR HEVC TrueHD Atmos 7.1-HDO 大小：56.46G 促销：50% 不符合默认过滤规则
2022-11-03 16:50:47,050	INFO: 【Indexer】Doctor Strange in the Multiverse of Madness 2022 2160p EUR UHD Blu-ray HEVC TrueHD 7.1-SharpHD 大小：56.46G 促销：50% 不符合默认过滤规则
2022-11-03 16:50:47,057	INFO: 【Indexer】Doctor Strange in the Multiverse of Madness 2022 IMAX Enhanced Disney+ WEB-DL 4k HEVC HDR DDP-AREY 识别为 电影 奇异博士2：疯狂多元宇宙 (2022) 不匹配
2022-11-03 16:50:47,064	INFO: 【Indexer】Doctor Strange in the Multiverse of Madness 2022 IMAX 2160p DSNP WEB-DL DDP Atmos 5.1 Hybrid DV HDR H.265-HONE 识别为 电影 奇异博士2：疯狂多元宇宙 (2022) 不匹配
2022-11-03 16:50:47,071	INFO: 【Indexer】Doctor Strange in the Multiverse of Madness 2022 2160p MA WEB-DL DDP 5.1 Atmos HDR DV H.265-CMRG 识别为 电影 奇异博士2：疯狂多元宇宙 (2022) 不匹配
2022-11-03 16:50:47,075	INFO: 【Indexer】Doctor Strange in the Multiverse of Madness 2022 2160p WEB-DL HEVC Atmos DDP5.1-HDH 大小：62.4G 促销：50% 不符合默认过滤规则
2022-11-03 16:50:47,700	INFO: 【Meta】正在查询TMDB电影：453395 ...
2022-11-03 16:50:47,706	INFO: 【Meta】Doctor Strange In The Multiverse Of Madness 识别到 电影：TMDBID=453395, 名称=奇异博士2：疯狂多元宇宙, 上映日期=2022-05-04
2022-11-03 16:50:47,707	INFO: 【Indexer】Doctor Strange In The Multiverse Of Madness 2022 2160p WEB-DL DDPA5.1 HDR HEVC-CMRG 识别为 电影 奇异博士2：疯狂多元宇宙 (2022) 不匹配
2022-11-03 16:50:47,713	INFO: 【Indexer】Doctor Strange in the Multiverse of Madness 2022 2160p WEB-DL DDP5.1 Atmos H.265-EVO 识别为 电影 奇异博士2：疯狂多元宇宙 (2022) 不匹配
2022-11-03 16:50:47,718	INFO: 【Indexer】Doctor Strange in the Multiverse of Madness 2022 1080p WEB-DL DDP5 1 Atmos H 264-EVO 识别为 电影 奇异博士2：疯狂多元宇宙 (2022) 不匹配
2022-11-03 16:50:47,725	INFO: 【Indexer】Doctor Strange in the Multiverse of Madness 2022 2160p WEB-DL DDP5.1 Atmos HDR H.265-EVO 识别为 电影 奇异博士2：疯狂多元宇宙 (2022) 不匹配
2022-11-03 16:50:47,730	INFO: 【Indexer】Doctor Strange 2016 UHD BluRay 2160p 10bit HDR 2Audio TrueHD(Atmos) 7.1 x265-beAst 国配中字HDR10奇异博士/怪奇医生/奇怪博士 国英双语TrueHD7.1/英语导评/英简繁SUP字幕/章节 识别为 奇异博士 (2016)  匹配成功
2022-11-03 16:50:47,735	INFO: 【Indexer】Doctor Strange 2016 3D BluRay 1080p HSBS x264 DTS-HD MA7 1 2Audios-CMCT 国配中字奇异博士 2016 3D版 国英双语 字幕：中英3D、简体3D、中英2D、简体2D 识别为 奇异博士 (2016)  匹配成功
2022-11-03 16:50:47,739	INFO: 【Indexer】Doctor Strange 2016 2160p UHD BluRay REMUX MULTi HDR HEVC TrueHD Atmos 7.1-newt 大小：49.33G 促销：50% 不符合默认过滤规则
2022-11-03 16:50:47,742	INFO: 【Indexer】What If 2021 S01E04 What If Doctor Strange Lost His Heart And Not His Hands 2160p WEB-DL DDP5.1 Atmos HDR H 265-FLUX 是 电视剧，不匹配类型：电影
2022-11-03 16:50:47,745	INFO: 【Indexer】Doctor Stranger 2014 S01 Complete 1080p Netflix Webdl AVC AAC-DBTV 是 电视剧，不匹配类型：电影
2022-11-03 16:50:47,749	INFO: 【Indexer】Doctor Strange 2016 BluRay 2160p x265 10bit HDR 3Audio mUHD-FRDS 奇异博士/史奇医生/史特兰奇博士/奇怪博士 mUHD作品 4k HDR10版本 识别为 奇异博士 (2016)  匹配成功
2022-11-03 16:50:47,754	INFO: 【Indexer】Doctor Strange 2016 BluRay 2160p HEVC Atmo TrueHD_7 1-XDY@Dream 官方奇异博士 / Dr. Strange / 史奇医生 / 史特兰奇博士 / 奇异医生 / 奇怪博士 / 怪奇医生 / 斯特兰奇博士 识别为 奇异博士 (2016)  匹配成功
2022-11-03 16:50:47,757	INFO: 【Indexer】Doctor Stranger S01 Complete 1080p NF WEB-DL DDP2 0 x264-Ao 是 电视剧，不匹配类型：电影
2022-11-03 16:50:47,762	INFO: 【Indexer】Doctor Strange 2016 UHD BluRay 2160p 2Audio TrueHD Atmos 7.1 x265 10bit HDR-BeiTai 奇异博士 国英双语TrueHD7.1/英简繁SUP字幕/章节 识别为 奇异博士 (2016)  匹配成功
2022-11-03 16:50:47,767	INFO: 【Indexer】Doctor Strange 2016 BluRay 1080p x265.10bit MNHD-FRDS 【奇异博士/斯特兰奇博士/史特兰奇博士/奇怪博士/怪奇医生/奇异医生/史奇医生】10bit HEVC版本 识别为 奇异博士 (2016)  匹配成功
2022-11-03 16:50:47,769	INFO: 【Indexer】Doctor Stranger 2014 Complete WEB-DL 2160P H265 AAC-LeagueTV 是 电视剧，不匹配类型：电影
2022-11-03 16:50:47,770	INFO: 【Indexer】杜比 共检索到 31 条数据，过滤 8，不匹配 12，有效资源 7，耗时 7 秒
2022-11-03 16:50:47,771	INFO: 【Indexer】所有站点检索完成，有效资源数：7，总耗时 7 秒
2022-11-03 16:50:47,780	INFO: 【Web】共检索到 7 个有效资源

```

**Comment by timmy0209** [comment]
windows系统相同的问题 报错内容也是一样的

**Comment by XINGYUZHMM** [comment]
> 
![image](https://user-images.githubusercontent.com/112518475/199709949-2098b03e-a244-46f3-9624-2735278bf468.png)
![image](https://user-images.githubusercontent.com/112518475/199709985-62c74e53-3521-4c7f-99c9-dd15cc4b591d.png)


所有站都是这样 2.3.2版本 普通搜索高级搜索都一样

**Comment by FireGodson** [comment]
我也是，只有几个站能搜出大多数搜不出来，退回之前版本好使

**Comment by jxxghp** [comment]
windows版本已重新打包
