### ISSUE TITLE
2.4.1 豆瓣网页查询豆瓣详情，前端持续显示搜索中，supervisord日志中python报错

### ISSUE THREAD

**Issue by fengted** [jxxghp/nas-tools#1964]
## 你使用的 NASTool 是什么版本，什么环境？

NASTool 版本: 2.4.1

环境: docker

## 你遇到什么问题了？

全新升级到2.4.1后，豆瓣热门可以显示条目，点击具体条目搜索，持续显示 正在搜索 xxxxxxx  请稍候......

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

没发现类似提报

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

ogs/supervisor 目录下的日志：
======
2022-11-09 11:16:29,114	INFO: WEB管理页面用户：admin
2022-11-09 11:16:29,114	INFO: 未启用https，请使用 http://IP:3000 访问管理页面
2022-11-09 11:16:29,114	INFO: TMDB匹配模式：正常模式
2022-11-09 11:16:29,114	INFO: 媒体管理软件设置为：plex
2022-11-09 11:16:29,114	WARNING: emby配置不完整
2022-11-09 11:16:29,114	INFO: 下载软件设置为：qbittorrent
2022-11-09 11:16:29,114	INFO: 下载文件转移模式为：硬链接
2022-11-09 11:16:29,115	INFO: 索引器设置为：builtin
2022-11-09 11:16:29,115	INFO: 微信等移动端渠道搜索已开启自动择优下载
2022-11-09 11:16:29,115	INFO: 保种时间未配置，自动删种功能已关闭
2022-11-09 11:16:29,275	INFO: 站点自动签到服务启动
2022-11-09 11:16:29,301	INFO: 下载文件转移服务启动
2022-11-09 11:16:29,309	INFO: RSS订阅服务启动
2022-11-09 11:16:29,316	INFO: 订阅定时搜索服务启动
2022-11-09 11:16:29,317	INFO: 媒体库同步服务启动
2022-11-09 11:16:29,320	INFO: 【Sync】读取到监控目录：/videos/Download/animation，目的目录：/videos/Animation/，转移方式：硬链接
2022-11-09 11:16:29,320	INFO: 【Sync】/videos/Download/animation 不进行监控和同步：手动关闭
2022-11-09 11:16:29,320	INFO: 【Sync】读取到监控目录：/videos/Download/movies/，目的目录：/videos/Movie/，转移方式：硬链接
2022-11-09 11:16:29,320	INFO: 【Sync】/videos/Download/movies/ 不进行监控和同步：手动关闭
2022-11-09 11:16:29,321	INFO: 【Sync】读取到监控目录：/videos/Download/tv，目的目录：/videos/TV/，转移方式：硬链接
2022-11-09 11:16:29,321	INFO: 【Sync】/videos/Download/tv 不进行监控和同步：手动关闭
正在加载配置...
配置文件地址：/config/config.yaml
NASTool 当前版本号：v2.4.1
数据库初始化...
数据库初始化已完成
数据库更新...
数据库更新已完成
日志输出类型为：file
日志将写入文件：/config/logs
开始启动进程...
Pending jobs:
    Sites.signin (trigger: cron[hour='8', minute='1'], pending)
    Downloader.transfer (trigger: interval[0:05:00], pending)
    Rss.rssdownload (trigger: interval[0:30:00], pending)
    Rss.rsssearch_all (trigger: interval[1 day, 0:00:00], pending)
    MediaServer.sync_mediaserver (trigger: interval[12:00:00], pending)
    MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
    Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
    Rss.rsssearch (trigger: interval[0:05:00], pending)
    Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2022-11-09 11:17:29 CST)
    Rss.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
    MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
    get_login_wallpaper (trigger: interval[1:00:00], next run at: 2022-11-09 11:16:29 CST)
 * Serving Flask app 'web.main' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2022-11-09 11:19:00,129	INFO: 【Douban】正在通过API查询豆瓣详情：35801819
2022-11-09 11:19:07,119	INFO: 【Douban】正在通过网页查询豆瓣详情：35801819
[2022-11-09 11:19:07,120] ERROR in app: Exception on /do [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/nas-tools/web/main.py", line 1048, in do
    return WebAction().action(cmd, data)
  File "/nas-tools/web/action.py", line 185, in action
    return func(data)
  File "/nas-tools/web/action.py", line 406, in __search
    ret, ret_msg = search_medias_for_web(content=search_word,
  File "/nas-tools/web/backend/search_torrents.py", line 49, in search_medias_for_web
    doubaninfo = DouBan().get_media_detail_from_web(doubanid)
  File "/nas-tools/app/media/douban.py", line 206, in get_media_detail_from_web
    web_info = self.doubanweb.detail(cookie=self.cookie, doubanid=doubanid)
TypeError: unhashable type: 'dict'
======

**Comment by jxxghp** [comment]
多谢，就是要这个报错。我本地重现不了，一直不知道是哪的问题

**Comment by jxxghp** [comment]
修复了，更新下代码看看

**Comment by fengted** [comment]
> 修复了，更新下代码看看

重新拉了代码，问题修复！
