### ISSUE TITLE
无法打开字幕设置界面 

### ISSUE THREAD

**Issue by ltsj** [jxxghp/nas-tools#2062]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: v2.4.2 7579060b
>
> 环境: docker
>

## 你遇到什么问题了？

> 无法打开字幕设置界面 即 http://127.0.0.1:3000//subtitle 查询日志报错如下

## 给出程序界面截图、后台运行日志或配置文件
 `[2022-11-18 21:00:06,800] ERROR in app: Exception on /subtitle [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/nas-tools/web/main.py", line 994, in subtitle
    return render_template("setting/subtitle.html", Config=Config().get_config())
  File "/usr/lib/python3.10/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/usr/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/nas-tools/web/templates/setting/subtitle.html", line 62, in top-level template code
    <input class="form-check-input" type="checkbox" id="subtitle.opensubtitles.enable" {% if
  File "/usr/lib/python3.10/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'ruamel.yaml.comments.CommentedMap object' has no attribute 'subtitle'
`

**Comment by jxxghp** [comment]
你自己改了配置文件吧？配置文件不全或者没有成功读取
