### ISSUE TITLE
订阅失败问题

### ISSUE THREAD

**Issue by leo8912** [jxxghp/nas-tools#218]
1，web端订阅，加年代不加年代都失败

2022-06-01 22:55:35,310	INFO: 【META】正在识别电影：独行月球, 年份= ...
2022-06-01 22:55:37,225	INFO: >电影ID：801803, 电影名称：独行月球, 上映日期：None
2022-06-01 22:55:58,232	INFO: 【META】正在识别电影：独行月球, 年份=2022 ...
2022-06-01 22:55:59,805	WARNING: 【META】独行月球 未找到媒体信息!
2022-06-01 22:56:34,483	ERROR: 微信消息处理发生错误：'NoneType' object has no attribute 'text' - Traceback (most recent call last):
  File "/nas-tools/web/main.py", line 1831, in wechat
    event_key = xml_tree.find("EventKey").text
AttributeError: 'NoneType' object has no attribute 'text'

2，尝试微信订阅。。这个错误，消息里也出现过几次
2022-06-01 22:56:39,942	INFO: 消息内容：订阅 独行月球
2022-06-01 22:56:40,067	INFO: 【WEB】电影 独行月球 已添加订阅
2022-06-01 22:57:13,106	ERROR: 微信消息处理发生错误：'NoneType' object has no attribute 'text' - Traceback (most recent call last):
  File "/nas-tools/web/main.py", line 1831, in wechat
    event_key = xml_tree.find("EventKey").text
AttributeError: 'NoneType' object has no attribute 'text'

2022-06-01 22:58:13,856	ERROR: 微信消息处理发生错误：'NoneType' object has no attribute 'text' - Traceback (most recent call last):
  File "/nas-tools/web/main.py", line 1831, in wechat
    event_key = xml_tree.find("EventKey").text
AttributeError: 'NoneType' object has no attribute 'text'

2022-06-01 22:59:51,476	ERROR: 微信消息处理发生错误：'NoneType' object has no attribute 'text' - Traceback (most recent call last):
  File "/nas-tools/web/main.py", line 1831, in wechat
    event_key = xml_tree.find("EventKey").text
AttributeError: 'NoneType' object has no attribute 'text'

2022-06-01 22:59:57,957	INFO: 消息内容：订阅 独行月球
2022-06-01 22:59:57,972	INFO: 【WEB】电影 独行月球 已添加订阅

**Comment by jxxghp** [comment]
1、微信消息处理发生错误 这个可能是企业微信的心跳，跟订阅无关，实际上没有影响，更新下最新的代码，看是否还会输出这个错误日志。
2、无法订阅是因为这个词条没有年份，最新的代码已经支持。

**Comment by leo8912** [comment]
> 

V1.3.3可以了，谢谢
