### ISSUE TITLE
从2.6.0更新到2.6.1后无法启动 

### ISSUE THREAD

**Issue by eadorothy86** [jxxghp/nas-tools#2285]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>6358e1e 
> 环境: docker or windows or Synology
>docker

## 你遇到什么问题了？

> 更新后一直重复启动，无法启动后台

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
查过以往的问题没跟我相符的，已经删除过镜像，重新拉过。

## 你期望的结果

> 描述以下你期望的结果
能够正常运行
## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
Pending jobs:
    Sites.signin (trigger: cron[hour='8', minute='0'], pending)
    Downloader.transfer (trigger: interval[0:05:00], pending)
    Rss.rssdownload (trigger: interval[0:30:00], pending)
    DoubanSync.sync (trigger: interval[6:00:00], pending)
    MediaServer.sync_mediaserver (trigger: interval[1:00:00], pending)
    MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
    Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
    Subscribe.subscribe_search (trigger: interval[0:05:00], pending)
    Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2022-12-03 09:16:23 CST)
    Subscribe.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
    MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
    get_login_wallpaper (trigger: interval[1:00:00], next run at: 2022-12-03 09:15:23 CST)
2022-12-03 09:15:23,904	INFO: /video/TV 的监控服务启动
2022-12-03 09:15:24,295	INFO: /video/Movie 的监控服务启动
2022-12-03 09:15:24,297	INFO: /video/Anime 的监控服务启动
Traceback (most recent call last):
  File "/nas-tools/run.py", line 186, in <module>
    start_service()
  File "/nas-tools/run.py", line 140, in start_service
    BrushTask()
  File "/nas-tools/app/utils/commons.py", line 21, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/brushtask.py", line 37, in __init__
    self.init_config()
  File "/nas-tools/app/brushtask.py", line 69, in init_config
    self._brush_tasks = self.get_brushtask_info()
  File "/nas-tools/app/brushtask.py", line 111, in get_brushtask_info
    "site": site_info.get("name"),
AttributeError: 'NoneType' object has no attribute 'get'
2022-12-03T09:15:26: PM2 log: App [NAStool:0] exited with code [1] via signal [SIGINT]
2022-12-03T09:15:26: PM2 log: App [NAStool:0] starting in -fork mode-
2022-12-03T09:15:26: PM2 log: App [NAStool:0] online
正在加载配置：/config/config.yaml
NAStool 当前版本号：v2.6.1
开始初始化数据库...
数据库初始化完成
开始更新数据库...
数据库更新完成
日志输出类型为：file
日志将写入文件：/config/logs
WEB管理页面用户：eadorothy
未启用https，请使用 http://IP:3000 访问管理页面
TMDB匹配模式：正常模式
媒体管理软件设置为：emby
下载软件设置为：qbittorrent
默认文件转移模式为：硬链接
索引器设置为：builtin
开始启动服务...
2022-12-03 09:15:30,052	INFO: 【Telegram】Webhook 地址为：https://nas.3338333.xyz/telegram
2022-12-03 09:15:30,205	INFO: 站点自动签到服务启动
2022-12-03 09:15:34,712	INFO: 下载文件转移服务启动
2022-12-03 09:15:34,720	INFO: RSS订阅服务启动
2022-12-03 09:15:34,724	INFO: 豆瓣同步服务启动
2022-12-03 09:15:34,725	INFO: 媒体库同步服务启动
2022-12-03 09:15:34,729	INFO: 【Sync】读取到监控目录：/video/TV，目的目录：/video/link/TV，转移方式：硬链接
2022-12-03 09:15:34,730	INFO: 【Sync】读取到监控目录：/video/Movie，目的目录：/video/link/Movie，转移方式：硬链接
2022-12-03 09:15:34,730	INFO: 【Sync】读取到监控目录：/video/Anime，目的目录：/video/link/Anime，转移方式：硬链接
Pending jobs:
    Sites.signin (trigger: cron[hour='8', minute='0'], pending)
    Downloader.transfer (trigger: interval[0:05:00], pending)
    Rss.rssdownload (trigger: interval[0:30:00], pending)
    DoubanSync.sync (trigger: interval[6:00:00], pending)
    MediaServer.sync_mediaserver (trigger: interval[1:00:00], pending)
    MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
    Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
    Subscribe.subscribe_search (trigger: interval[0:05:00], pending)
    Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2022-12-03 09:16:34 CST)
    Subscribe.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
    MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
    get_login_wallpaper (trigger: interval[1:00:00], next run at: 2022-12-03 09:15:34 CST)
2022-12-03 09:15:34,863	INFO: /video/TV 的监控服务启动
2022-12-03 09:15:35,194	INFO: /video/Movie 的监控服务启动
2022-12-03 09:15:35,196	INFO: /video/Anime 的监控服务启动
Traceback (most recent call last):
  File "/nas-tools/run.py", line 186, in <module>
    start_service()
  File "/nas-tools/run.py", line 140, in start_service
    BrushTask()
  File "/nas-tools/app/utils/commons.py", line 21, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/brushtask.py", line 37, in __init__
    self.init_config()
  File "/nas-tools/app/brushtask.py", line 69, in init_config
    self._brush_tasks = self.get_brushtask_info()
  File "/nas-tools/app/brushtask.py", line 111, in get_brushtask_info
    "site": site_info.get("name"),
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by wwek** [comment]
相同的问题

**Comment by RejeyFeng** [comment]
我是，删除重建解决
