### ISSUE TITLE
slack配置后nas-tools再也起不来了，陷入循环

### ISSUE THREAD

**Issue by chinaoldcat** [jxxghp/nas-tools#2393]
slack_bolt.error.BoltError: `token` is invalid (auth.test result: {'ok': False, 'error': 'invalid_auth'})
2022-12-08T14:14:51: PM2 log: App [NAStool:0] exited with code [1] via signal [SIGINT]
2022-12-08T14:14:51: PM2 log: App [NAStool:0] starting in -fork mode-
2022-12-08T14:14:51: PM2 log: App [NAStool:0] online
2022-12-08T14:14:52: PM2 log: Stopping app:NAStool id:0
Traceback (most recent call last):
  File "/nas-tools/run.py", line 54, in <module>
    from web.main import App
  File "/nas-tools/web/main.py", line 20, in <module>
    from app.brushtask import BrushTask
  File "/nas-tools/app/brushtask.py", line 10, in <module>
    from app.downloader import Qbittorrent, Transmission
  File "/nas-tools/app/downloader/__init__.py", line 3, in <module>
    from .client.qbittorrent import Qbittorrent
  File "/nas-tools/app/downloader/client/qbittorrent.py", line 10, in <module>
    import qbittorrentapi
  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/__init__.py", line 2, in <module>
    from qbittorrentapi.app import AppAPIMixIn
  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/app.py", line 4, in <module>
    from qbittorrentapi.auth import AuthAPIMixIn
  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/auth.py", line 4, in <module>
    from qbittorrentapi.decorators import login_required
  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/decorators.py", line 6, in <module>
    from qbittorrentapi.exceptions import APIError
  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/exceptions.py", line 105, in <module>
    class MissingRequiredParameters400Error(HTTP400Error):
KeyboardInterrupt

**Comment by chinaoldcat** [comment]
两个TOKEN在重启之前通过了后台的检测。

**Comment by chinaoldcat** [comment]
降级安装 2.6下载的是2.63，重新下载2.63故障依旧，删除config文件也不行了。

**Comment by chinaoldcat** [comment]
删除容器，文件，重新建docker容器也无法启动了。 2.61也试过了

**Comment by jxxghp** [comment]
slack_bolt.error.BoltError: token is invalid (auth.test result: {'ok': False, 'error': 'invalid_auth'})

**Comment by chinaoldcat** [comment]
token 在 WEB UI 中测试是通过的。
