### ISSUE TITLE
设置了Slack后nas-tools打不开了

### ISSUE THREAD

**Issue by kaomaiqi** [jxxghp/nas-tools#2404]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v2.6.2
> 环境: docker or windows or Synology
>群晖7套件版

## 你遇到什么问题了？

> 描述一下你遇到的问题
设置了Slack后nas-tools打不开了，怎么恢复？？

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by chinaoldcat** [comment]
好吧，我也是同样的问题，只是提出问题就被删除了

**Comment by chinaoldcat** [comment]
我尝试退回 2.5 也无法启动了。然后后续又尝试安装了 2.6 2.61 重新安装2.63也是一样无法解决问题。

**Comment by Shurelol** [comment]
没有日志，无法分析

**Comment by xmj1** [comment]
好吧，我也是同样的问题，只是提出问题就被删除了

**Comment by danielsocials** [comment]
log:

```
TMDB匹配模式：正常模式
媒体管理软件设置为：emby
下载软件设置为：qbittorrent
默认文件转移模式为：硬链接
索引器设置为：builtin
微信等移动端渠道搜索已开启自动择优下载
下载软件监控未开启，下载器监控功能已关闭
开始启动服务...
2022-12-29 10:13:03,979	ERROR: 启动定时服务失败：`token` is invalid (auth.test result: {'ok': False, 'error': 'invalid_auth'}) - Traceback (most recent call last):
  File "/nas-tools/third_party/slack_bolt/slack_bolt/app/app.py", line 359, in _init_middleware_list
    auth_test_result = self._client.auth_test(token=self._token)
  File "/usr/lib/python3.10/site-packages/slack_sdk/web/client.py", line 1532, in auth_test
    return self.api_call("auth.test", params=kwargs)
  File "/usr/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 156, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/usr/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 187, in _sync_send
    return self._urllib_api_call(
  File "/usr/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 317, in _urllib_api_call
    ).validate()
  File "/usr/lib/python3.10/site-packages/slack_sdk/web/slack_response.py", line 199, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed. (url: https://www.slack.com/api/auth.test)
The server responded with: {'ok': False, 'error': 'invalid_auth'}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/nas-tools/app/scheduler.py", line 236, in run_scheduler
    Scheduler().run_service()
  File "/nas-tools/app/scheduler.py", line 81, in run_service
    self.SCHEDULER.add_job(Sites().signin,
  File "/nas-tools/app/utils/commons.py", line 21, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/sites/sites.py", line 50, in __init__
    self.init_config()
  File "/nas-tools/app/sites/sites.py", line 54, in init_config
    self.message = Message()
  File "/nas-tools/app/utils/commons.py", line 21, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/message/message.py", line 51, in __init__
    self.init_config()
  File "/nas-tools/app/message/message.py", line 90, in init_config
    "client": self.__build_client(ctype, config, interactive),
  File "/nas-tools/app/message/message.py", line 114, in __build_client
    return Slack(conf, interactive)
  File "/nas-tools/app/message/channel/slack.py", line 28, in __init__
    self.init_config()
  File "/nas-tools/app/message/channel/slack.py", line 33, in init_config
    slack_app = App(token=self._client_config.get("bot_token"))
  File "/nas-tools/third_party/slack_bolt/slack_bolt/app/app.py", line 324, in __init__
    self._init_middleware_list(
  File "/nas-tools/third_party/slack_bolt/slack_bolt/app/app.py", line 367, in _init_middleware_list
    raise BoltError(error_auth_test_failure(err.response))
slack_bolt.error.BoltError: `token` is invalid (auth.test result: {'ok': False, 'error': 'invalid_auth'})
2022-12-29 10:13:04,582	ERROR: 启动目录同步服务失败：`token` is invalid (auth.test result: {'ok': False, 'error': 'invalid_auth'})
Traceback (most recent call last):
  File "/nas-tools/third_party/slack_bolt/slack_bolt/app/app.py", line 359, in _init_middleware_list
    auth_test_result = self._client.auth_test(token=self._token)
  File "/usr/lib/python3.10/site-packages/slack_sdk/web/client.py", line 1532, in auth_test
    return self.api_call("auth.test", params=kwargs)
  File "/usr/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 156, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/usr/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 187, in _sync_send
    return self._urllib_api_call(
  File "/usr/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 317, in _urllib_api_call
    ).validate()
  File "/usr/lib/python3.10/site-packages/slack_sdk/web/slack_response.py", line 199, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed. (url: https://www.slack.com/api/auth.test)
The server responded with: {'ok': False, 'error': 'invalid_auth'}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/nas-tools/run.py", line 180, in <module>
    start_service()
  File "/nas-tools/run.py", line 132, in start_service
    BrushTask()
  File "/nas-tools/app/utils/commons.py", line 21, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/brushtask.py", line 36, in __init__
    self.init_config()
  File "/nas-tools/app/brushtask.py", line 40, in init_config
    self.message = Message()
  File "/nas-tools/app/utils/commons.py", line 21, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/message/message.py", line 51, in __init__
    self.init_config()
  File "/nas-tools/app/message/message.py", line 90, in init_config
    "client": self.__build_client(ctype, config, interactive),
  File "/nas-tools/app/message/message.py", line 114, in __build_client
    return Slack(conf, interactive)
  File "/nas-tools/app/message/channel/slack.py", line 28, in __init__
    self.init_config()
  File "/nas-tools/app/message/channel/slack.py", line 33, in init_config
    slack_app = App(token=self._client_config.get("bot_token"))
  File "/nas-tools/third_party/slack_bolt/slack_bolt/app/app.py", line 324, in __init__
    self._init_middleware_list(
  File "/nas-tools/third_party/slack_bolt/slack_bolt/app/app.py", line 367, in _init_middleware_list
    raise BoltError(error_auth_test_failure(err.response))
slack_bolt.error.BoltError: `token` is invalid (auth.test result: {'ok': False, 'error': 'invalid_auth'})
2022-12-29T10:13:09: PM2 log: App [NAStool:0] exited with code [1] via signal [SIGINT]
2022-12-29T10:13:09: PM2 log: App [NAStool:0] starting in -fork mode-
2022-12-29T10:13:09: PM2 log: App [NAStool:0] online
```
