### ISSUE TITLE
2.6.3 配置 slack 后陷入死循环，无法启动

### ISSUE THREAD

**Issue by chinaoldcat** [jxxghp/nas-tools#2409]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>2.6.3
> 环境: docker or windows or Synology
>docker
## 你遇到什么问题了？
>配置slack后再WEB UI检测通过，但是重启后就无法再次启动nastools了，后台一直重新启动
## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
>除了在这里提出问题的人之外没看到其他人提出或找到解决办法
## 你期望的结果
>恢复正常使用，如果slack是不必要的，也不会再尝试了。
## 给出程序界面截图、后台运行日志或配置文件
**>DOCKER日志如下**
2022-12-08 16:01:38,667	ERROR: 启动目录同步服务失败：`token` is invalid (auth.test result: {'ok': False, 'error': 'invalid_auth'})
2022-12-08 16:01:43,163	ERROR: 启动定时服务失败：`token` is invalid (auth.test result: {'ok': False, 'error': 'invalid_auth'}) - Traceback (most recent call last):
  File "/nas-tools/third_party/slack_bolt/slack_bolt/app/app.py", line 359, in _init_middleware_list
    auth_test_result = self._client.auth_test(token=self._token)
  File "/usr/lib/python3.10/site-packages/slack_sdk/web/client.py", line 1532, in auth_test
    return self.api_call("auth.test", params=kwargs)
  File "/usr/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 156, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/usr/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 187, in _sync_send
    return self._urllib_api_call(
  File "/usr/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 317, in _urllib_api_call
    ).validate()
  File "/usr/lib/python3.10/site-packages/slack_sdk/web/slack_response.py", line 199, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed. (url: https://www.slack.com/api/auth.test)
The server responded with: {'ok': False, 'error': 'invalid_auth'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nas-tools/app/scheduler.py", line 236, in run_scheduler
    Scheduler().run_service()
  File "/nas-tools/app/scheduler.py", line 81, in run_service
    self.SCHEDULER.add_job(Sites().signin,
  File "/nas-tools/app/utils/commons.py", line 21, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/sites/sites.py", line 50, in __init__
    self.init_config()
  File "/nas-tools/app/sites/sites.py", line 54, in init_config
    self.message = Message()
  File "/nas-tools/app/utils/commons.py", line 21, in _singleton
    INSTANCES[cls] = cls(*args, **kwargs)
  File "/nas-tools/app/message/message.py", line 51, in __init__
    self.init_config()
  File "/nas-tools/app/message/message.py", line 90, in init_config
    "client": self.__build_client(ctype, config, interactive),
  File "/nas-tools/app/message/message.py", line 114, in __build_client
    return Slack(conf, interactive)
  File "/nas-tools/app/message/channel/slack.py", line 27, in __init__
    self.init_config()
  File "/nas-tools/app/message/channel/slack.py", line 32, in init_config
    slack_app = App(token=self._client_config.get("bot_token"))
  File "/nas-tools/third_party/slack_bolt/slack_bolt/app/app.py", line 324, in __init__
    self._init_middleware_list(
  File "/nas-tools/third_party/slack_bolt/slack_bolt/app/app.py", line 367, in _init_middleware_list
    raise BoltError(error_auth_test_failure(err.response))
slack_bolt.error.BoltError: `token` is invalid (auth.test result: {'ok': False, 'error': 'invalid_auth'})

2022-12-08 16:01:44,057	ERROR: 启动目录同步服务失败：`token` is invalid (auth.test result: {'ok': False, 'error': 'invalid_auth'})
至此陷入无限循环

**Comment by chinaoldcat** [comment]
大佬们抓住一条就是 **token**，但是token的确是没有问题的，在WEB UI 中点击测试，显示测试通过。

**Comment by chinaoldcat** [comment]
换句话说，即使slack的token错误，为什么会影响正常的程序启动。如果某个模块错误会导致整个程序崩溃那么不是很可笑的一件事情吗？而且这个所谓的token错误导致的问题，在更换或者回滚老版本也无法再让整个程序重新运转起来。我是安装在NAS的DOCK环境中的，难不成还得把整个NAS重新做一下系统。。。

**Comment by Shurelol** [comment]
换个空的config文件夹挂载，建新容器

**Comment by chinaoldcat** [comment]
试过了。换空coinfg文件夹重新下载并建立新容器。

**Comment by chinaoldcat** [comment]
好吧，那我再试一下，再新建个目录，什么都没有的。
