### ISSUE TITLE
媒体整理的历史记录打不开

### ISSUE THREAD

**Issue by shanyan-wcx** [jxxghp/nas-tools#2485]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.0
>
> 环境: docker 
>

## 你遇到什么问题了？

> 媒体整理的历史记录打不开

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 能打开

## 给出程序界面截图、后台运行日志或配置文件

> https://user-images.githubusercontent.com/58252651/206966656-7991a57d-61ec-483d-9451-3fed8041a983.mp4

**Comment by jxxghp** [comment]
一般是数据问题导致，但是我们没法重现就分析不出来问题。你看docker后台有没有报错日志。

**Comment by shanyan-wcx** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: TRANSFER_HISTORY.TMDBID
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/nas-tools/web/main.py", line 748, in history
    Result = WebAction().get_transfer_history({"keyword": keyword, "page": current_page, "pagenum": pagenum})
  File "/nas-tools/web/action.py", line 3446, in get_transfer_history
    totalCount, historys = self.dbhelper.get_transfer_history(SearchStr, CurrentPage, PageNum)
  File "/nas-tools/app/helper/db_helper.py", line 261, in get_transfer_history
    return self._db.query(TRANSFERHISTORY).count(), self._db.query(TRANSFERHISTORY).order_by(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 3167, in count
    return self._from_self(col).enable_eagerloads(False).scalar()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2892, in scalar
    ret = self.one()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2869, in one
    return self._iter().one()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2907, in _iter
    result = self.session.execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: TRANSFER_HISTORY.TMDBID
[SQL: SELECT count(*) AS count_1 
FROM (SELECT "TRANSFER_HISTORY"."ID" AS "TRANSFER_HISTORY_ID", "TRANSFER_HISTORY"."MODE" AS "TRANSFER_HISTORY_MODE", "TRANSFER_HISTORY"."TYPE" AS "TRANSFER_HISTORY_TYPE", "TRANSFER_HISTORY"."CATEGORY" AS "TRANSFER_HISTORY_CATEGORY", "TRANSFER_HISTORY"."TMDBID" AS "TRANSFER_HISTORY_TMDBID", "TRANSFER_HISTORY"."TITLE" AS "TRANSFER_HISTORY_TITLE", "TRANSFER_HISTORY"."YEAR" AS "TRANSFER_HISTORY_YEAR", "TRANSFER_HISTORY"."SEASON_EPISODE" AS "TRANSFER_HISTORY_SEASON_EPISODE", "TRANSFER_HISTORY"."SOURCE" AS "TRANSFER_HISTORY_SOURCE", "TRANSFER_HISTORY"."SOURCE_PATH" AS "TRANSFER_HISTORY_SOURCE_PATH", "TRANSFER_HISTORY"."SOURCE_FILENAME" AS "TRANSFER_HISTORY_SOURCE_FILENAME", "TRANSFER_HISTORY"."DEST" AS "TRANSFER_HISTORY_DEST", "TRANSFER_HISTORY"."DEST_PATH" AS "TRANSFER_HISTORY_DEST_PATH", "TRANSFER_HISTORY"."DEST_FILENAME" AS "TRANSFER_HISTORY_DEST_FILENAME", "TRANSFER_HISTORY"."DATE" AS "TRANSFER_HISTORY_DATE" 
FROM "TRANSFER_HISTORY") AS anon_1]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by Shurelol** [comment]
会改数据库的话，把config下user.db里alembic_version表里version_num字段清零，然后重启
![image](https://user-images.githubusercontent.com/16237201/207041480-f98d70c6-a44e-4fd4-8886-fe47b1b324af.png)

**Comment by shanyan-wcx** [comment]
> 会改数据库的话，把config下user.db里alembic_version表version_num字段清零，然后重启 ![image](https://user-images.githubusercontent.com/16237201/207041480-f98d70c6-a44e-4fd4-8886-fe47b1b324af.png)

清零后重启了，还是不行。
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/nas-tools/web/main.py", line 748, in history
    Result = WebAction().get_transfer_history({"keyword": keyword, "page": current_page, "pagenum": pagenum})
  File "/nas-tools/web/action.py", line 3446, in get_transfer_history
    totalCount, historys = self.dbhelper.get_transfer_history(SearchStr, CurrentPage, PageNum)
  File "/nas-tools/app/helper/db_helper.py", line 261, in get_transfer_history
    return self._db.query(TRANSFERHISTORY).count(), self._db.query(TRANSFERHISTORY).order_by(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 3167, in count
    return self._from_self(col).enable_eagerloads(False).scalar()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2892, in scalar
    ret = self.one()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2869, in one
    return self._iter().one()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2907, in _iter
    result = self.session.execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: TRANSFER_HISTORY.TMDBID
[SQL: SELECT count(*) AS count_1 
FROM (SELECT "TRANSFER_HISTORY"."ID" AS "TRANSFER_HISTORY_ID", "TRANSFER_HISTORY"."MODE" AS "TRANSFER_HISTORY_MODE", "TRANSFER_HISTORY"."TYPE" AS "TRANSFER_HISTORY_TYPE", "TRANSFER_HISTORY"."CATEGORY" AS "TRANSFER_HISTORY_CATEGORY", "TRANSFER_HISTORY"."TMDBID" AS "TRANSFER_HISTORY_TMDBID", "TRANSFER_HISTORY"."TITLE" AS "TRANSFER_HISTORY_TITLE", "TRANSFER_HISTORY"."YEAR" AS "TRANSFER_HISTORY_YEAR", "TRANSFER_HISTORY"."SEASON_EPISODE" AS "TRANSFER_HISTORY_SEASON_EPISODE", "TRANSFER_HISTORY"."SOURCE" AS "TRANSFER_HISTORY_SOURCE", "TRANSFER_HISTORY"."SOURCE_PATH" AS "TRANSFER_HISTORY_SOURCE_PATH", "TRANSFER_HISTORY"."SOURCE_FILENAME" AS "TRANSFER_HISTORY_SOURCE_FILENAME", "TRANSFER_HISTORY"."DEST" AS "TRANSFER_HISTORY_DEST", "TRANSFER_HISTORY"."DEST_PATH" AS "TRANSFER_HISTORY_DEST_PATH", "TRANSFER_HISTORY"."DEST_FILENAME" AS "TRANSFER_HISTORY_DEST_FILENAME", "TRANSFER_HISTORY"."DATE" AS "TRANSFER_HISTORY_DATE" 
FROM "TRANSFER_HISTORY") AS anon_1]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by TimoYoung** [comment]
请问解决了吗，遇到了同样的问题。

**Comment by jxxghp** [comment]
无法重现，备份数据后重装可解决。
