### ISSUE TITLE
transmission打标失败

### ISSUE THREAD

**Issue by TimoYoung** [jxxghp/nas-tools#2544]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
> 2.7.1
> 环境: docker or windows or Synology
> docker
## 你遇到什么问题了？

> 调用transmission-rpc时，change_torrent报错，打标失败导致文件转移任务一直重复尝试。
Transmission: 3.00 (bb6b5a062e), RPC: 16

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> transmission正常打上label

## 给出程序界面截图、后台运行日志或配置文件

> 
```
2022-12-16 11:21:12,014 INFO: 【Rmt】/media/complete/tv/风吹半夏.Wild.Bloom.S01.2022.1080p.WEB-DL.AAC.H264-HDSWEB 处理完成，总数：36，失败：36
Exception: 'NoneType' object is not iterable
Callstack:
File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
self._bootstrap_inner()
File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
self.run()
File "/usr/lib/python3.10/threading.py", line 953, in run
self._target(*self._args, **self._kwargs)
File "/usr/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
work_item.run()
File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
retval = job.func(*job.args, **job.kwargs)
File "/nas-tools/app/downloader/downloader.py", line 343, in transfer
self.default_client.set_torrents_status(ids=task.get("id"),
File "/nas-tools/app/downloader/client/transmission.py", line 141, in set_torrents_status
ExceptionUtils.exception_traceback(err)
Traceback (most recent call last):
File "/nas-tools/app/downloader/client/transmission.py", line 138, in set_torrents_status
self.trc.change_torrent(labels=tags, ids=ids)
File "/nas-tools/third_party/transmission-rpc/transmission_rpc/client.py", line 678, in change_torrent
arg, val = argument_value_convert("torrent-set", argument, value, self.rpc_version)
File "/nas-tools/third_party/transmission-rpc/transmission_rpc/utils.py", line 123, in argument_value_convert
return argument, TR_TYPE_MAP[info.type](value)
TypeError: 'NoneType' object is not iterable
```
>

**Comment by jxxghp** [comment]
应该是TR版本的问题

**Comment by TimoYoung** [comment]
用的linuxserver的docker镜像最新版本。请问您测试用的TR版本是什么，可以推荐一个能正常用的嘛，感谢！
