### ISSUE TITLE
【Bug】run.py中复制第三方补丁目录未判断是否创建，导致启动失败

### ISSUE THREAD

**Issue by lowking** [jxxghp/nas-tools#2655]
这里有问题，我注释掉复制文件的代码就可以启动
https://github.com/jxxghp/nas-tools/blob/master/run.py#L57

```
Dec 24 22:22:42 Plex nas-tools[93252]: Traceback (most recent call last):
Dec 24 22:22:42 Plex nas-tools[93252]:   File "run.py", line 54, in <module>
Dec 24 22:22:42 Plex nas-tools[93252]:     shutil.copy2(os.path.join(os.path.dirname(__file__),
Dec 24 22:22:42 Plex nas-tools[93252]:   File "/usr/lib/python3.8/shutil.py", line 435, in copy2
Dec 24 22:22:42 Plex nas-tools[93252]:     copyfile(src, dst, follow_symlinks=follow_symlinks)
Dec 24 22:22:42 Plex nas-tools[93252]:   File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
Dec 24 22:22:42 Plex nas-tools[93252]:     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
Dec 24 22:22:42 Plex nas-tools[93252]: FileNotFoundError: [Errno 2] No such file or directory: 'third_party/feapder/feapder/network/downloader/_selenium.py'
```

**Comment by jxxghp** [comment]
新版已取消
