### ISSUE TITLE
2.7.4 更新后，容器不停意外中止

### ISSUE THREAD

**Issue by netboy2008** [jxxghp/nas-tools#2738]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.4
>
> 环境: Synology docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

  容器一直意外停止，以下是部分日志

stdout
21:15:05
  × python setup.py egg_info did not run successfully.
stdout
21:15:05
  │ exit code: 1
stdout
21:15:05
  ╰─> [18 lines of output]
stdout
21:15:05
      Traceback (most recent call last):
stdout
21:15:05
        File "<string>", line 2, in <module>
stdout
21:15:05
        File "<pip-setuptools-caller>", line 34, in <module>
stdout
21:15:05
        File "/tmp/pip-install-dormttwn/fast-bencode_1f392dbf135645a78314ea62b8c00801/setup.py", line 44, in <module>
stdout
21:15:05
          setup(
stdout
21:15:05
        File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
stdout
21:15:05
          return distutils.core.setup(**attrs)
stdout
21:15:05
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 172, in setup
stdout
21:15:05
          ok = dist.parse_command_line()
stdout
21:15:05
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 475, in parse_command_line
stdout
21:15:05
          args = self._parse_command_opts(parser, args)
stdout
21:15:05
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1106, in _parse_command_opts
stdout
21:15:05
          nargs = _Distribution._parse_command_opts(self, parser, args)
stdout
21:15:05
        File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 534, in _parse_command_opts
stdout
21:15:05
          cmd_class = self.get_command_class(command)
stdout
21:15:05
        File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 948, in get_command_class
stdout
21:15:05
          if command in self.cmdclass:
stdout
21:15:05
      TypeError: argument of type 'NoneType' is not iterable
stdout
21:15:05
      [end of output]
stdout
21:15:05
  
stdout
21:15:05
  note: This error originates from a subprocess, and is likely not a problem with pip.
stdout
21:15:05
error: metadata-generation-failed
stdout
21:15:05
stdout
21:15:05
× Encountered error while generating package metadata.
stdout
21:15:05
╰─> See above for output.
stdout
21:15:05
stdout
21:15:05
note: This is an issue with the package mentioned above, not pip.
stdout
21:15:05
hint: See above for details.
stdout
21:15:05
无法安装依赖，请更新镜像...
stdout
21:15:05
以PUID=0，PGID=0的身份启动程序...
stdout
21:15:05
/usr/bin/dumb-init
stdout
21:15:06
2022-12-31T21:15:06: PM2 log: Launching in no daemon mode
stdout
21:15:06
2022-12-31T21:15:06: PM2 log: App [NAStool:0] starting in -fork mode-
stdout
21:15:06
2022-12-31T21:15:06: PM2 log: App [NAStool:0] online
stdout
21:15:06
Traceback (most recent call last):
stdout
21:15:06
  File "/nas-tools/run.py", line 8, in <module>

**Comment by jxxghp** [comment]
看更新日志吧
