### ISSUE TITLE
使用Jackett作为索引器搜索时报错

### ISSUE THREAD

**Issue by caomeiguojiang** [jxxghp/nas-tools#2770]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.7.4
>
> 环境: docker
>

## 你遇到什么问题了？

>内建索引器可以正常使用，选择Jackett作为索引器搜索时报错。 Jackett配置正确，单独使用Jackett可以manual search。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 可以正常使用Jackett作为索引器搜索(好像2.7.1还是.2还是正常的……)

## 给出程序界面截图、后台运行日志或配置文件

2023-01-02 22:03:48,017 INFO: 【Douban】正在通过API查询豆瓣详情：1867345
2023-01-02 22:03:48,528 INFO: 【Douban】查询到数据：遗愿清单
2023-01-02 22:03:55,396 INFO: 【Douban】正在通过网页查询豆瓣详情：1867345
2023-01-02 22:03:56,767 INFO: 【Douban】查询到数据：遗愿清单
2023-01-02 22:03:57,844 INFO: 【Meta】正在查询TMDB电影：7350 ...
2023-01-02 22:03:58,898 INFO: 【Web】从TMDB中匹配到电影：遗愿清单 (2007)
2023-01-02 22:03:58,898 INFO: 【Web】开始检索 遗愿清单 ...
[2023-01-02 22:03:58,907] ERROR in app: Exception on /do [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/nas-tools/web/main.py", line 105, in login_check
    return func(*args, **kwargs)
  File "/nas-tools/web/main.py", line 1035, in do
    return WebAction().action(cmd, data)
  File "/nas-tools/web/action.py", line 206, in action
    return func(data)
  File "/nas-tools/web/action.py", line 433, in __search
    ret, ret_msg = search_medias_for_web(content=search_word,
  File "/nas-tools/web/backend/search_torrents.py", line 151, in search_medias_for_web
    media_list = Searcher().search_medias(key_word=first_search_name,
  File "/nas-tools/app/searcher.py", line 55, in search_medias
    return self.indexer.search_by_keyword(key_word=key_word,
  File "/nas-tools/app/indexer/indexer.py", line 103, in search_by_keyword
    indexers = self.get_indexers()
  File "/nas-tools/app/indexer/indexer.py", line 51, in get_indexers
    return self._client.get_indexers(check)
TypeError: Jackett.get_indexers() takes 1 positional argument but 2 were given

**Comment by yuan1821** [comment]
我也遇到了这个问题

**Comment by shimingyun** [comment]
同样的问题

**Comment by KITblue** [comment]
总是报网络错误，测试连接又是成功的。

**Comment by Aldia098** [comment]
一样的问题

**Comment by cslanjian** [comment]
我也遇到了，有人解决么？

**Comment by cslanjian** [comment]
> 

重启后解决了

**Comment by Diluka** [comment]
# 程序版本
 v2.9.0 226b07e
# 容器日志
```
正在加载配置：/config/config.yaml
Exception: Expecting value: line 1 column 1 (char 0)
Callstack:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/nas-tools/app/indexer/client/jackett.py", line 64, in get_indexers
    if not ret or not ret.json():
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
正在加载配置：/config/config.yaml
```
# 容器内手动测试
```
root@815090ed4a52:/nas-tools $ curl http://jackett:9117/api/v2.0/indexers/all/results/torznab/api?apikey=XXX&t=indexers
[1] 8565
root@815090ed4a52:/nas-tools $ <?xml version="1.0" encoding="UTF-8"?>
<error code="100" description="Invalid API Key" />
```
反正是通的，我的qb用得很好

@jxxghp
