### ISSUE TITLE
备份文件无法恢复

### ISSUE THREAD

**Issue by VincentWu920** [jxxghp/nas-tools#2777]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.4
>
> 环境: docker and windows (都试过了，都有问题)
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
恢复文件无法识别，提示D:/Download/config\temp\bk_20230103142923.zip is not a zip file
在当前版本中，使用备份生成的文件，也无法恢复成功，提示同类报错

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
2023-01-03 15:07:56 Callstack:
2023-01-03 15:07:56 Traceback (most recent call last):
2023-01-03 15:07:56   File "/nas-tools/web/action.py", line 2448, in __restory_backup
2023-01-03 15:07:56     shutil.unpack_archive(file_path, config_path, format='zip')
2023-01-03 15:07:56   File "/usr/lib/python3.10/shutil.py", line 1298, in unpack_archive
2023-01-03 15:07:56     func(filename, extract_dir, **dict(format_info[2]))
2023-01-03 15:07:56   File "/usr/lib/python3.10/shutil.py", line 1201, in _unpack_zipfile
2023-01-03 15:07:56     raise ReadError("%s is not a zip file" % filename)
2023-01-03 15:07:56 shutil.ReadError: /config/temp/bk_20230103150741.zip is not a zip file
2023-01-03 15:12:08 Exception: [Errno 2] No such file or directory: '/config/temp/1.zip'
2023-01-03 15:12:08 Callstack:
2023-01-03 15:12:08 Traceback (most recent call last):
2023-01-03 15:12:08   File "/nas-tools/web/main.py", line 1539, in upload
2023-01-03 15:12:08     files.save(str(file_path))
2023-01-03 15:12:08   File "/usr/lib/python3.10/site-packages/werkzeug/datastructures.py", line 2999, in save
2023-01-03 15:12:08     dst = open(dst, "wb")
2023-01-03 15:12:08 FileNotFoundError: [Errno 2] No such file or directory: '/config/temp/1.zip'
2023-01-03 15:12:09 Exception: /config/temp/1.zip is not a zip file
2023-01-03 15:12:09 Callstack:
2023-01-03 15:12:09 Traceback (most recent call last):
2023-01-03 15:12:09   File "/nas-tools/web/action.py", line 2448, in __restory_backup
2023-01-03 15:12:09     shutil.unpack_archive(file_path, config_path, format='zip')
2023-01-03 15:12:09   File "/usr/lib/python3.10/shutil.py", line 1298, in unpack_archive
2023-01-03 15:12:09     func(filename, extract_dir, **dict(format_info[2]))
2023-01-03 15:12:09   File "/usr/lib/python3.10/shutil.py", line 1201, in _unpack_zipfile
2023-01-03 15:12:09     raise ReadError("%s is not a zip file" % filename)
2023-01-03 15:12:09 shutil.ReadError: /config/temp/1.zip is not a zip file

**Comment by jxxghp** [comment]
docker的话映射配置文件目录了吗？

**Comment by VincentWu920** [comment]
docker没有映射配置文件目录，目前用windows  v2.7.2可以正常恢复

**Comment by jxxghp** [comment]
docker不映射配置文件，一更新镜像配置就全没了。。。

**Comment by VincentWu920** [comment]
用软件里面的“[备份&恢复]”功能进行备份的，然后升级到docker 2.7.4后无法恢复了
