### ISSUE TITLE
NASTOOLS 启动不了，提示 启动目录监控失败：[Errno 28] inotify watch limit reached

### ISSUE THREAD

**Issue by bcvb2001** [jxxghp/nas-tools#2858]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.5
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题
启动的时候报错了，一直循环反复启动

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

正在加载配置：/config/config.yaml
NAStool 当前版本号：v2.7.5
开始初始化数据库...
数据库初始化完成
开始更新数据库...
数据库更新完成
日志输出类型为：file
日志将写入文件：/config/logs
WEB管理页面用户：admin
未启用https，请使用 http://IP:3000 访问管理页面
TMDB匹配模式：正常模式
媒体管理软件设置为：emby
动漫媒体库目录不存在：/data1/Anima/
下载软件设置为：qbittorrent
默认文件转移模式为：硬链接
索引器设置为：builtin
微信等移动端渠道搜索已开启自动择优下载
站点自动签到时间未配置，站点签到功能已关闭
RSS订阅周期未配置，RSS订阅功能已关闭
开始启动服务...
2023-01-06 17:21:06,732	INFO: 下载文件转移服务启动
2023-01-06 17:21:06,732	INFO: 媒体库同步服务启动
2023-01-06 17:21:06,736	INFO: 【Sync】读取到监控目录：/data1，转移方式：硬链接
2023-01-06 17:21:06,736	INFO: 【Sync】读取到监控目录：/data1/TVsence，转移方式：硬链接
2023-01-06 17:21:06,736	INFO: 【Sync】读取到监控目录：/data1/Anima，转移方式：硬链接
2023-01-06 17:21:06,737	ERROR: 【Sync】/data1/Anima 目录不存在！
2023-01-06 17:21:06,737	INFO: 【Sync】读取到监控目录：/data1/Movie，转移方式：硬链接
2023-01-06 17:21:06,737	ERROR: 【Sync】/data1/Movie 目录不存在！
2023-01-06 17:21:06,737	INFO: 【Sync】读取到监控目录：/data1/Unknown，转移方式：硬链接
Pending jobs:
    Downloader.transfer (trigger: interval[0:05:00], pending)
    MediaServer.sync_mediaserver (trigger: interval[12:00:00], pending)
    MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
    Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
    Subscribe.subscribe_search (trigger: interval[0:05:00], pending)
    Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2023-01-06 17:22:06 CST)
    Subscribe.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
    MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
    get_login_wallpaper (trigger: interval[1:00:00], next run at: 2023-01-06 17:21:06 CST)
Exception: [Errno 28] inotify watch limit reached
Callstack:
Traceback (most recent call last):
  File "/nas-tools/app/sync.py", line 298, in run_service
    observer.start()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/api.py", line 262, in start
    emitter.start()
  File "/usr/lib/python3.10/site-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 167, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 372, in _add_dir_watch
    self._add_watch(full_path, mask)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 386, in _add_watch
    Inotify._raise_error()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 398, in _raise_error
    raise OSError(errno.ENOSPC, "inotify watch limit reached")
OSError: [Errno 28] inotify watch limit reached
2023-01-06 17:21:07,004	ERROR: /data1 启动目录监控失败：[Errno 28] inotify watch limit reached
2023-01-06 17:21:07,005	ERROR: /data1/TVsence 启动目录监控失败：[Errno 28] inotify watch limit reached
Exception: [Errno 28] inotify watch limit reached
Callstack:
Traceback (most recent call last):
  File "/nas-tools/app/sync.py", line 298, in run_service
    observer.start()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/api.py", line 262, in start
    emitter.start()
  File "/usr/lib/python3.10/site-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 167, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 365, in _add_dir_watch
    self._add_watch(path, mask)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 386, in _add_watch
    Inotify._raise_error()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 398, in _raise_error
    raise OSError(errno.ENOSPC, "inotify watch limit reached")
OSError: [Errno 28] inotify watch limit reached
Exception: [Errno 28] inotify watch limit reached
Callstack:
Traceback (most recent call last):
  File "/nas-tools/app/sync.py", line 298, in run_service
    observer.start()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/api.py", line 262, in start
    emitter.start()
  File "/usr/lib/python3.10/site-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 167, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 365, in _add_dir_watch
    self._add_watch(path, mask)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 386, in _add_watch
    Inotify._raise_error()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 398, in _raise_error
    raise OSError(errno.ENOSPC, "inotify watch limit reached")
OSError: [Errno 28] inotify watch limit reached
2023-01-06 17:21:07,006	ERROR: /data1/Unknown 启动目录监控失败：[Errno 28] inotify watch limit reached
Traceback (most recent call last):
  File "/nas-tools/run.py", line 181, in <module>
    monitor_config()
  File "/nas-tools/run.py", line 171, in monitor_config
    _observer.start()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/api.py", line 262, in start
    emitter.start()
  File "/usr/lib/python3.10/site-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 167, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 365, in _add_dir_watch
    self._add_watch(path, mask)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 386, in _add_watch
    Inotify._raise_error()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 398, in _raise_error
    raise OSError(errno.ENOSPC, "inotify watch limit reached")
OSError: [Errno 28] inotify watch limit reached
2023-01-06T17:21:07: PM2 log: App [NAStool:0] exited with code [1] via signal [SIGINT]
2023-01-06T17:21:07: PM2 log: App [NAStool:0] starting in -fork mode-
2023-01-06T17:21:08: PM2 log: App [NAStool:0] online
正在加载配置：/config/config.yaml
NAStool 当前版本号：v2.7.5
开始初始化数据库...
数据库初始化完成
开始更新数据库...
数据库更新完成
日志输出类型为：file
日志将写入文件：/config/logs
WEB管理页面用户：admin
未启用https，请使用 http://IP:3000 访问管理页面
TMDB匹配模式：正常模式
媒体管理软件设置为：emby
动漫媒体库目录不存在：/data1/Anima/
下载软件设置为：qbittorrent
默认文件转移模式为：硬链接
索引器设置为：builtin
微信等移动端渠道搜索已开启自动择优下载
站点自动签到时间未配置，站点签到功能已关闭
RSS订阅周期未配置，RSS订阅功能已关闭
开始启动服务...
2023-01-06 17:21:10,786	INFO: 下载文件转移服务启动
2023-01-06 17:21:10,787	INFO: 媒体库同步服务启动
2023-01-06 17:21:10,791	INFO: 【Sync】读取到监控目录：/data1，转移方式：硬链接
2023-01-06 17:21:10,791	INFO: 【Sync】读取到监控目录：/data1/TVsence，转移方式：硬链接
2023-01-06 17:21:10,791	INFO: 【Sync】读取到监控目录：/data1/Anima，转移方式：硬链接
2023-01-06 17:21:10,791	ERROR: 【Sync】/data1/Anima 目录不存在！
2023-01-06 17:21:10,792	INFO: 【Sync】读取到监控目录：/data1/Movie，转移方式：硬链接
2023-01-06 17:21:10,792	ERROR: 【Sync】/data1/Movie 目录不存在！
2023-01-06 17:21:10,792	INFO: 【Sync】读取到监控目录：/data1/Unknown，转移方式：硬链接
Pending jobs:
    Downloader.transfer (trigger: interval[0:05:00], pending)
    MediaServer.sync_mediaserver (trigger: interval[12:00:00], pending)
    MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
    Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
    Subscribe.subscribe_search (trigger: interval[0:05:00], pending)
    Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2023-01-06 17:22:10 CST)
    Subscribe.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
    MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
    get_login_wallpaper (trigger: interval[1:00:00], next run at: 2023-01-06 17:21:10 CST)
Exception: [Errno 28] inotify watch limit reached
Callstack:
Traceback (most recent call last):
  File "/nas-tools/app/sync.py", line 298, in run_service
    observer.start()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/api.py", line 262, in start
    emitter.start()
  File "/usr/lib/python3.10/site-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 167, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 372, in _add_dir_watch
    self._add_watch(full_path, mask)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 386, in _add_watch
    Inotify._raise_error()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 398, in _raise_error
    raise OSError(errno.ENOSPC, "inotify watch limit reached")
OSError: [Errno 28] inotify watch limit reached
2023-01-06 17:21:11,058	ERROR: /data1 启动目录监控失败：[Errno 28] inotify watch limit reached
2023-01-06 17:21:11,059	ERROR: /data1/TVsence 启动目录监控失败：[Errno 28] inotify watch limit reached
Exception: [Errno 28] inotify watch limit reached
Callstack:
Traceback (most recent call last):
  File "/nas-tools/app/sync.py", line 298, in run_service
    observer.start()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/api.py", line 262, in start
    emitter.start()
  File "/usr/lib/python3.10/site-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 167, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 365, in _add_dir_watch
    self._add_watch(path, mask)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 386, in _add_watch
    Inotify._raise_error()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 398, in _raise_error
    raise OSError(errno.ENOSPC, "inotify watch limit reached")
OSError: [Errno 28] inotify watch limit reached
Exception: [Errno 28] inotify watch limit reached
Callstack:
Traceback (most recent call last):
  File "/nas-tools/app/sync.py", line 298, in run_service
    observer.start()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/api.py", line 262, in start
    emitter.start()
  File "/usr/lib/python3.10/site-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 167, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 365, in _add_dir_watch
    self._add_watch(path, mask)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 386, in _add_watch
    Inotify._raise_error()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 398, in _raise_error
    raise OSError(errno.ENOSPC, "inotify watch limit reached")
OSError: [Errno 28] inotify watch limit reached
2023-01-06 17:21:11,060	ERROR: /data1/Unknown 启动目录监控失败：[Errno 28] inotify watch limit reached
Traceback (most recent call last):
  File "/nas-tools/run.py", line 181, in <module>
    monitor_config()
  File "/nas-tools/run.py", line 171, in monitor_config
    _observer.start()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/api.py", line 262, in start
    emitter.start()
  File "/usr/lib/python3.10/site-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 167, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 365, in _add_dir_watch
    self._add_watch(path, mask)
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 386, in _add_watch
    Inotify._raise_error()
  File "/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 398, in _raise_error
    raise OSError(errno.ENOSPC, "inotify watch limit reached")
OSError: [Errno 28] inotify watch limit reached
2023-01-06T17:21:11: PM2 log: App [NAStool:0] exited with code [1] via signal [SIGINT]
2023-01-06T17:21:11: PM2 log: App [NAStool:0] starting in -fork mode-
2023-01-06T17:21:11: PM2 log: App [NAStool:0] online
正在加载配置：/config/config.yaml
NAStool 当前版本号：v2.7.5
开始初始化数据库...
数据库初始化完成
开始更新数据库...
数据库更新完成
日志输出类型为：file
日志将写入文件：/config/logs

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by jxxghp** [comment]
请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问
