### ISSUE TITLE
gotify 出翔 Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by ciegyet** [jxxghp/nas-tools#2878]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>
> 环境: docker or windows or Synology
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Shurelol** [comment]
发日志

**Comment by ciegyet** [comment]
以下是Docker 的日志
Exception: Expecting value: line 1 column 1 (char 0)
Callstack:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/nas-tools/app/message/client/gotify.py", line 60, in send_msg
    message = res.json()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-01-07 15:23:41,754 ERROR: 【Message】gotify 发送测试消息失败：Expecting value: line 1 column 1 (char 0)

**Comment by ciegyet** [comment]
> 发日志

以下是Docker 的日志
Exception: Expecting value: line 1 column 1 (char 0)
Callstack:
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/requests/models.py", line 971, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/lib/python3.10/json/init.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/nas-tools/app/message/client/gotify.py", line 60, in send_msg
message = res.json()
File "/usr/lib/python3.10/site-packages/requests/models.py", line 975, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-01-07 15:23:41,754 ERROR: 【Message】gotify 发送测试消息失败：Expecting value: line 1 column 1 (char 0)
