### ISSUE TITLE
docker反复加载配置重启，无法正常进入程序

### ISSUE THREAD

**Issue by zzfree2021** [jxxghp/nas-tools#2887]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: docker中的latest
>
> 环境: 威联通容器
>

## 你遇到什么问题了？
nastools容器反复重启，无法正常进入web页面
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: DOWNLOAD_SETTING
[SQL: UPDATE RSS_MOVIES SET DOWNLOAD_SETTING = null WHERE DOWNLOAD_SETTING = -1]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-08T08:20:23: PM2 log: App [NAStool:0] exited with code [1] via signal [SIGINT]
2023-01-08T08:20:23: PM2 log: App [NAStool:0] starting in -fork mode-
2023-01-08T08:20:23: PM2 log: App [NAStool:0] online
正在加载配置：/config/config.yaml
2023-01-08T08:20:25: PM2 log: Stopping app:NAStool id:0
Traceback (most recent call last):
  File "/nas-tools/run.py", line 51, in <module>
    from web.main import App
  File "/nas-tools/web/main.py", line 22, in <module>
    from app.brushtask import BrushTask
  File "/nas-tools/app/brushtask.py", line 14, in <module>
    from app.rss import Rss
  File "/nas-tools/app/rss.py", line 13, in <module>
    from app.subscribe import Subscribe

> 描述一下你遇到的问题

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by JimmyBaize** [comment]
我也遇到这个问题了，一直重启
2023-01-08T09:28:53: PM2 log: App [NAStool:0] online
正在加载配置：/config/config.yaml
NAStool 当前版本号：v2.7.5
开始初始化数据库...
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: DOWNLOAD_SETTING
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/nas-tools/run.py", line 175, in <module>
    init_system()
  File "/nas-tools/run.py", line 109, in init_system
    init_db()
  File "/nas-tools/app/db/__init__.py", line 18, in init_db
    MainDb().init_data()
  File "/nas-tools/app/db/main_db.py", line 53, in init_data
    self.excute(sql)
  File "/nas-tools/app/db/main_db.py", line 79, in excute
    self.session.execute(sql)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: DOWNLOAD_SETTING
[SQL: UPDATE RSS_MOVIES SET DOWNLOAD_SETTING = null WHERE DOWNLOAD_SETTING = -1]

**Comment by jxxghp** [comment]
数据库没有升级成功，重启Docker让数据库自动升级。

**Comment by JimmyBaize** [comment]
> 数据库没有升级成功，重启Docker让数据库自动升级。

docker restart nas-tools 试过了，重启也不行。

**Comment by jxxghp** [comment]
不知道是啥情况，正常按版本号安装是会自动升级数据库的。
不然只能手工进数据库，把数据库中的版本号清掉。重启。

**Comment by JimmyBaize** [comment]
> 手工进数据库，把数据库中的版本号清掉。重启。

这个操作怎么搞？帮指导下
我试了前几个版本都起不来。不知道是不是因为中间几个版本没有自动更新引起的。

**Comment by JimmyBaize** [comment]
回退到2.7.3 是正常的

**Comment by jxxghp** [comment]
这种问题没办法帮你，自己研究解决吧

**Comment by zzfree2021** [comment]
经常性一升级，就挂掉

**Comment by zzfree2021** [comment]
> ，重启Docker让数据库自动升级。

重启，docker自动关闭，手动开还是一会自动停止，反复这样

**Comment by muzhi1991** [comment]
同样的问题，只能回退
