### ISSUE TITLE
win这个版本打不开，准备直接在WIN运行PY，卡在这一步

### ISSUE THREAD

**Issue by gyshier** [jxxghp/nas-tools#2987]
D:\AAA\Nastool>python run.py
【Config】加载 config.yaml 配置出错：[Errno 22] Invalid argument: '"/xxx/config/config.yaml"'
Traceback (most recent call last):
  File "D:\AAA\Nastool\run.py", line 51, in <module>
    from web.main import App
  File "D:\AAA\Nastool\web\main.py", line 22, in <module>
    from app.brushtask import BrushTask
  File "D:\AAA\Nastool\app\brushtask.py", line 10, in <module>
    from app.downloader.client import Qbittorrent, Transmission
  File "D:\AAA\Nastool\app\downloader\__init__.py", line 1, in <module>
    from .downloader import Downloader
  File "D:\AAA\Nastool\app\downloader\downloader.py", line 6, in <module>
    from app.filetransfer import FileTransfer
  File "D:\AAA\Nastool\app\filetransfer.py", line 15, in <module>
    from app.media import Media, Category, Scraper
  File "D:\AAA\Nastool\app\media\__init__.py", line 2, in <module>
    from .media import Media
  File "D:\AAA\Nastool\app\media\media.py", line 13, in <module>
    from app.media.meta.metainfo import MetaInfo
  File "D:\AAA\Nastool\app\media\meta\__init__.py", line 1, in <module>
    from .metainfo import MetaInfo
  File "D:\AAA\Nastool\app\media\meta\metainfo.py", line 6, in <module>
    from app.media.meta.metaanime import MetaAnime
  File "D:\AAA\Nastool\app\media\meta\metaanime.py", line 5, in <module>
    import anitopy
ModuleNotFoundError: No module named 'anitopy'

/xxx/config/config.yaml我把这个换成D盘文件路径也不行，额，看不懂

**Comment by Shurelol** [comment]
项目说明里说的很清楚了
