### ISSUE TITLE
docker版数据库v2.7.6无限重启

### ISSUE THREAD

**Issue by CaptNo78-GitHub** [jxxghp/nas-tools#2989]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.7.6
>
> 环境: docker
>

## 你遇到什么问题了？

> 描述一下你遇到的问题

数据库无限重启

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

是

## 你期望的结果

> 描述以下你期望的结果

问题解决

## 给出程序界面截图、后台运行日志或配置文件
正在加载配置：/config/config.yaml
NAStool 当前版本号：v2.7.6
开始初始化数据库...
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: DOWNLOAD_SETTING
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/nas-tools/run.py", line 175, in <module>
    init_system()
  File "/nas-tools/run.py", line 109, in init_system
    init_db()
  File "/nas-tools/app/db/__init__.py", line 18, in init_db
    MainDb().init_data()
  File "/nas-tools/app/db/main_db.py", line 53, in init_data
    self.excute(sql)
  File "/nas-tools/app/db/main_db.py", line 79, in excute
    self.session.execute(sql)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: DOWNLOAD_SETTING
[SQL: UPDATE RSS_MOVIES SET DOWNLOAD_SETTING = null WHERE DOWNLOAD_SETTING = -1]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2023-01-13T16:31:10: PM2 log: App [NAStool:0] exited with code [1] via signal [SIGINT]
2023-01-13T16:31:10: PM2 log: App [NAStool:0] starting in -fork mode-
2023-01-13T16:31:10: PM2 log: App [NAStool:0] online

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by inforest27** [comment]
请问解决了吗
