### ISSUE TITLE
更改web_host为0.0.0.0后程序无法启动

### ISSUE THREAD

**Issue by WLYseven** [jxxghp/nas-tools#3024]
弹窗提示以下信息
Traceback (most recent call last):
  File "run.py", line 176, in <module>
  File "run.py", line 109, in init_system
  File "app\db\__init__.py", line 18, in init_db
  File "app\db\main_db.py", line 57, in init_data
KeyError: 'app'

**Comment by jxxghp** [comment]
改配置的时候把yaml格式改坏了？
日志贴全
