### ISSUE TITLE
电影和电视剧订阅页面不显示

### ISSUE THREAD

**Issue by SheepChao** [jxxghp/nas-tools#3086]
> NAStool 版本: v2.8.0
>
> 环境: docker 
>

> 描述一下你遇到的问题
今天在NASTOOLS主界面上点击了更新，从之前的版本更新到v2.8.0。之前有订阅过电视剧和电影，现在电影和电视剧里面都不显示订阅记录了，打不开这两个订阅页面。但是在电影搜索结果，电影推荐里面列表里面，会对之前的订阅电影有一个红心标记。

> 其它问题提供后台日志，如为Docker请提供docker的日志
[2023-01-21 11:49:41,987] ERROR in app: Exception on /movie_rss [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: RSS_MOVIES.KEYWORD
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/nas-tools/web/main.py", line 283, in movie_rss
    RssItems = WebAction().get_movie_rss_list().get("result")
  File "/nas-tools/web/action.py", line 3556, in get_movie_rss_list
    return {"code": 0, "result": Subscribe().get_subscribe_movies()}
  File "/nas-tools/app/subscribe.py", line 324, in get_subscribe_movies
    rss_movies = self.dbhelper.get_rss_movies(rssid=rid, state=state)
  File "/nas-tools/app/helper/db_helper.py", line 606, in get_rss_movies
    return self._db.query(RSSMOVIES).all()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2772, in all
    return self._iter().all()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2907, in _iter
    result = self.session.execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: RSS_MOVIES.KEYWORD
[SQL: SELECT "RSS_MOVIES"."ID" AS "RSS_MOVIES_ID", "RSS_MOVIES"."NAME" AS "RSS_MOVIES_NAME", "RSS_MOVIES"."YEAR" AS "RSS_MOVIES_YEAR", "RSS_MOVIES"."KEYWORD" AS "RSS_MOVIES_KEYWORD", "RSS_MOVIES"."TMDBID" AS "RSS_MOVIES_TMDBID", "RSS_MOVIES"."IMAGE" AS "RSS_MOVIES_IMAGE", "RSS_MOVIES"."RSS_SITES" AS "RSS_MOVIES_RSS_SITES", "RSS_MOVIES"."SEARCH_SITES" AS "RSS_MOVIES_SEARCH_SITES", "RSS_MOVIES"."OVER_EDITION" AS "RSS_MOVIES_OVER_EDITION", "RSS_MOVIES"."FILTER_ORDER" AS "RSS_MOVIES_FILTER_ORDER", "RSS_MOVIES"."FILTER_RESTYPE" AS "RSS_MOVIES_FILTER_RESTYPE", "RSS_MOVIES"."FILTER_PIX" AS "RSS_MOVIES_FILTER_PIX", "RSS_MOVIES"."FILTER_RULE" AS "RSS_MOVIES_FILTER_RULE", "RSS_MOVIES"."FILTER_TEAM" AS "RSS_MOVIES_FILTER_TEAM", "RSS_MOVIES"."SAVE_PATH" AS "RSS_MOVIES_SAVE_PATH", "RSS_MOVIES"."DOWNLOAD_SETTING" AS "RSS_MOVIES_DOWNLOAD_SETTING", "RSS_MOVIES"."FUZZY_MATCH" AS "RSS_MOVIES_FUZZY_MATCH", "RSS_MOVIES"."STATE" AS "RSS_MOVIES_STATE", "RSS_MOVIES"."DESC" AS "RSS_MOVIES_DESC", "RSS_MOVIES"."NOTE" AS "RSS_MOVIES_NOTE" 
FROM "RSS_MOVIES"]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by ainas999** [comment]
我刚刚更新完也是不显示这两个页面。

**Comment by jxxghp** [comment]
问题修复：v2.8.0版本由于数据库升级顺序问题，第一时间就完成了升级的，数据库可能无法准确更新，且不会再次触发更新操作，可按如下方式处理：
1、更新到当前最新程序、或拉取最新镜像（小版本号：3d7059e）。
2、备份配置->重新导入配置->重启（整理历史记录会丢失）；或者使用sqllite数据库软件打开user.db->删除alembic_version表->重启（所有数据完整保留）。

其中删除alembic_version表的方法也可用于解决Windows版本无法启动的问题。
