### ISSUE TITLE
QB自动删种失效

### ISSUE THREAD

**Issue by szjawo** [jxxghp/nas-tools#3145]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.1
>
> 环境: docker
>

## 你遇到什么问题了？

> QB自动删种失效，其中QB使用的是docker版的nevinee-qbittorrent（https://registry.hub.docker.com/r/nevinee/qbittorrent/）。自动删种一直报错。这个版本的qb，其目录与正常的不同，不知道该问题是否与此相关。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 使得自动删种可以在此QB的docker镜像中正常使用。

## 给出程序界面截图、后台运行日志或配置文件

> 2023-01-25 07:03:32	stdout	qbittorrentapi.exceptions.MissingRequiredParameters400Error
2023-01-25 07:03:32	stdout	    raise MissingRequiredParameters400Error()
2023-01-25 07:03:32	stdout	  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 634, in _handle_error_responses
2023-01-25 07:03:32	stdout	    self._handle_error_responses(data, params, response)
2023-01-25 07:03:32	stdout	  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 463, in _request
2023-01-25 07:03:32	stdout	    return self._request(**kwargs)
2023-01-25 07:03:32	stdout	  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 401, in _request_manager
2023-01-25 07:03:32	stdout	    return self._request_manager(
2023-01-25 07:03:32	stdout	  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 350, in _post
2023-01-25 07:03:32	stdout	    return self._post(_name=APINames.Torrents, _method="info", data=data, **kwargs)
2023-01-25 07:03:32	stdout	  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/torrents.py", line 1663, in torrents_info
2023-01-25 07:03:32	stdout	    return func(client, *args, **kwargs)
2023-01-25 07:03:32	stdout	  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/decorators.py", line 92, in wrapper
2023-01-25 07:03:32	stdout	    response = func(client, *args, **kwargs)
2023-01-25 07:03:32	stdout	  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/decorators.py", line 164, in wrapper
2023-01-25 07:03:32	stdout	    return func(client, *args, **kwargs)
2023-01-25 07:03:32	stdout	  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/decorators.py", line 119, in wrapper
2023-01-25 07:03:32	stdout	    torrents = self.qbc.torrents_info(torrent_hashes=ids, status_filter=status, tag=tag)
2023-01-25 07:03:32	stdout	  File "/nas-tools/app/downloader/client/qbittorrent.py", line 99, in get_torrents
2023-01-25 07:03:32	stdout	Traceback (most recent call last):
2023-01-25 07:03:32	stdout	Callstack:
2023-01-25 07:03:32	stdout	Exception: 
2023-01-25 07:03:29	stdout	2023-01-25 15:03:29,803 INFO: 【TorrentRemover】自动删种任务：1 获取符合处理条件种子数 0
2023-01-25 07:03:29	stdout	qbittorrentapi.exceptions.MissingRequiredParameters400Error
2023-01-25 07:03:29	stdout	    raise MissingRequiredParameters400Error()
2023-01-25 07:03:29	stdout	  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 634, in _handle_error_responses
2023-01-25 07:03:29	stdout	    self._handle_error_responses(data, params, response)
2023-01-25 07:03:29	stdout	  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 463, in _request
2023-01-25 07:03:29	stdout	    return self._request(**kwargs)
2023-01-25 07:03:29	stdout	  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 401, in _request_manager
2023-01-25 07:03:29	stdout	    return self._request_manager(
2023-01-25 07:03:29	stdout	  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 350, in _post
2023-01-25 07:03:29	stdout	    return self._post(_name=APINames.Torrents, _method="info", data=data, **kwargs)
2023-01-25 07:03:29	stdout	  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/torrents.py", line 1663, in torrents_info
2023-01-25 07:03:29	stdout	    return func(client, *args, **kwargs)
2023-01-25 07:03:29	stdout	  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/decorators.py", line 92, in wrapper
2023-01-25 07:03:29	stdout	    response = func(client, *args, **kwargs)
2023-01-25 07:03:29	stdout	  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/decorators.py", line 164, in wrapper
2023-01-25 07:03:29	stdout	    return func(client, *args, **kwargs)
2023-01-25 07:03:29	stdout	  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/decorators.py", line 119, in wrapper
2023-01-25 07:03:29	stdout	    torrents = self.qbc.torrents_info(torrent_hashes=ids, status_filter=status, tag=tag)
2023-01-25 07:03:29	stdout	  File "/nas-tools/app/downloader/client/qbittorrent.py", line 99, in get_torrents
2023-01-25 07:03:29	stdout	Traceback (most recent call last):
2023-01-25 07:03:29	stdout	Callstack:
2023-01-25 07:03:29	stdout	Exception: 
2023-01-25 07:00:30	stdout	2023-01-25 15:00:30,135 INFO: 【Brush】任务 PTHOME保种 本次检查未删除下载任务
2023-01-25 07:00:29	stdout	2023-01-25 15:00:29,899 INFO: 【Brush】任务 M-Team刷流 本次检查未删除下载任务
2023-01-25 06:55:29	stdout	2023-01-25 14:55:29,844 INFO: /PTdownloads/act 的监控服务启动
2023-01-25 06:55:29	stdout	2023-01-25 14:55:29,836 INFO: /PTdownloads/教育 的监控服务启动
2023-01-25 06:55:29	stdout	2023-01-25 14:55:29,836 INFO: /private/课程 的监控服务启动
2023-01-25 06:55:29	stdout	2023-01-25 14:55:29,834 INFO: /special mark 的监控服务启动
2023-01-25 06:55:29	stdout	2023-01-25 14:55:29,804 INFO: /PTdownloads/综艺 的监控服务启动
2023-01-25 06:55:29	stdout	2023-01-25 14:55:29,804 INFO: /PTdownloads/动漫 的监控服务启动
2023-01-25 06:55:29	stdout	2023-01-25 14:55:29,803 INFO: /PTdownloads/电视剧 的监控服务启动
2023-01-25 06:55:29	stdout	2023-01-25 14:55:29,803 INFO: /PTdownloads/电影 的监控服务启动
2023-01-25 06:55:29	stdout	    get_login_wallpaper (trigger: interval[1:00:00], next run at: 2023-01-25 14:55:29 CST)
2023-01-25 06:55:29	stdout	    MetaHelper.delete_unknown_meta (trigger: interval[12:00:00], pending)
2023-01-25 06:55:29	stdout	    Subscribe.refresh_rss_metainfo (trigger: interval[6:00:00], pending)
2023-01-25 06:55:29	stdout	    Sites.refresh_pt_date_now (trigger: interval[6:00:00], next run at: 2023-01-25 14:56:29 CST)
2023-01-25 06:55:29	stdout	    Subscribe.subscribe_search (trigger: interval[0:05:00], pending)
2023-01-25 06:55:29	stdout	    Sync.transfer_mon_files (trigger: interval[0:01:00], pending)
2023-01-25 06:55:29	stdout	    MetaHelper.save_meta_data (trigger: interval[0:10:00], pending)
2023-01-25 06:55:29	stdout	    MediaServer.sync_mediaserver (trigger: interval[12:00:00], pending)
2023-01-25 06:55:29	stdout	    DoubanSync.sync (trigger: interval[12:00:00], pending)
2023-01-25 06:55:29	stdout	    Subscribe.subscribe_search_all (trigger: interval[6:00:00], pending)
2023-01-25 06:55:29	stdout	    Sites.signin (trigger: cron[hour='8', minute='1'], pending)
2023-01-25 06:55:29	stdout	Pending jobs:
2023-01-25 06:55:29	stdout	2023-01-25 14:55:29,793 INFO: 媒体库同步服务启动
2023-01-25 06:55:29	stdout	2023-01-25 14:55:29,793 INFO: 豆瓣同步服务启动
2023-01-25 06:55:29	stdout	2023-01-25 14:55:29,792 INFO: 订阅定时搜索服务启动
2023-01-25 06:55:29	stdout	2023-01-25 14:55:29,791 INFO: 站点自动签到服务启动
2023-01-25 06:55:29	stdout	2023-01-25 14:55:29,768 INFO: 自动删种服务启动
2023-01-25 06:55:29	stdout	    TorrentRemover.auto_remove_torrents (trigger: interval[0:10:00], pending)

**Comment by szjawo** [comment]
另附QB的docker所报的错误
> <html>
<body>


2023-01-25 07:05:30 | stdout | (N) 2023-01-25T15:05:30 - WebAPI 登录成功。IP：::ffff:192.168.86.4
-- | -- | --
2023-01-25 07:05:29 | stdout | (W) 2023-01-25T15:05:29 - Http 请求错误，关闭套接字。IP：::ffff:192.168.86.4
2023-01-25 07:05:29 | stdout | Http::RequestParser::ParseResult Http::RequestParser::doParse(const QByteArray&) bad request: content-length invalid
2023-01-25 07:03:32 | stdout | (W) 2023-01-25T15:03:32 - Http 请求错误，关闭套接字。IP：::ffff:192.168.86.4
2023-01-25 07:03:32 | stdout | Http::RequestParser::ParseResult Http::RequestParser::doParse(const QByteArray&) bad request: content-length invalid
2023-01-25 07:03:29 | stdout | (W) 2023-01-25T15:03:29 - Http 请求错误，关闭套接字。IP：::ffff:192.168.86.4
2023-01-25 07:03:29 | stdout | Http::RequestParser::ParseResult Http::RequestParser::doParse(const QByteArray&) bad request: content-length invalid
2023-01-25 07:00:29 | stdout | (N) 2023-01-25T15:00:29 - WebAPI 登录成功。IP：::ffff:192.168.86.4
2023-01-25 06:55:23 | stdout | (N) 2023-01-25T14:55:23 - WebAPI 登录成功。IP：::ffff:192.168.86.4
2023-01-25 06:53:45 | stdout | (W) 2023-01-25T14:53:45 - Http 请求错误，关闭套接字。IP：::ffff:192.168.86.4
2023-01-25 06:53:45 | stdout | Http::RequestParser::ParseResult Http::RequestParser::doParse(const QByteArray&) bad request: content-length invalid
2023-01-25 06:53:43 | stdout | (W) 2023-01-25T14:53:43 - Http 请求错误，关闭套接字。IP：::ffff:192.168.86.4
2023-01-25 06:53:43 | stdout | Http::RequestParser::ParseResult Http::RequestParser::doParse(const QByteArray&) bad request: content-length invalid
2023-01-25 06:53:30 | stdout | (N) 2023-01-25T14:53:30 - WebAPI 登录成功。IP：::ffff:192.168.86.4
2023-01-25 06:53:09 | stdout | (N) 2023-01-25T14:53:08 - WebAPI 登录成功。IP：::ffff:192.168.86.4
2023-01-25 06:52:44 | stdout | (W) 2023-01-25T14:52:44 - Http 请求错误，关闭套接字。IP：::ffff:192.168.86.4
2023-01-25 06:52:44 | stdout | Http::RequestParser::ParseResult Http::RequestParser::doParse(const QByteArray&) bad request: content-length invalid
2023-01-25 06:50:21 | stdout | (N) 2023-01-25T14:50:20 - WebAPI 登录成功。IP：::ffff:192.168.86.4
2023-01-25 06:45:37 | stdout | (W) 2023-01-25T14:45:37 - Http 请求错误，关闭套接字。IP：::ffff:192.168.86.4
2023-01-25 06:45:37 | stdout | Http::RequestParser::ParseResult Http::RequestParser::doParse(const QByteArray&) bad request: content-length invalid
2023-01-25 06:45:35 | stdout | (W) 2023-01-25T14:45:35 - Http 请求错误，关闭套接字。IP：::ffff:192.168.86.4
2023-01-25 06:45:35 | stdout | (N) 2023-01-25T14:45:35 - WebAPI 登录成功。IP：::ffff:192.168.86.4
2023-01-25 06:45:35 | stdout | Http::RequestParser::ParseResult Http::RequestParser::doParse(const QByteArray&) bad request: content-length invalid
2023-01-25 06:41:40 | stdout | (W) 2023-01-25T14:41:40 - Http 请求错误，关闭套接字。IP：::ffff:192.168.86.4
2023-01-25 06:41:40 | stdout | Http::RequestParser::ParseResult Http::RequestParser::doParse(const QByteArray&) bad request: content-length invalid
2023-01-25 06:41:33 | stdout | (W) 2023-01-25T14:41:33 - Http 请求错误，关闭套接字。IP：::ffff:192.168.86.4
2023-01-25 06:41:33 | stdout | Http::RequestParser::ParseResult Http::RequestParser::doParse(const QByteArray&) bad request: content-length invalid
2023-01-25 06:41:30 | stdout | (W) 2023-01-25T14:41:30 - Http 请求错误，关闭套接字。IP：::ffff:192.168.86.4
2023-01-25 06:41:30 | stdout | Http::RequestParser::ParseResult Http::RequestParser::doParse(const QByteArray&) bad request: content-length invalid


</body>
</html>

**Comment by jxxghp** [comment]
看报错是QB的API不适配，应该是QB版本的问题
