### ISSUE TITLE
添加下载失败 请检查下载任务是否已存在！

### ISSUE THREAD

**Issue by TheSeaYouAreAllWater** [jxxghp/nas-tools#3260]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 2.8.2
>
> 环境: windows10 下使用docker安装
>

## 你遇到什么问题了？

![image](https://user-images.githubusercontent.com/40189242/215708852-a5676c66-49f2-431b-abaf-cecf513fe82a.png)

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

是

## 你期望的结果

> 描述以下你期望的结果
可以下载
## 给出程序界面截图、后台运行日志或配置文件
第一次报错
2023-01-31 15:30:57,993 INFO: 【Meta】正在查询TMDB电影：558 ...
2023-01-31 15:30:59,723 WARNING: 【Downloader】获取到磁力链接：magnet:?xt=urn:btih:d541b240c211b6405d90713ad2e2819450dd08ec&dn=Spider+Man+2&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.tracker.cl%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2810%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=https%3A%2F%2Fopentracker.i2p.rocks%3A443%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce
Exception: Failed to connect to qBittorrent. Connection Error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='172.17.0.4', port=8080): Max retries exceeded with url: /api/v2/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f456ea20ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))"))
Callstack:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f456ea20ee0>: Failed to establish a new connection: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='172.17.0.4', port=8080): Max retries exceeded with url: /api/v2/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f456ea20ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 401, in _request_manager
    return self._request(**kwargs)
  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 452, in _request
    response = self._session.request(
  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 562, in request
    return super(QbittorrentSession, self).request(method, url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.17.0.4', port=8080): Max retries exceeded with url: /api/v2/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f456ea20ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/nas-tools/app/downloader/client/qbittorrent.py", line 72, in __login_qbittorrent
    qbt.auth_log_in()
  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/auth.py", line 96, in auth_log_in
    self._post(_name=APINames.Authorization, _method="login", data=creds, **kwargs)
  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 350, in _post
    return self._request_manager(
  File "/nas-tools/third_party/qbittorrent-api/qbittorrentapi/request.py", line 411, in _request_manager
    raise APIConnectionError(error_message, response=response)
qbittorrentapi.exceptions.APIConnectionError: Failed to connect to qBittorrent. Connection Error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='172.17.0.4', port=8080): Max retries exceeded with url: /api/v2/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f456ea20ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))"))
2023-01-31 15:30:59,736 ERROR: 【Qbittorrent】qBittorrent连接出错：Failed to connect to qBittorrent. Connection Error: ConnectionError(MaxRetryError("HTTPConnectionPool(host='172.17.0.4', port=8080): Max retries exceeded with url: /api/v2/auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f456ea20ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))"))
2023-01-31 15:30:59,736 INFO: 【Downloader】添加下载任务：Spider Man 2，目录：None，Url：magnet:?xt=urn:btih:d541b240c211b6405d90713ad2e2819450dd08ec&dn=Spider+Man+2&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.tracker.cl%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2810%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=https%3A%2F%2Fopentracker.i2p.rocks%3A443%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce

后面报错

2023-01-31 16:32:40,164 INFO: 【Meta】正在查询TMDB电视剧：204541 ...
2023-01-31 16:32:41,107 WARNING: 【Downloader】获取到磁力链接：magnet:?xt=urn:btih:e3597cfe9d883e1cb33cdab8e1673e5060670242&dn=%5B%E7%94%B5%E8%A7%86%E5%89%A7%5D%5B%E4%B8%89%E4%BD%93%5D%5B%E4%B8%89%E4%BD%93(%E5%89%A7%E7%89%88)%5D%5BThree+Body%5D%5BThree-Body%5D%5B2023%5D%5BWEB%5D.txt&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.tracker.cl%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2810%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=https%3A%2F%2Fopentracker.i2p.rocks%3A443%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce
2023-01-31 16:32:41,108 INFO: 【Downloader】添加下载任务：[电视剧][三体][三体(剧版)][Three Body][Three-Body][2023][WEB].txt，目录：None，Url：magnet:?xt=urn:btih:e3597cfe9d883e1cb33cdab8e1673e5060670242&dn=%5B%E7%94%B5%E8%A7%86%E5%89%A7%5D%5B%E4%B8%89%E4%BD%93%5D%5B%E4%B8%89%E4%BD%93(%E5%89%A7%E7%89%88)%5D%5BThree+Body%5D%5BThree-Body%5D%5B2023%5D%5BWEB%5D.txt&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.tracker.cl%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2810%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=https%3A%2F%2Fopentracker.i2p.rocks%3A443%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce
> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

个人认为是不是docker下载时，不是内部访问qb，访问的ip地址不能为本地的吗？还是必须使用公网ip

**Comment by jxxghp** [comment]
你这个就是QB连不上：
host='172.17.0.4', port=8080

**Comment by TheSeaYouAreAllWater** [comment]
改了连接docker容器内部的ip，测试可以
![image](https://user-images.githubusercontent.com/40189242/215711211-1addacee-e2e0-41bb-a282-c697f47c5e15.png)
然后下载，还是报错
2023-01-31 16:42:59,287 INFO: 【Meta】正在查询TMDB电视剧：204541 ...
2023-01-31 16:42:59,713 WARNING: 【Downloader】获取到磁力链接：magnet:?xt=urn:btih:e3597cfe9d883e1cb33cdab8e1673e5060670242&dn=%5B%E7%94%B5%E8%A7%86%E5%89%A7%5D%5B%E4%B8%89%E4%BD%93%5D%5B%E4%B8%89%E4%BD%93(%E5%89%A7%E7%89%88)%5D%5BThree+Body%5D%5BThree-Body%5D%5B2023%5D%5BWEB%5D.txt&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.tracker.cl%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2810%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=https%3A%2F%2Fopentracker.i2p.rocks%3A443%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce
2023-01-31 16:42:59,714 INFO: 【Downloader】添加下载任务：[电视剧][三体][三体(剧版)][Three Body][Three-Body][2023][WEB].txt，目录：None，Url：magnet:?xt=urn:btih:e3597cfe9d883e1cb33cdab8e1673e5060670242&dn=%5B%E7%94%B5%E8%A7%86%E5%89%A7%5D%5B%E4%B8%89%E4%BD%93%5D%5B%E4%B8%89%E4%BD%93(%E5%89%A7%E7%89%88)%5D%5BThree+Body%5D%5BThree-Body%5D%5B2023%5D%5BWEB%5D.txt&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.tracker.cl%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2810%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=https%3A%2F%2Fopentracker.i2p.rocks%3A443%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce
正在加载配置：/config/config.yaml

**Comment by TheSeaYouAreAllWater** [comment]
> 你这个就是QB连不上： host='172.17.0.4', port=8080

改了连接docker容器内部的ip，测试可以
![image](https://user-images.githubusercontent.com/40189242/215711523-a8ec7cdb-0508-4cb4-97cf-a45611d64b72.png)

然后下载，还是报错
2023-01-31 16:42:59,287 INFO: 【Meta】正在查询TMDB电视剧：204541 ...
2023-01-31 16:42:59,713 WARNING: 【Downloader】获取到磁力链接：magnet:?xt=urn:btih:e3597cfe9d883e1cb33cdab8e1673e5060670242&dn=%5B%E7%94%B5%E8%A7%86%E5%89%A7%5D%5B%E4%B8%89%E4%BD%93%5D%5B%E4%B8%89%E4%BD%93(%E5%89%A7%E7%89%88)%5D%5BThree+Body%5D%5BThree-Body%5D%5B2023%5D%5BWEB%5D.txt&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.tracker.cl%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2810%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=https%3A%2F%2Fopentracker.i2p.rocks%3A443%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce
2023-01-31 16:42:59,714 INFO: 【Downloader】添加下载任务：[电视剧][三体][三体(剧版)][Three Body][Three-Body][2023][WEB].txt，目录：None，Url：magnet:?xt=urn:btih:e3597cfe9d883e1cb33cdab8e1673e5060670242&dn=%5B%E7%94%B5%E8%A7%86%E5%89%A7%5D%5B%E4%B8%89%E4%BD%93%5D%5B%E4%B8%89%E4%BD%93(%E5%89%A7%E7%89%88)%5D%5BThree+Body%5D%5BThree-Body%5D%5B2023%5D%5BWEB%5D.txt&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.tracker.cl%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2810%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=https%3A%2F%2Fopentracker.i2p.rocks%3A443%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce
正在加载配置：/config/config.yaml

**Comment by xiao-xiaozi** [comment]
遇到了一样的问题。

**Comment by TheSeaYouAreAllWater** [comment]
> 遇到了一样的问题。

需要先把媒体库配置上，否则不行，plex、jettyfly你随便装一个配置上去才行，所有的装完后，配置完成后，才能使用

**Comment by xiao-xiaozi** [comment]
> > 遇到了一样的问题。
> 
> 需要先把媒体库配置上，否则不行，plex、jettyfly你随便装一个配置上去才行，所有的装完后，配置完成后，才能使用

用的R66S装了iStoreOS，套件都配置上了。测试jettyfly是可以的，就qb不行，在qb手动添加下载倒是可以。可能哪里没配置对，再研究看看

**Comment by mingzaily** [comment]
同样的问题，不管是qt还是tr配置了都没效果，都是报这个错误
![image](https://user-images.githubusercontent.com/44798713/217576496-230c6d81-df5c-4419-8a19-9a4540836656.png)
不管是手动上次种子还是用资源搜索里的下载，都没办法下载，已经配置了plex

**Comment by lilarcor** [comment]
一样的问题

**Comment by mingzaily** [comment]
> 同样的问题，不管是qt还是tr配置了都没效果，都是报这个错误 ![image](https://user-images.githubusercontent.com/44798713/217576496-230c6d81-df5c-4419-8a19-9a4540836656.png) 不管是手动上次种子还是用资源搜索里的下载，都没办法下载，已经配置了plex

我重新试了下，你们如果docker启动是bridge模式，可以输入下内网的IP就是172.17.0.X

**Comment by ourines** [comment]
如果上面配置都没问题的话，你尝试看看是不是puid，pgid这两个参数正确吗
