### ISSUE TITLE
关于权限的一些问题

### ISSUE THREAD

**Issue by tediorelee** [jxxghp/nas-tools#447]
作者你好！

我在TrueNAS Scale上跑了一个docker app来运行nastool，假定前提我的共享文件夹目录属于user 1，group 1，PUID和GUID都为1000

我在运行nastool的时候，如果指定运行用户为1000，即容器无法正常启动，logs可以看到chown operation not permitted

![image](https://user-images.githubusercontent.com/48272067/177794652-6f185d30-8c0f-4473-8a15-e2ba892e49b1.png)

如果切换运行nastool app用户为root用户(id 0)，可以正常启动nastool

但是在nastool内，运行目录同步的时候，会发生权限错误

```
22:06:43 INFO - 【RMT】开始处理：/Files/Download/movie/Morbius.2022.1080p.WEB-DL.AAC2.0.H264-HAMR.mkv
22:06:43 ERROR - 【RMT】文件转移时发生错误：[Errno 13] Permission denied: '/Files/Emby/Movie/外语电影' - Traceback (most recent call last): File "/nas-tools/rmt/filetransfer.py", line 581, in transfer_media os.makedirs(ret_dir_path) File "/usr/lib/python3.10/os.py", line 215, in makedirs makedirs(head, exist_ok=exist_ok) File "/usr/lib/python3.10/os.py", line 225, in makedirs mkdir(name, mode) PermissionError: [Errno 13] Permission denied: '/Files/Emby/Movie/外语电影'
22:06:44 INFO - 【RMT】/Files/Download/movie/Morbius.2022.1080p.WEB-DL.AAC2.0.H264-HAMR.mkv 处理完成，总数：1，失败：0
22:06:44 INFO - 【RMT】开始处理：/Files/Download/movie/Doctor.Strange.in.the.Multiverse.of.Madness.2022.2160p.WEB-DL.HDR.HEVC.DDP5.1.Atmos-HDSWEB.mkv
22:06:44 ERROR - 【RMT】文件转移时发生错误：[Errno 13] Permission denied: '/Files/Emby/Movie/外语电影' - Traceback (most recent call last): File "/nas-tools/rmt/filetransfer.py", line 581, in transfer_media os.makedirs(ret_dir_path) File "/usr/lib/python3.10/os.py", line 215, in makedirs makedirs(head, exist_ok=exist_ok) File "/usr/lib/python3.10/os.py", line 225, in makedirs mkdir(name, mode) PermissionError: [Errno 13] Permission denied: '/Files/Emby/Movie/外语电影'
22:06:44 INFO - 【RMT】/Files/Download/movie/Doctor.Strange.in.the.Multiverse.of.Madness.2022.2160p.WEB-DL.HDR.HEVC.DDP5.1.Atmos-HDSWEB.mkv 处理完成，总数：1，失败：0
```

目前卡在这里无法进行下一步

**Comment by jxxghp** [comment]
权限问题跟这个程序没关系，只能自己解决。
