### ISSUE TITLE
微信消息处理问题

### ISSUE THREAD

**Issue by Tartarus2014** [jxxghp/nas-tools#448]
19:27:23 ERROR - 微信消息处理发生错误：invalid literal for int() with base 10: '' - Traceback (most recent call last): File "/nas-tools/web/main.py", line 1371, in wechat WebAction().handle_message_job(content, SearchType.WX, user_id) File "/nas-tools/web/action.py", line 133, in handle_message_job "/db": {"func": DouBan().sync, "desp": "豆瓣同步"} File "/nas-tools/pt/douban.py", line 42, in __init__ self.init_config() File "/nas-tools/pt/douban.py", line 49, in init_config self.__interval = int(douban.get('interval')) ValueError: invalid literal for int() with base 10: ''

**Comment by Tartarus2014** [comment]
> 19:27:23 ERROR - 微信消息处理发生错误：invalid literal for int() with base 10: '' - Traceback (most recent call last): File "/nas-tools/web/main.py", line 1371, in wechat WebAction().handle_message_job(content, SearchType.WX, user_id) File "/nas-tools/web/action.py", line 133, in handle_message_job "/db": {"func": DouBan().sync, "desp": "豆瓣同步"} File "/nas-tools/pt/douban.py", line 42, in **init** self.init_config() File "/nas-tools/pt/douban.py", line 49, in init_config self.__interval = int(douban.get('interval')) ValueError: invalid literal for int() with base 10: ''

这个是啥问题啊
