### ISSUE TITLE
站点适配需求：柠檬、城市、1ptbar

### ISSUE THREAD

**Issue by log-time** [jxxghp/nas-tools#450]
站点适配需求：柠檬、城市、1ptbar。

目前各站点数据显示情况如下：

![Screenshot_20220708_201237](https://user-images.githubusercontent.com/66826612/177989954-8bd84095-5844-4999-8c97-5e6ca5c1e644.png)
![Screenshot_20220708_201253](https://user-images.githubusercontent.com/66826612/177989991-bbc65e61-a02a-480c-b73e-e83b10ffe273.png)
![Screenshot_20220708_201314](https://user-images.githubusercontent.com/66826612/177990012-434207af-0f4c-4ec7-8f5c-1a18dca8fd4f.png)

柠檬目前保种数和保种体积无法正常显示；1ptbar除了上传和下载数据正确，其他包括用户名、等级等数据均异常；城市所有数据均异常。

**Comment by log-time** [comment]
站点网址：https://1ptba.com/
FREE：<font class="free">免费</font>
2xFREE：站免暂时无法获取
HR：<img class="hitandrun" src="pic/trans.gif" alt="H&amp;R" title="H&amp;R">

**Comment by log-time** [comment]
`
站点网址：https://www.tjupt.org/
FREE：全站免费
2XFREE：<font class="twoup">2X</font>
HR：<font color="red">Hit&amp;Run</font>

`

**Comment by YuChuQing** [comment]
你好，如果有时间请麻烦适配下hdroute.org，目前在站点维护后，统计信息无法正常展示，种子下载也有问题

**Comment by log-time** [comment]
> 你好，如果有时间请麻烦适配下hdroute.org，目前在站点维护后，统计信息无法正常展示，种子下载也有问题

索引器你用的是？一般jackett或者prowlarr支持的站点不需要适配都可以直接使用的。
站点的数据展示，可以截个图上来。

**Comment by log-time** [comment]
![QQ图片20220713110645](https://user-images.githubusercontent.com/66826612/178642342-2dd29ccb-966c-4a63-855d-3f21285d8d57.png)
吐鲁番的这个分享率好像有问题

**Comment by log-time** [comment]
[a3f42e4](https://github.com/jxxghp/nas-tools/commit/a3f42e4ff7785fb8f773576cfbf599027ee51a3b)   已修复吐鲁番的这个分享率问题
[79db473](https://github.com/jxxghp/nas-tools/commit/79db4737935619fccfdf78e1d35adf6b4cb2a2fc)   已修复柠檬数据显示异常问题
[84bd99d](https://github.com/jxxghp/nas-tools/commit/84bd99dbb7ba64f0738b3a1efde30bc1fe5b24e6)   已修复1ptbar数据获取异常问题

**Comment by JKnuts** [comment]
HDArea站点数据异常，没有下载量
![image](https://user-images.githubusercontent.com/91355283/179382839-52bfa83b-fd11-45d7-9e91-a34951fdbac9.png)

**Comment by Chen3553887** [comment]
![微信图片_20220717161906](https://user-images.githubusercontent.com/74977868/179390046-94e5cd2c-91b8-4f95-bf66-3fabc4828caa.png)
![微信图片_20220717161926](https://user-images.githubusercontent.com/74977868/179390048-70b56fae-8958-484b-bad3-27185ae0a0c9.png)
希望可以在电视剧订阅的界面，添加一个根据TMDB ID订阅的选项。

**Comment by log-time** [comment]
[fafb446](https://github.com/jxxghp/nas-tools/commit/fafb44603a80b2dd69e42e59b8c7876e4bb53087)已适配城市

**Comment by log-time** [comment]
> ![微信图片_20220717161906](https://user-images.githubusercontent.com/74977868/179390046-94e5cd2c-91b8-4f95-bf66-3fabc4828caa.png) ![微信图片_20220717161926](https://user-images.githubusercontent.com/74977868/179390048-70b56fae-8958-484b-bad3-27185ae0a0c9.png) 在添加订阅后，识别出现问题自动变成了另外一个同名的剧集。 希望可以在电视剧订阅的界面，添加一个根据TMDB ID订阅的选项。

这个汇总帖主要是在做站点的适配，功能上的建议需要跟作者提。
@jxxghp

**Comment by lightolly** [comment]
> HDArea站点数据异常，没有下载量
> 
> ![image](https://user-images.githubusercontent.com/91355283/179382839-52bfa83b-fd11-45d7-9e91-a34951fdbac9.png)
> 
> 

帮忙确认下新版本是否已经正常

**Comment by JKnuts** [comment]
> 
可以了，HDArea识别正常

**Comment by JKnuts** [comment]
M-team数据无法识别，1.9.12版本
![image](https://user-images.githubusercontent.com/91355283/180131073-0e6d3cdc-7114-4be8-894a-4c5ce51fc1e4.png)

**Comment by log-time** [comment]
> M-team数据无法识别，1.9.12版本 ![image](https://user-images.githubusercontent.com/91355283/180131073-0e6d3cdc-7114-4be8-894a-4c5ce51fc1e4.png)

我的似乎正常！

**Comment by lightolly** [comment]
我的也正常

**Comment by JKnuts** [comment]
> > M-team数据无法识别，1.9.12版本 ![image](https://user-images.githubusercontent.com/91355283/180131073-0e6d3cdc-7114-4be8-894a-4c5ce51fc1e4.png)
> 
> 我的似乎正常！

好像是两步验证的原因，我把Mteam的两步验证关了就可以识别了

**Comment by tengsihai** [comment]
你好，如果有时间请麻烦适配下greatposterwall.com，目前统计信息无法展示

**Comment by lightolly** [comment]
> 你好，如果有时间请麻烦适配下greatposterwall.com，目前统计信息无法展示

是中文版的cookies么，哪块显示有问题？新版本应该是正常的

**Comment by noname0emmm** [comment]
你好，能否适配一下北洋园PT、天雪还有北邮人

**Comment by tengsihai** [comment]
> 

我正常像其他站一样抓取cookie其他的站没问题海豹不行用的最新版

**Comment by lightolly** [comment]
北洋和🦭已经适配了
方便截图看下数据状态么

**Comment by noname0emmm** [comment]
> 北洋和🦭已经适配了 方便截图看下数据状态么

北洋和北邮是我cookies没配置好的问题，天雪还不行

**Comment by lightolly** [comment]
> 

#604

**Comment by KyoMio** [comment]
btschool一直连接失败，获取不到数据，但是签到提示是成功的。

**Comment by lightolly** [comment]
> btschool一直连接失败，获取不到数据，但是签到提示是成功的。

学校站点负载太高了，等站免过后更新下cookies就行了

**Comment by KyoMio** [comment]
> > btschool一直连接失败，获取不到数据，但是签到提示是成功的。
> 
> 学校站点负载太高了，等站免过后更新下cookies就行了
好的谢谢

**Comment by thsrite** [comment]
站点维护了学校，但是数据统计没有学校。

**Comment by y403321959** [comment]
大佬，学校是不是连不上了。

**Comment by lightolly** [comment]
> 大佬，学校是不是连不上了。

学校填写cookies的时候 貌似也需要将取cookies的浏览器的ua也填写到nastool中才行

**Comment by KyoMio** [comment]
> > 大佬，学校是不是连不上了。
> 
> 学校填写cookies的时候 貌似也需要将取cookies的浏览器的ua也填写到nastool中才行

但是我填了对应的UA，他还是加载不出来学校的数据

**Comment by y403321959** [comment]
> 

我也试了试，也不行。。

**Comment by y403321959** [comment]
> > 大佬，学校是不是连不上了。
> 
> 学校填写cookies的时候 貌似也需要将取cookies的浏览器的ua也填写到nastool中才行

我也试了试，也不行。。

**Comment by log-time** [comment]
@lightolly 学校似乎确实有问题，那么多天就没连上过。

**Comment by lightolly** [comment]
> @lightolly 学校似乎确实有问题，那么多天就没连上过。

应该是5s盾的原因，用浏览器相同的ua+个人信息页面的cookies我这边正常的
配置完成ua nastool重启下

**Comment by log-time** [comment]
站点ua是否能考虑每个站点单独设置？弄一个默认的ua，有特别需要的可以单独设置，有好几个站点对ua有要求了。

**Comment by KyoMio** [comment]
> > @lightolly 学校似乎确实有问题，那么多天就没连上过。
> 
> 应该是5s盾的原因，用浏览器相同的ua+个人信息页面的cookies我这边正常的 配置完成ua nastool重启下

添加一个FlareSolverr的配置项？接入个flaresolverr用来破5s盾怎么样。
在docker控制台里小测了一下，学校的请求返回了一个cf的空白页面，在win的环境下尝试就一切正常能拉取到学校的完整页面。我ua和cookie是同一个浏览器获取的肯定没错，也重启过，感觉就是nas的docker客户端被cf判断为爬虫了。
（一知半解不是很懂）

返回的cf响应：
```
<html>

<body>
    <script language="javascript" type="ee57680eace08e798edf4399-text/javascript">
        window.location = "/?__" + "SAKURA" + "=" + "3d1f17e" + "db" + "1fb" + "1f11d" + "1" + "3334bd" + "35532c52" +
            "9166081" + "0238_260" + "2" + "7" + "938" + "1";
    </script>
    <script src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js"
        data-cf-settings="ee57680eace08e798edf4399-|49" defer=""></script>
</body>

</html>
```

**Comment by log-time** [comment]
我这边啥都没干，今天最新版学校又正常了

**Comment by lightolly** [comment]
我找时间研究下自动过盾的 应该会稳定不少

**Comment by lightolly** [comment]
> > > @lightolly 学校似乎确实有问题，那么多天就没连上过。
> 
> > 
> 
> > 应该是5s盾的原因，用浏览器相同的ua+个人信息页面的cookies我这边正常的 配置完成ua nastool重启下
> 
> 
> 
> 添加一个FlareSolverr的配置项？接入个flaresolverr用来破5s盾怎么样。
> 
> 在docker控制台里小测了一下，学校的请求返回了一个cf的空白页面，在win的环境下尝试就一切正常能拉取到学校的完整页面。我ua和cookie是同一个浏览器获取的肯定没错，也重启过，感觉就是nas的docker客户端被cf判断为爬虫了。
> 
> （一知半解不是很懂）
> 
> 
> 
> 返回的cf响应：
> 
> ```
> 
> <html>
> 
> 
> 
> <body>
> 
>     <script language="javascript" type="ee57680eace08e798edf4399-text/javascript">
> 
>         window.location = "/?__" + "SAKURA" + "=" + "3d1f17e" + "db" + "1fb" + "1f11d" + "1" + "3334bd" + "35532c52" +
> 
>             "9166081" + "0238_260" + "2" + "7" + "938" + "1";
> 
>     </script>
> 
>     <script src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js"
> 
>         data-cf-settings="ee57680eace08e798edf4399-|49" defer=""></script>
> 
> </body>
> 
> 
> 
> </html>
> 
> ```

嗯 在考虑过盾方案了

**Comment by lightolly** [comment]
> 站点ua是否能考虑每个站点单独设置？弄一个默认的ua，有特别需要的可以单独设置，有好几个站点对ua有要求了。

这个可以的

**Comment by KyoMio** [comment]
啥也没动学校又正常了┐(‘～`；)┌

**Comment by y403321959** [comment]
啥也没动学校又正常了┐(‘～`；)┌

**Comment by RUANRUI1995** [comment]
我这里学校和车pt都不行，学校在站点统计里面有，但是数据更新不了。车是直接没有。这两个都用的是cf

**Comment by KyoMio** [comment]
> 我这里学校和车pt都不行，学校在站点统计里面有，但是数据更新不了。车是直接没有。这两个都用的是cf

车好像没问题啊，一直都行的。

**Comment by RUANRUI1995** [comment]
> > 我这里学校和车pt都不行，学校在站点统计里面有，但是数据更新不了。车是直接没有。这两个都用的是cf
> 
> 车好像没问题啊，一直都行的。

签到提示cookie过期又是啥问题呢？更新了也一样

**Comment by KyoMio** [comment]
> > > 我这里学校和车pt都不行，学校在站点统计里面有，但是数据更新不了。车是直接没有。这两个都用的是cf
> > 
> > 
> > 车好像没问题啊，一直都行的。
> 
> 签到提示cookie过期又是啥问题呢？更新了也一样

进站里注销登录再重新登陆一下，把浏览器ua和重新抓的cookie配置进去，再重启试试。

**Comment by RUANRUI1995** [comment]
> > > > 我这里学校和车pt都不行，学校在站点统计里面有，但是数据更新不了。车是直接没有。这两个都用的是cf
> > > 
> > > 
> > > 车好像没问题啊，一直都行的。
> > 
> > 
> > 签到提示cookie过期又是啥问题呢？更新了也一样
> 
> 进站里注销登录再重新登陆一下，把浏览器ua和重新抓的cookie配置进去，再重启试试。

这样弄了以后车正常了，学校还是没法更新数据和签到。另外天雪和海豹数据正常，但是签到提示cookie过期

**Comment by RUANRUI1995** [comment]
![image](https://user-images.githubusercontent.com/18418418/185576550-91a1a2ff-403b-4630-8558-29ec05358f49.png)
这种啥问题啊 我就修改了一下站点名字就每个都重复了

**Comment by log-time** [comment]
> ![image](https://user-images.githubusercontent.com/18418418/185576550-91a1a2ff-403b-4630-8558-29ec05358f49.png) 这种啥问题啊 我就修改了一下站点名字就每个都重复了

明天再看？

**Comment by RUANRUI1995** [comment]
> > ![image](https://user-images.githubusercontent.com/18418418/185576550-91a1a2ff-403b-4630-8558-29ec05358f49.png) 这种啥问题啊 我就修改了一下站点名字就每个都重复了
> 
> 明天再看？

还是重复的 应该是修改名字之前有数据 修改之后数据没有合并 旧的当成独立站点了

**Comment by lightolly** [comment]
> > > ![image](https://user-images.githubusercontent.com/18418418/185576550-91a1a2ff-403b-4630-8558-29ec05358f49.png) 这种啥问题啊 我就修改了一下站点名字就每个都重复了
> 
> > 
> 
> > 明天再看？
> 
> 
> 
> 还是重复的 应该是修改名字之前有数据 修改之后数据没有合并 旧的当成独立站点了

这个得去数据库修改下历史站点数据了

**Comment by lightolly** [comment]
签到那块的cookies过期有的判断不准确

**Comment by RUANRUI1995** [comment]
数据问题操作数据库解决了，开放数据库操作还挺好

**Comment by dwwl886** [comment]
![image](https://user-images.githubusercontent.com/41872694/188176990-749e7483-1468-42ad-aecc-0fa5c40e4408.png)

https://www.hd.ai   一直提示错误

**Comment by sherlockHlb** [comment]
21:49:52 INFO - 【SEARCHER】开始检索 异世界药局 ...
21:49:52 INFO - 【JACKETT】开始检索 异世界药局，站点：['acgrip'] ...
21:49:52 INFO - 【JACKETT】开始检索Indexer：ACG.RIP ...
21:49:53 WARN - 【JACKETT】ACG.RIP 返回数据：30

ACG.RIP返回有问题,
直接显示返回数据30.
但是没有处理下文
DMHY则是无法索引到种子...

**Comment by sherlockHlb** [comment]
![image](https://user-images.githubusercontent.com/30238046/188465362-7691fe18-07ff-4420-bbff-78c2e5661d76.png)

**Comment by ChuckPeng** [comment]
我这边添加M-Team站点，一直说未检测到已登录，请检查cookie是否过期，把cookie去掉，他又不是提示了，但无法搜索到M-Team的任何资源
<img width="238" alt="11" src="https://user-images.githubusercontent.com/21271650/189049081-4107711f-80bc-4cfc-9ecc-b43e273d7748.png">

**Comment by log-time** [comment]
> 我这边添加M-Team站点，一直说未检测到已登录，请检查cookie是否过期，把cookie去掉，他又不是提示了，但无法搜索到M-Team的任何资源 <img alt="11" width="238" src="https://user-images.githubusercontent.com/21271650/189049081-4107711f-80bc-4cfc-9ecc-b43e273d7748.png">

关掉二次验证试试？

**Comment by Tartarus2014** [comment]
<img class="hitandrun" src="pic/trans.gif" alt="H&amp;R" title="H&amp;R">    
https://ourbits.club/index.php  我堡的hr

**Comment by huluohu** [comment]
https://nextpt.net 飞天拉面神教 ，小站，能否适配下。

**Comment by lightolly** [comment]
这个站点貌似还在调整代码，有不少信息没有，可以等一段时间稳定之后再看看
> https://nextpt.net 飞天拉面神教 ，小站，能否适配下。

**Comment by zhushu11** [comment]
BTSCHOOL 可否适配，站点维护中可以添加，点击名称也能跳转到网页，但是数据统计、每日签到都无法实现

**Comment by tianzhuosx** [comment]
还有以下几个站没有内建索引器，希望到大佬可以适配下，感谢。
1. https://wintersakura.net/index.php
2. https://www.hd.ai/index.php
3. http://hdmayi.com/index.php
4. https://www.haidan.video/index.php

**Comment by huluohu** [comment]
me too---- 回复的原邮件 ***@***.***>发送日期2022年10月05日 11:19 ***@***.***> ***@***.******@***.***>主题Re: [jxxghp/nas-tools] 【汇总】站点管理数据统计适配需求在此提交 (Issue #450)

BTSCHOOL 可否适配，站点维护中可以添加，点击名称也能跳转到网页，但是数据统计、每日签到都无法实现



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/jxxghp/nas-tools/issues/450#issuecomment-1267870778",

"url": "https://github.com/jxxghp/nas-tools/issues/450#issuecomment-1267870778",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Jay-Young** [comment]
avistaz系列站点好像都不支持数据统计？
[AvistaZ](https://avistaz.to/) [AnimeZ](https://animez.to/) [PrivateHD](https://privatehd.to/) [CinemaZ](https://cinemaz.to/) [ExoticaZ](https://exoticaz.to/)

**Comment by thsrite** [comment]
22:23:47 ERROR - 【PT】站点 m-team 连接失败：https://kp.m-team.cc
22:23:57 ERROR - 【PT】站点 btschool 连接失败：https://pt.btschool.club
22:24:01 ERROR - 【PT】站点 hdtime 连接失败：https://hdtime.org
22:24:15 ERROR - 【PT】站点 greatposterwall 连接失败：https://greatposterwall.com
22:25:29 ERROR - 【PT】站点 hares 连接失败：https://club.hares.top

这几个站点，在容器内都可以ping通，为啥这里显示链接失败。
<img width="670" alt="image" src="https://user-images.githubusercontent.com/54088512/194338996-73519cd3-82ff-41e2-9ef2-4e654dc1f6cc.png">
<img width="568" alt="image" src="https://user-images.githubusercontent.com/54088512/194339111-3f21fc5c-3154-47e7-9a3c-fadd01ac4ff1.png">

**Comment by KyoMio** [comment]
v2.2.0版本，数据统计页面还是无法显示学校，并且资源浏览里打开学校显示无资源。

日志里面显示的是跳转失败。

**Comment by Antonchenxr** [comment]
v2.2.0 版本 可以看到具体的每个站的数据，但是饼图不工作也不记录任何当天的变化，同时【PT】站点 m-team 连接失败：https://kp.m-team.cc/    之前v2.1.3的时候应该都是ok的

**Comment by xuzhe1224** [comment]
CHD（https://chdbits.co/） 能适配下吗？谢谢

**Comment by minsa** [comment]
白兔（[https://club.hares.top/index.php](https://club.hares.top/index.php)）的做种数和做种体积不正常，都显示为0

**Comment by lxzx21** [comment]
织梦zmpt.cc求大佬适配 谢谢

**Comment by lightolly** [comment]
> 白兔（[https://club.hares.top/index.php](https://club.hares.top/index.php)）的做种数和做种体积不正常，都显示为0

白兔改界面了，这块抽时间改下

**Comment by lightolly** [comment]
> 织梦( https://zmpt.cc  )求大佬适配 谢谢

这个是站点数据没有么？理论上小站应该正常的

**Comment by lxzx21** [comment]
> > 织梦( https://zmpt.cc  )求大佬适配 谢谢
> 
> 这个是站点数据没有么？理论上小站应该正常的

索引器里没有  求支持

**Comment by xuzhe1224** [comment]
> > CHD（[https://chdbits.co/）](https://chdbits.co/%EF%BC%89) 能适配下吗？谢谢
> 
> 这块没有号，得有号的大佬帮忙看看了

我有号啊，需要做什么？

**Comment by lcylgs** [comment]
希望支持https://jpopsuki.eu/index.php
目前统计报错
01:12:29 ERROR - 【Sites】站点 jpopsuki 获取流量数据失败：list index out of range - Traceback (most recent call last): File "/nas-tools/app/sites/sites.py", line 186, in __refresh_pt_data site_user_info.parse() File "/nas-tools/app/sites/siteuserinfo/site_user_info.py", line 100, in parse self._parse_user_traffic_info(self._get_page_content(urljoin(self._base_url, self._user_traffic_page))) File "/nas-tools/app/sites/siteuserinfo/small_horse.py", line 46, in _parse_user_traffic_info self.join_at = str(tmps[1].xpath("li")[0].xpath("span//text()")[0]) IndexError: list index out of range

**Comment by EliteOtaku** [comment]
https://webhd.cc/
很不错的一个字幕和电视电影资源站点，希望能早日适配

**Comment by lightolly** [comment]
> 白兔（https://club.hares.top/index.php）的做种数和做种体积不正常，都显示为0

#1781

**Comment by lxzx21** [comment]
希望内置索引器支持一下 织梦(https://zmpt.cc)

**Comment by banbiantan** [comment]
希望支持一下 莫妮卡 monikadesign [https://monikadesign.uk/](url)

**Comment by Mrxlei** [comment]
PTTIME能正常使用吗？

**Comment by flowdesign-github** [comment]
CCF https://ccfbits.org/ 站点没有正常抓取用户的数据, 搜索也无法获取该站点的数据

![image](https://user-images.githubusercontent.com/87160795/201817691-400eda0b-1b64-4c22-a20b-216063acb73d.png)

**Comment by MyFaith** [comment]
HDSKY 获取不到等级和加入时间
![image](https://user-images.githubusercontent.com/8826441/201833353-9d814739-7386-4a60-b259-33f8381f38fb.png)

**Comment by beichengmiwang** [comment]
作者您好，求适配wintersakura.net冬樱。目前冬樱添加站点后无法查看站点资源，求适配站点资源。签到的话因为站长加了cf。也没法实现

**Comment by serenity666** [comment]
TorrentLeechorg站无法登录，通过油猴插件导入cookie也无法使用
![image](https://user-images.githubusercontent.com/64485323/204251219-4e335cb5-5de7-49b2-8ae8-e832a3f3cdca.png)

**Comment by Egolas** [comment]
作者您好，[HDCity](https://hdcity.city/)  似乎无法正确识别

**Comment by huluohu** [comment]
[海豹](https://greatposterwall.com/index.php) 劳烦适配

**Comment by yzlyu** [comment]
[HUNO](https://hawke.uno/) 
请求适配，谢谢！

**Comment by DamonWangL** [comment]
m-team下载提示“添加下载失败 Url链接为空！”，请求适配

**Comment by huluohu** [comment]
> m-team下载提示“添加下载失败 Url链接为空！”，请求适配

你是真敢提啊，劝你删掉吧，要不作者必怼你

**Comment by DamonWangL** [comment]
> > m-team下载提示“添加下载失败 Url链接为空！”，请求适配
> 
> 你是真敢提啊，劝你删掉吧，要不作者必怼你

一脸懵，可以问下为什么吗

**Comment by DamonWangL** [comment]
> > m-team下载提示“添加下载失败 Url链接为空！”，请求适配
> 
> 你是真敢提啊，劝你删掉吧，要不作者必怼你

因为mt站提供的是种子不是种子的url？

**Comment by 1245040330** [comment]
https://www.bugutv.net/ 布谷tv可以适配吗

**Comment by kai456789** [comment]
http://hdmayi.com/ 
站點資源不顯示 其他正常

**Comment by RoninAaron** [comment]
求问下大佬 憨憨的做中体积显示不正确 是什么原因造成的啊？

**Comment by soupice** [comment]
BT之家 希望能配置

**Comment by 48542257** [comment]
更新2.7.2后发现使用内建索引器 站点管理-站点资源无法显示。我使用的MT和PTHOME。请大佬看一下、

**Comment by maxin-cn** [comment]
> > 北洋和🦭已经适配了 方便截图看下数据状态么
> 
> 北洋和北邮是我cookies没配置好的问题，天雪还不行

hello，请问下北洋园的cookies应该怎么配置呢，我在站点管理里面能够测试通过，但是数据统计里面是空的。

**Comment by ncj1990** [comment]
麻烦匹配下1ptba.com和carpt.net两个站点
cookie登录报错
站点 1ptba 获取流量数据失败：expected str, bytes or os.PathLike object, not NoneType - Traceback (most recent call last): File "/volume1/@appstore/NASTool/nas-tools/app/sites/sites.py", line 230, in __refresh_site_data site_user_info = SiteUserInfoFactory().build(url=site_url, File "/volume1/@appstore/NASTool/nas-tools/app/sites/site_user_info_factory.py", line 38, in build if not chrome.visit(url=url, ua=ua, cookie=site_cookie): File "/volume1/@appstore/NASTool/nas-tools/app/helper/chrome_helper.py", line 74, in visit if not self.browser: File "/volume1/@appstore/NASTool/nas-tools/app/helper/chrome_helper.py", line 39, in browser self._chrome = self.__get_browser() File "/volume1/@appstore/NASTool/nas-tools/app/helper/chrome_helper.py", line 69, in __get_browser chrome = ChromeWithPrefs(options=options, driver_executable_path=self._executable_path) File "/volume1/@appstore/NASTool/nas-tools/app/helper/chrome_helper.py", line 174, in __init__ super().__init__(*args, options=options, **kwargs) File "/var/packages/NASTool/target/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 409, in __init__ browser = subprocess.Popen( File "/var/packages/Python3.9/target/usr/lib/python3.9/subprocess.py", line 951, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/var/packages/Python3.9/target/usr/lib/python3.9/subprocess.py", line 1696, in _execute_child and os.path.dirname(executable) File "/var/packages/Python3.9/target/usr/lib/python3.9/posixpath.py", line 152, in dirname p = os.fspath(p) TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by linqinpeng910927** [comment]
请求适配https://www.haidan.video/

**Comment by luoxiao-xy** [comment]
内置索引器希望能适配冬樱https://wintersakura.net/
一个比较有潜力的新站，有官组，更新也满勤的

**Comment by sususu98** [comment]
希望适配[北邮人](https://byr.pt/index.php)

**Comment by bg4vrg** [comment]
求修复明教hdpt和猪猪保种数据只显示100条的bug

**Comment by luoxiao-xy** [comment]
请求适配朱雀 https://zhuque.in/

**Comment by onlyLTY** [comment]
请求适配朱雀 https://zhuque.in/

**Comment by madaowinterh** [comment]
辛苦适配开启两步验证的馒头

**Comment by iizx** [comment]
你好，如果有时间请麻烦适配下https://cyanbug.net/，目前在无法搜索站点资源，站点结构与阿童木类似

**Comment by bg4vrg** [comment]
感谢大佬，今天升级最新版本后发现明教和猪猪做种数和做种体积已经能正确识别了。

不可说出现做种体积只能识别200个的问题，之前没有注意到是否正常

**Comment by Hcczz** [comment]
你好，如果有时间请麻烦适配下[https://skyeysnow.com](https://skyeysnow.com) 无法搜索站点资源

**Comment by bimzcy** [comment]
看楼上有两人求冬樱了，半年了也没适配，我也来求冬樱wintersakura.net

**Comment by Mrxlei** [comment]
【dicmusic】模拟登录失败，无法打开网站！
使用站点测速反馈如下：
dicmusic | 否 | 379 毫秒 | 无法打开网站
同一时间用浏览器打开站点是正常的，请大佬测试一下
