### ISSUE TITLE
企业微信配置一直提示回调未通过

### ISSUE THREAD

**Issue by wklesss** [jxxghp/nas-tools#53]
日志如下

2022-04-18 11:23:27,493	ERROR: 微信请求验证失败 VerifyURL ret: -40003

[2022-04-18 11:23:27,493] ERROR in app: Exception on /wechat [GET]

Traceback (most recent call last):

  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app

    response = self.full_dispatch_request()

  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1526, in full_dispatch_request

    return self.finalize_request(rv)

  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1545, in finalize_request

    response = self.make_response(rv)

  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1701, in make_response

    raise TypeError(

TypeError: The view function for 'wechat' did not return a valid response. The function either returned None or ended without a return statement.

**Comment by wklesss** [comment]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/29318238/163749759-a9907d0f-935a-4ea0-b506-bb86c0094ede.png">
<img width="692" alt="image" src="https://user-images.githubusercontent.com/29318238/163749780-df32719f-45c9-4f78-88f1-f55cc423876f.png">

**Comment by wklesss** [comment]
是否是由于域名是通过ipv6端口映射造成。烦请大佬帮忙看一下

**Comment by sungamma** [comment]
v6的我也搞不了，v4的没问题

**Comment by jxxghp** [comment]
我没有ipv6的环测试不了，确定按下面的说明操作了吗？
    ## 配置步聚：
    # 1、在微信企业应用接收消息设置页面生成Token和EncodingAESKey并填入下面区域。
    # 2、重启本程序。
    # 3、在微信企业应用接收消息设置页面输入此地址：http(s)://ip:3000/wechat，需要有公网IP并做好端口转发，最好要有域名

**Comment by wklesss** [comment]
> 我没有ipv6的环测试不了，确定按下面的说明操作了吗？ ## 配置步聚： # 1、在微信企业应用接收消息设置页面生成Token和EncodingAESKey并填入下面区域。 # 2、重启本程序。 # 3、在微信企业应用接收消息设置页面输入此地址：http(s)://ip:3000/wechat，需要有公网IP并做好端口转发，最好要有域名

完全按照上述步骤操作

**Comment by wklesss** [comment]
> v6的我也搞不了，v4的没问题

我主要是想确定是否是企业微信不支持ipv6

**Comment by sungamma** [comment]
> Reference

应该是不支持的
