### ISSUE TITLE
amd64 Linux环境本地运行报错

### ISSUE THREAD

**Issue by yubanmeiqin9048** [jxxghp/nas-tools#688]
系统版本：`Ubuntu 20.04.3 LTS`
Python版本：`Python 3.8.10`
NASTool 版本：`v1.9.21`

安装依赖：`python3 -m pip install -r requirements.txt`
```
Requirement already satisfied: markupsafe>=2.1.1 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: flask>=2.1.1 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (2.2.2)
Requirement already satisfied: requests[socks]>=2.27.1 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (2.28.1)
Requirement already satisfied: urllib3>=1.26.9 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (1.26.11)
Requirement already satisfied: APScheduler>=3.9.1 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (3.9.1)
Requirement already satisfied: tmdbv3api>=1.7.6 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (1.7.7)
Requirement already satisfied: qbittorrent-api>=2022.4.30 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (2022.8.35)
Requirement already satisfied: watchdog>=2.1.7 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (2.1.9)
Requirement already satisfied: flask-httpauth>=4.5.0 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (4.7.0)
Requirement already satisfied: pycryptodome>=3.14.1 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (3.15.0)
Requirement already satisfied: pyyaml>=6.0 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (6.0)
Requirement already satisfied: transmission-rpc>=3.3.0 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 12)) (3.3.2)
Requirement already satisfied: lxml>=4.8.0 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 13)) (4.9.1)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 14)) (4.11.1)
Requirement already satisfied: flask-login>=0.6.0 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 15)) (0.6.2)
Requirement already satisfied: cn2an>=0.5.16 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 16)) (0.5.17)
Requirement already satisfied: anitopy>=2.1.0 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 17)) (2.1.1)
Requirement already satisfied: supervisor>=4.2.4 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 18)) (4.2.4)
Requirement already satisfied: ruamel.yaml>=0.17.19 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 19)) (0.17.21)
Requirement already satisfied: plexapi>=4.10.1 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 20)) (4.12.1)
Requirement already satisfied: python-opensubtitles>=0.6.dev0 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 21)) (0.6.dev0)
Requirement already satisfied: parse>=1.19.0 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 22)) (1.19.0)
Requirement already satisfied: bencode.py>=4.0.0 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 23)) (4.0.0)
Requirement already satisfied: cacheout>=0.13.1 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 24)) (0.13.1)
Requirement already satisfied: cssselect>=1.1.0 in /home/zhang/.local/lib/python3.8/site-packages (from -r requirements.txt (line 25)) (1.1.0)
Requirement already satisfied: importlib-metadata>=3.6.0; python_version < "3.10" in /home/zhang/.local/lib/python3.8/site-packages (from flask>=2.1.1->-r requirements.txt (line 2)) (4.12.0)
Requirement already satisfied: Werkzeug>=2.2.2 in /home/zhang/.local/lib/python3.8/site-packages (from flask>=2.1.1->-r requirements.txt (line 2)) (2.2.2)
Requirement already satisfied: click>=8.0 in /home/zhang/.local/lib/python3.8/site-packages (from flask>=2.1.1->-r requirements.txt (line 2)) (8.1.3)
Requirement already satisfied: itsdangerous>=2.0 in /home/zhang/.local/lib/python3.8/site-packages (from flask>=2.1.1->-r requirements.txt (line 2)) (2.1.2)
Requirement already satisfied: Jinja2>=3.0 in /home/zhang/.local/lib/python3.8/site-packages (from flask>=2.1.1->-r requirements.txt (line 2)) (3.1.2)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/zhang/.local/lib/python3.8/site-packages (from requests[socks]>=2.27.1->-r requirements.txt (line 3)) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests[socks]>=2.27.1->-r requirements.txt (line 3)) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests[socks]>=2.27.1->-r requirements.txt (line 3)) (2019.11.28)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6; extra == "socks" in /home/zhang/.local/lib/python3.8/site-packages (from requests[socks]>=2.27.1->-r requirements.txt (line 3)) (1.7.1)
Requirement already satisfied: tzlocal!=3.*,>=2.0 in /home/zhang/.local/lib/python3.8/site-packages (from APScheduler>=3.9.1->-r requirements.txt (line 5)) (4.2)
Requirement already satisfied: six>=1.4.0 in /usr/lib/python3/dist-packages (from APScheduler>=3.9.1->-r requirements.txt (line 5)) (1.14.0)
Requirement already satisfied: setuptools>=0.7 in /usr/lib/python3/dist-packages (from APScheduler>=3.9.1->-r requirements.txt (line 5)) (45.2.0)
Requirement already satisfied: pytz in /home/zhang/.local/lib/python3.8/site-packages (from APScheduler>=3.9.1->-r requirements.txt (line 5)) (2022.2.1)
Requirement already satisfied: typing_extensions<5.0.0.0,>=3.7.4.2 in /home/zhang/.local/lib/python3.8/site-packages (from transmission-rpc>=3.3.0->-r requirements.txt (line 12)) (4.3.0)
Requirement already satisfied: soupsieve>1.2 in /home/zhang/.local/lib/python3.8/site-packages (from beautifulsoup4>=4.11.1->-r requirements.txt (line 14)) (2.3.2.post1)
Requirement already satisfied: proces>=0.1.0 in /home/zhang/.local/lib/python3.8/site-packages (from cn2an>=0.5.16->-r requirements.txt (line 16)) (0.1.2)
Requirement already satisfied: ruamel.yaml.clib>=0.2.6; platform_python_implementation == "CPython" and python_version < "3.11" in /home/zhang/.local/lib/python3.8/site-packages (from ruamel.yaml>=0.17.19->-r requirements.txt (line 19)) (0.2.6)
Requirement already satisfied: zipp>=0.5 in /usr/lib/python3/dist-packages (from importlib-metadata>=3.6.0; python_version < "3.10"->flask>=2.1.1->-r requirements.txt (line 2)) (1.0.0)
Requirement already satisfied: pytz-deprecation-shim in /home/zhang/.local/lib/python3.8/site-packages (from tzlocal!=3.*,>=2.0->APScheduler>=3.9.1->-r requirements.txt (line 5)) (0.1.0.post0)
Requirement already satisfied: backports.zoneinfo; python_version < "3.9" in /home/zhang/.local/lib/python3.8/site-packages (from tzlocal!=3.*,>=2.0->APScheduler>=3.9.1->-r requirements.txt (line 5)) (0.2.1)
Requirement already satisfied: zhconv==1.4.3 in /home/zhang/.local/lib/python3.8/site-packages (from proces>=0.1.0->cn2an>=0.5.16->-r requirements.txt (line 16)) (1.4.3)
Requirement already satisfied: tzdata; python_version >= "3.6" in /home/zhang/.local/lib/python3.8/site-packages (from pytz-deprecation-shim->tzlocal!=3.*,>=2.0->APScheduler>=3.9.1->-r requirements.txt (line 5)) (2022.2)
```

运行`python3 run.py`
```
zhang@ubuntu:~/nas-tools$ python3 run.py
配置文件地址：/home/zhang/nas-tools/config/config.yaml
NASTool 当前版本号：v1.9.21
日志输出类型为：file
日志将写入文件：/config/logs
Traceback (most recent call last):
  File "run.py", line 37, in <module>
    if not check_config(config):
  File "/home/zhang/nas-tools/utils/check_config.py", line 39, in check_config
    log.info("WEB管理页面用户：%s" % str(login_user))
  File "/home/zhang/nas-tools/log.py", line 83, in info
    return Logger.get_instance().logger.info(text)
  File "/home/zhang/nas-tools/log.py", line 64, in get_instance
    Logger.__instance = Logger()
  File "/home/zhang/nas-tools/log.py", line 45, in __init__
    os.makedirs(logpath)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/config'
```
运行`sudo python3 run.py`
```
zhang@ubuntu:~/nas-tools$ sudo python3 run.py
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    import log
  File "/home/zhang/nas-tools/log.py", line 8, in <module>
    from config import Config
  File "/home/zhang/nas-tools/config.py", line 4, in <module>
    import ruamel.yaml
ModuleNotFoundError: No module named 'ruamel'
```

**Comment by jxxghp** [comment]
这个不是环境问题吗？ 你普通用户没目录权限。管理员用户没有安装依赖啊。

**Comment by yubanmeiqin9048** [comment]
> 这个不是环境问题吗？ 你普通用户没目录权限。管理员用户没有安装依赖啊。

请问以普通用户运行nas-tools还需要哪些目录权限，nas-tools目录权限我是给满的

**Comment by yubanmeiqin9048** [comment]
> 

请问需要哪些目录权限
