### ISSUE TITLE
更新2.0.3出错，提示配置文件不对

### ISSUE THREAD

**Issue by evanjiang404** [jxxghp/nas-tools#846]
直接在浏览器上更新的，没有更改过配置文件，
更新之后提示：
```
配置文件地址：/config/config.yaml
NASTool 当前版本号：v2.0.3
【ERROR】配置文件 config.yaml 格式出现严重错误！请检查：'laboratory'
配置文件格式错误，找不到app配置项！
Traceback (most recent call last):
  File "/nas-tools/run.py", line 78, in <module>
    if not check_config(config):
  File "/nas-tools/app/utils/check_config.py", line 128, in check_config
    log.error("配置文件格式错误，找不到media配置项！")
  File "/nas-tools/log.py", line 93, in error
    return Logger.get_instance().logger.error(text)
  File "/nas-tools/log.py", line 68, in get_instance
    Logger.__instance = Logger()
  File "/nas-tools/log.py", line 49, in __init__
    os.makedirs(logpath)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```
删除镜像重新拉取未能解决问题

**Comment by KyoMio** [comment]
把映射的文件夹里面的config.yaml删掉再重启。

**Comment by evanjiang404** [comment]
打开了，在后面追加了实验室功能：
```
# 【实验室】
laboratory:
  # 【识别增强】关键字猜想
  search_keyword: false
  # 【TMDB缓存过期策略】：是否开启TMDB缓存过期策略，默认7天过期，过期缓存将被删除,  7天内访问过期时间可以被刷新
  tmdb_cache_expire: false
  # 【使用豆瓣名称联想】：开启将使用豆瓣进行电影电视剧的名称联想，否则使用TMDB的数据
  use_douban_titles: true
  # 【精确搜索使用英文名称】：开启后对于精确搜索场景（远程搜索、订阅搜索等）将会使用英文名检索站点资源以提升匹配度，但对有些站点资源标题全是中文的则需要关闭，否则匹配不到
  search_en_title: false
  # 【订阅API认证密钥】
  subscribe_token:
```
2.0的配置文件多了这个部分，不加这个打不开

**Comment by jxxghp** [comment]
修复了
