### ISSUE TITLE
filetransfer出错

### ISSUE THREAD

**Issue by ChenZheying** [jxxghp/nas-tools#854]
根据[页面提示](https://github.com/jxxghp/nas-tools#8整理存量媒体资源可选)中的“整理存量媒体资源——docker版本”进行操作，
执行命令：``python3 /nas-tools/app/filetransfer.py -m link -s /video/movies``，得到错误提示如下
```
Traceback (most recent call last):
  File "/nas-tools/app/filetransfer.py", line 17, in <module>
    from app.subtitle import Subtitle
  File "/nas-tools/app/subtitle.py", line 4, in <module>
    from pythonopensubtitles.opensubtitles import OpenSubtitles
ModuleNotFoundError: No module named 'pythonopensubtitles'
```
执行命令``pip3 install pythonopensubtitles``，得到错误提示如下
```
ERROR: Could not find a version that satisfies the requirement pythonopensubtitles (from versions: none)
ERROR: No matching distribution found for pythonopensubtitles
```

**Comment by jxxghp** [comment]
安装依赖：
   python3 -m pip install -r requirements.txt
   python3 -m pip install -r third_party.txt
