### ISSUE TITLE
名称识别测试报错

### ISSUE THREAD

**Issue by lowking** [jxxghp/nas-tools#877]
![image](https://user-images.githubusercontent.com/33308659/187657745-49677789-5f17-42ab-b041-289316b900d4.png)
```
[2022-08-31 18:25:04,425] ERROR in app: Exception on /do [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/root/nas-tools/web/main.py", line 1400, in do
    return WebAction().action(cmd, data)
  File "/root/nas-tools/web/action.py", line 126, in action
    return func(data)
  File "/root/nas-tools/web/action.py", line 1489, in __name_test
    "type": media_info.type.value,
AttributeError: 'NoneType' object has no attribute 'type'

```
下面是我写入文本框的内容：
[离谱Sub] 打工吧！！魔王大人 第二季 / はたらく魔王さま!! / Hataraku Maou-sama!! [07v2][HEVC AAC][1080p][PGS简繁内封]

**Comment by lowking** [comment]
```
[2022-09-01 09:20:12,822] ERROR in app: Exception on /do [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/root/nas-tools/web/main.py", line 1402, in do
    return WebAction().action(cmd, data)
  File "/root/nas-tools/web/action.py", line 125, in action
    return func(data)
  File "/root/nas-tools/web/action.py", line 1495, in __name_test
    "type": media_info.type.value if media_info.type else "",
AttributeError: 'NoneType' object has no attribute 'type'

```
dev分支依然报错

**Comment by jxxghp** [comment]
![image](https://user-images.githubusercontent.com/51039935/188043480-5e2780fd-2c08-4cf0-a673-bc229ff5dd81.png)
