### ISSUE TITLE
搜索特定关键字会500错误

### ISSUE THREAD

**Issue by goofysun** [jxxghp/nas-tools#901]
搜索 『红海行动』「消失的孩子」 「名侦探柯南」 等词组，会直接 HTTP 500 错误

以下为日志信息：
======================================================

当前日期：20220901
 * Serving Flask app 'web.main'
 * Debug mode: off
[2022-09-01 21:11:35,736] ERROR in app: Exception on /medialist [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/nas-tools/web/main.py", line 500, in medialist
    medias = DouBan().search_douban_medias(keyword=key_word,
  File "/nas-tools/app/douban.py", line 342, in search_douban_medias
    meta_info.vote_average = item.get("rating", {}).get("value")
AttributeError: 'NoneType' object has no attribute 'get'
[2022-09-01 21:11:40,660] ERROR in app: Exception on /medialist [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/nas-tools/web/main.py", line 500, in medialist
    medias = DouBan().search_douban_medias(keyword=key_word,
  File "/nas-tools/app/douban.py", line 342, in search_douban_medias
    meta_info.vote_average = item.get("rating", {}).get("value")
AttributeError: 'NoneType' object has no attribute 'get'
[2022-09-01 21:11:52,834] ERROR in app: Exception on /do [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/nas-tools/web/main.py", line 1402, in do
    return WebAction().action(cmd, data)
  File "/nas-tools/web/action.py", line 125, in action
    return func(data)
  File "/nas-tools/web/action.py", line 1035, in __media_info
    vote_average = douban_info.get("rating", {}).get("value") or ""
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by jxxghp** [comment]
目测豆瓣又改了接口报文。先把豆瓣的开关关掉，明天适配下。
